### ISSUE TITLE
[Feature Request] Raw HTML to Dash converter

### ISSUE THREAD

**Issue by astariul** [plotly/dash#1013]
**Is your feature request related to a problem? Please describe.**
I'm not fluent in HTML. But I want something beautiful for my Dash app.  
Luckily, there is a bunch of free template on the net.  
But there is no easy way to use these template : I have to use a Dash Layout, not raw HTML.

**Describe the solution you'd like**
Either be able to use raw HTML in Dash (and still be able to use callbacks on specific components), or provide a library to translate raw HTML into a Dash Layout.

**Describe alternatives you've considered**
Someone provided a code for such translation [here](https://community.plot.ly/t/easy-way-to-convert-a-short-text-between-dash-html-object-representation-and-html-raw-string/15985/6), but it's not convenient enough and does not support all the cases.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
