### ISSUE TITLE
[Feature Request] Tag input

### ISSUE THREAD

**Issue by astariul** [plotly/dash#1016]
**Is your feature request related to a problem? Please describe.**
I'm trying to add a `tag input` to my Dash application. I couldn't find such a component in the library, so I tried to add it using [this repo](https://github.com/xoxco/jQuery-Tags-Input).  
However I couldn't success : while my script works perfectly with an input declared in raw HTML, if I declare it inside the Dash layout it's not working.

**Describe the solution you'd like**
A core component for tag input would be perfect.

**Describe alternatives you've considered**
A way to have a tag input, even if not natively.

**Comment by luiztauffer** [comment]
we developed a tag input component here:
https://github.com/Tauffer-Consulting/dash-cool-components

**Comment by SumeetJindal** [comment]
Cool feature. Does it support auto-search/suggestions?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
