### ISSUE TITLE
[BUG] Can't move navbar from `index_string` to `Layout`

### ISSUE THREAD

**Issue by astariul** [plotly/dash#1030]
I'm not a frontend dev...

Anyway to have a working app (and somewhat beautiful), I took a template on internet, and built my Dash app from that template.

To make it work, I used `index_string` to be as close as possible to the template.
Among other things, this is how my index_string is :

```
[...]
<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    [...]
  </nav>

  {%app_entry%}
[...]
```

And it works great !

---

Now my problem :

I need to make a multi-lingual website. I know how to do, however I need to modify the content of the navigation bar depending on the language. 
To do that, I would need to move the navbar from the `index_string` to the Dash Layout.
But if I do that, the javascript is not working anymore... Making my navbar not working (it appears, but is not working).

This is the non working javascript :

```
$('a.js-scroll-trigger[href*="#"]:not([href="#"])').click(function() {
    if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
      // Hide every other thing and un-highlight all non-related menu
      $(".my-content").hide();
      $(".my-menu").removeClass("active");

      // Show only the selected one and set the menu of the selected one as active
      $(this.hash).show();
      $(this).addClass("active");
      console.log($(this));
    }
  });
```

Any idea why moving the navbar make it not working ?

**Comment by alexcjohnson** [comment]
This kind of question is a better fit for https://community.plot.ly but I'll take a quick stab at it here.

That JS is not working because it's being executed before the layout components have been added to the page - at which point `$('a.js-scroll-trigger[href*="#"]:not([href="#"])')` is an empty set.

One kind of hacky way to solve it is by putting that code into a `setInterval` that looks for this element to exist, and then when it finally sees it, attaches the handler and clears the interval. That may work fine, but be aware that if something on the page causes the navbar to rerender (such as a callback that changes the language) it may drop and remake the `<a>` element and you will lose the handler.

It would be more robust if you can rewrite this code as a regular dash callback. I'm not sure if this is all the relevant JS code or if there's more, but I suspect if you post this in the community forum - with as much detail and code as possible, ideally in a full executable form - folks will help identify how that could be done.

**Comment by astariul** [comment]
I'm sorry for posting at the wrong place.

---

@alexcjohnson This is the second time.. Second time you perfectly understand my problem through my mess of a post, and propose me a working solution. Thank you very much !

I simply didn't think of implementing this short javascript into Dash. I did, and it work perfectly ! Thank you again for your precious insights ! ❤️
