### ISSUE TITLE
[Feature Request] Option to wait for DOM to be complete before executing clientside Javascript

### ISSUE THREAD

**Issue by wbrgss** [plotly/dash#1041]
It's confusing and unclear for users that want to use Javascript to modify their Dash app that their Javascript will often execute too early. Normally, we'd tell them to write JS that modifies the DOM such that it it only executes after `DOMContentLoaded`, but I have had trouble getting this to work with Dash (I could be doing something wrong in JS). 

When I've had to do something like this before, I've hacked around it by polling for `document.readyState`:

```js
var interval = setInterval(function(){
   if(document.readyState === 'complete') {
       myMainFunction();
   }
}, 0);

var myMainFunction = function() {
    console.log('I got called');
    ...
    clearInterval(interval);
}
```

Does it make sense to have a config option to wait until Dash has loaded the DOM content to start executing JavaScript? 

**Additional context**
Motivation: https://community.plot.ly/t/add-js-in-dashh-app/32217

**Comment by wbrgss** [comment]
There's an interesting community component that claims to do this (I haven't tested it) here:
https://github.com/zouhairm/dash_defer_js_import

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
