### ISSUE TITLE
[BUG] Couldn't generate collapsible list in dash

### ISSUE THREAD

**Issue by inandasram** [plotly/dash#1047]
```
dash                    1.7.0      
dash-core-components    1.6.0      
dash-html-components    1.0.2      
dash-renderer           1.2.2      
dash-table              4.5.1 
```
    - OS: Windows 10
    - Browser Chrome
    - Version  78.0.3904.87

**Describe the bug**
Trying to implement a collapsible list of elements from dash. But the collapsing and expanding elements were not shown(or rendered) 
Used Jquery library as external scripts but only it was rendered as below
![image](https://user-images.githubusercontent.com/10071722/70795499-f25a7a00-1dc5-11ea-82e8-c65885e5aec3.png)

**Expected behavior**
The below image is created by locally creating a html and invoking the js scripts.

![image](https://user-images.githubusercontent.com/10071722/70795346-a14a8600-1dc5-11ea-9513-b6628027a23d.png)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
