### ISSUE TITLE
[BUG] multipage dash app interferes with flask routing

### ISSUE THREAD

**Issue by schmidt-jake** [plotly/dash#1079]
```
dash                       1.7.0
dash-bootstrap-components  0.7.2
dash-core-components       1.6.0
dash-daq                   0.1.7
dash-html-components       1.0.2
dash-renderer              1.2.2
dash-table                 4.5.1
```
I'm building a multi-page Dash app with a callback trigger on dcc.Location that also uses `flask.send_from_directory` in a Flask route. However, the Dash callback seems to be interfering with the Flask route because `flask.send_from_directory` is no longer fired in its flask route.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
