### ISSUE TITLE
[BUG] ES6 regenerator features aren't polyfilled (?)

### ISSUE THREAD

**Issue by wbrgss** [plotly/dash#1087]
On non-ES6/ES2015+ etc compatible browsers, I think there may be an issue with async Dash (`>= 1.5.0`) and "regenerator runtime". The error is `ReferenceError: regeneratorRuntime is not defined` in the JS console, specifically when trying to use async Dash Table. Hopefully this could be fixed in the webpack config, see https://babeljs.io/docs/en/babel-polyfill (`import "regenerator-runtime/runtime"`) and [here](https://github.com/babel/babel/issues/8829#issuecomment-456524916) (`... "regenerator": true`).

cc @Marc-Andre-Rivet

**Comment by wbrgss** [comment]
The user who reported this bug is using Chrome `Version 79.0.3945.117 (Official Build) (64-bit)` — so I doubt it's simply an issue with an old browser as @Marc-Andre-Rivet originally hypothesized

**Comment by mrgianlu** [comment]
I am having this after switching from single-page to multi-page dash
any way to solve it?

**Comment by mrgianlu** [comment]
> I am having this after switching from single-page to multi-page dash, for the datatable component only
> any way to solve it?

Returning here for saying that I fixed this by doing a fresh install of dash, making sure to upgrade **cpp build tools** first.

Hope this will help somebody in the future.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
