### ISSUE TITLE
Dash package generator should use R function names within online help

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#1096]
Currently, whenever online help is generated for R packages, any references of the form `'dashLibrary.functionName'` will be preserved, even though we strictly use camel case with no separator for Dash function names.

We should consider removing the `.` when the string is enclosed within single quotation marks for more coherent documentation within component libraries whose documentation is generated from JavaScript docstrings.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
