### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement dpd-static-components (from jupyter_plotly_dash) (from versions: none)

### ISSUE THREAD

**Issue by tanzin29** [plotly/dash#1108]
I am trying to install jupyter plotly dash but getting this error.

**Comment by tonydeck0506** [comment]
I found the same issues when installing. It will halt the installation of jupyter_plotly_dash

**Comment by xiaowohmbb** [comment]
pip install jupyter_plotly_dash==0.4.0 执行成功

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
