### ISSUE TITLE
[Feature Request] WebSocket support

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash#1110]
We have an exciting prototype for push (WebSocket) support and are looking for a partner to help us take it to the finish line:
![push-demo-screencast](https://user-images.githubusercontent.com/1865834/73766377-ed6dd300-4743-11ea-9d01-c0b504f2f8f5.gif)
Please reach out if your company is interested in a realtime streaming capability for Dash:
https://plot.ly/products/consulting-and-oem/

**Comment by tcbegley** [comment]
Exciting! Is the prototype available anywhere to play around with?

**Comment by Jerry-Ma** [comment]
@jackparmer  Any chance that you will share the prototype source code? This totally brings dash to a different level, and I've love to try it.

**Comment by byt3bl33d3r** [comment]
@jackparmer Can you make the prototype available so we can help? This is desperately needed for most modern applications

**Comment by sheldonrong** [comment]
@jackparmer any updates on this one?

**Comment by jackparmer** [comment]
Official WebSocket support is currently only available with Dash Enterprise, as one of the "low-code" features: plotly.com/dash

**Comment by matthijsramlab** [comment]
https://pypi.org/project/dash-devices/ Have al look at this, it uses web sockets

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
