### ISSUE TITLE
[BUG]Clicking on a new tab before the current tab is finished loading causes the app to crash

### ISSUE THREAD

**Issue by davidghill** [plotly/dash#1115]
Clicking on a tab then clicking on a new tab (ex. accidentally clicking on the wrong tab followed by clicking on the desired tab) crashes the app.

**Describe your context**
```
dash                               1.9.0
dash-core-components               1.8.0
dash-daq                           0.1.0
dash-html-components               1.0.2
dash-renderer                      1.2.4
dash-table                         4.6.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows 10
    - Browser Chrome
    - Version 79.0.3945.130 (Official Build) (64-bit)

**Describe the bug**

I have a tabbed app that has some buttons with lengthy run times.  If you click on a tab, then immediately click on another tab, the app crashes and the page hangs.  You have to relaunch the python app and refresh the page to get back.

**Expected behavior**

Run the running process in the background and move to the new tab or warn that moving to the next tab will cancel the current process.

**Screenshots**
![snip1](https://user-images.githubusercontent.com/45153878/74062095-80fd0900-49bb-11ea-9456-ef190412bfa1.png)
![snip2](https://user-images.githubusercontent.com/45153878/74062129-92deac00-49bb-11ea-9456-994ddf3c94ff.png)
![snip3](https://user-images.githubusercontent.com/45153878/74062449-52336280-49bc-11ea-92c4-838ea1d5938c.png)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
