### ISSUE TITLE
app.title attribute is not validated in Dash for Python, but is checked in Dash for R

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#1118]
In Dash for R v0.3.0, we will allow setting an app's title via the index template, `interpolate_index`, and also via `app$title()`, which mimics the functionality already extant when using `app.title` in Python.

However, on the R side, we validate the input to `app$title()` and ensure that it is a valid character string, while on the Python side we don't currently appear to perform any sanity checks. We should implement this for parity between Dash implementations.

@alexcjohnson

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
