### ISSUE TITLE
[BUG] Selected Points should reset if plot is redrawn while having an active selection

### ISSUE THREAD

**Issue by NotInControl** [plotly/dash#1121]
**Describe your context**
Currently when using a selectedData callback, if the plot has a active selection, but then has the the figure info updated (such that the plot get regenerated), the selected Data still returns the last selection of points, but the new figure does not indicate any selection.

-  replace the result of `pip list | grep dash` below
```
dash==1.8.0
dash-bootstrap-components==0.8.2
dash-core-components==1.7.0
dash-html-components==1.0.2
dash-renderer==1.2.3
dash-table==4.6.0
dask==2.10.1
Flask==1.1.1
Flask-Compress==1.4.0
```

**Describe the bug**

When a plot is rerendered, any data tied to the previous plot like selected points should be cleared. But instead the current behavior just resends the last list of points, even if those points don't exist on the new plot. This was experienced with Bar plots only, have not tested other plots. 

**Expected behavior**

Expecting SelectedData callback to return none if a previous selection was made, and then an update to the figure occured. 

**Screenshots**

If applicable, add screenshots or screen recording to help explain your problem.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
