### ISSUE TITLE
Dashed horizontal Lines in top of a bubble chart

### ISSUE THREAD

**Issue by rcontesti** [plotly/dash#1129]
I'm trying to create to red dashed lines, one horizontal and one vertical in top of a bbuble chart done with dash.

I'm following an example provided:
`
#Bubble Chart Data Dictionary
data_=[dict(
    x=df[df[colour_varible] == i][x_variable],
    y=df[df[colour_varible] == i][y_variable],
    text=df[df[colour_varible] == i][label_variable],
    mode='markers',
    opacity=0.7,
    marker={
    'size': 200*df[df[colour_varible] == i][size_variable]/max(df[size_variable]),
    'line': {'width': 0.5, 'color': 'white'}
    },
    name=i
    ) for i in df[colour_varible].unique()
]

layout_=dict(
                xaxis={'title': x_axis_title},
                yaxis={'title': y_axis_title},
                margin={'l': 40, 'b': 40, 't': 10, 'r': 10},
                legend={'x': 1, 'y': 1, 'itemsizing': 'constant'},
                hovermode='closest'
)

graph_=dcc.Graph(
        id=id_,
        figure={
            'data': data_,
            'layout': layout_            
        }
    )

app.layout = html.Div([
    graph_
])

if __name__ == '__main__':
    app.run_server(debug=True)

`

But I don't really know how to add two dashed line that go from axis origin at 100% both for x and y and form a square.

Many thanks!

**Comment by alexcjohnson** [comment]
This kind of question is better suited to the forum https://community.plot.ly/, but have you tried doing this with shapes? https://plot.ly/python/shapes/

**Comment by rcontesti** [comment]
@alexcjohnson many thanks for your answer. I have tried but I could't do it. I know how to do the plots individually or do them together in plotly but I can't work this out in dash.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
