### ISSUE TITLE
Setting Chart Themes

### ISSUE THREAD

**Issue by Tim113** [plotly/dash#1131]
This is related to https://github.com/plotly/angular-plotly.js/issues/99, but for dash.  I would like to be able to use the plotly_dark template in a dash app.

From my understanding of the API the following code should be giving me a graph with the tempalte applied but it is not:

```python
# -*- coding: utf-8 -*-
import dash
import dash_core_components as dcc
import dash_html_components as html

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div(
    children=[
        html.H1(children='Hello Dash'),
        html.Div(children='''
        Dash: A web application framework for Python.
    '''),
        dcc.Graph(
            id='example-graph',
            figure={
                'data':
                    [
                        {
                            'x': [1, 2, 3],
                            'y': [4, 1, 2],
                            'type': 'bar',
                            'name': 'SF'
                        },
                        {
                            'x': [1, 2, 3],
                            'y': [2, 4, 5],
                            'type': 'bar',
                            'name': u'Montréal'
                        },
                    ],
                'layout': {
                    'title': 'Dash Data Visualization',
                    'template': 'plotly_dark'
                }
            }
        )
    ]
)

if __name__ == '__main__':
    app.run_server(port=8555)
``` 

I did find https://community.plot.ly/t/plotly-dark-template-seems-to-stopped-working-on-dash/25935 this issue on the community forum that implied that it used to work on another verison of dash however I could not find one that woul work (I tried with dash 0.38.0 and 0.43.0)

**Comment by nicolaskruchten** [comment]
Hi!

The `plotly_dark` theme is part of the `plotly` package and so you can only refer to it by name if you're using a `go.Figure` object (either directly or as the output of a Plotly Express function) rather than raw `dict`s to specify your figure, as you're doing above. See https://plot.ly/python/creating-and-updating-figures/ for the relationship between these two approaches.

In order to get this to work for you, you can either wrap your `dict` in a `go.Figure()` call or you can extract the contents of the `plotly_dark` template from `plotly.io.templates` and inline it directly into your `dict`.

Hope this helps!

**Comment by gentrexha** [comment]
I can't for the life of me figure how this would exactly look like? Would you mind explaining this with an example?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
