### ISSUE TITLE
Documentation: Dash tutorial suggests installing an older version of dash

### ISSUE THREAD

**Issue by firasm** [plotly/dash#1149]
In the [dash tutorial](https://dash.plot.ly/installation), this is the recommendation on how to install dash:

> In your terminal, install several dash libraries. These libraries are under active development, so install and upgrade frequently. Python 2 and 3 are supported.
> `pip install dash==1.8.0`

The current dash version is 1.9.1

Is this intentional ? I'd send a PR, but I assume the documentation is auto generated.

**Comment by ned2** [comment]
Is there a reason it's not just?

`pip install dash`

I've always wondered why the explicit version is specified here.

**Comment by 11aditya11** [comment]
"pip install dash" this installs latest version
You can check version using

import dash_core_components
print(dash_core_components.__version__)
 Yes you are correct, this  doc is autogenerated

**Comment by chriddyp** [comment]
We provide an explicit version so that folks are:
1. Better aware that versions exist and that they can check their own version
2. Aware from the start of which version the documentation is using and that they may need to upgrade if they are on an old version.

This has since been updated, there is sometimes a delay between publishing the packages and upgrading the docs.

**Comment by firasm** [comment]
Yes thanks, as noted above we know how to get the latest version. However novices (those reading the tutorial, may not.

 I’d suggest updating the docs to always just use pip install dash rather than a specific version. Otherwise when folks copy paste code from the tutorial, they’ll end up with older versions of dash. 

Sorry for not being clear in the original issue.

**Comment by firasm** [comment]
Ah okay. So the delay isn’t normal. Gotcha.
