### ISSUE TITLE
Hot reload stops working randmoly

### ISSUE THREAD

**Issue by Jogala** [plotly/dash#1159]
The hot reload stops working randomly. Some times it senses a change only once, sometimes three or four times before it stops. I can see when it is sensing a change, when saving my document, because in the terminal it reprints the row

```
__name__:  __main__
Running on http://127.0.0.1:8050/
Debugger PIN: 387-359-895
```
I am changing the text of 

`html.H1(children='lalall '),
`
for triggering a change.

I tried many different options:

```
if __name__ == '__main__':
    app.run_server(debug=True)

if __name__ == '__main__':
    app.run_server(debug=True,use_reloader=True)

if __name__ == '__main__':
    app.run_server(debug=True,use_reloader=True,dev_tools_hot_reload_max_retry=3000)
        
```

conda list:
```
dash                      1.9.1                      py_0    conda-forge
dash-core-components      1.8.1                      py_0    conda-forge
dash-html-components      1.0.2                      py_0    conda-forge
dash-renderer             1.2.4                      py_0    conda-forge
dash-table                4.6.1                      py_0    conda-forge
```

I am using Fedora 29. The bug does not depend on the browser, as I can see the change detected in the bash.

**Comment by michaelbabyn** [comment]
@Jogala , if you're still having this issue, I wonder if it might be related to the version of Flask and Werkzeug you have installed in your environment.

Does the issue still occur if you install dash into a fresh conda environment?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
