### ISSUE TITLE
scroll bar and plotly mode bar in plot

### ISSUE THREAD

**Issue by creator-new** [plotly/dash#1165]
I added the scroll bars, but in doing so, i had to scroll to get plotly modebar, how to make plotly modebar visible all time

<img width="663" alt="Screen Shot 2020-03-26 at 10 50 12 PM" src="https://user-images.githubusercontent.com/16370000/77719927-7bcc3b80-6fb4-11ea-8329-bba26e0c00d4.png">
<img width="712" alt="Screen Shot 2020-03-26 at 10 50 27 PM" src="https://user-images.githubusercontent.com/16370000/77719923-7a9b0e80-6fb4-11ea-80c0-a154b9931d57.png">

```
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.figure_factory as ff
import plotly.graph_objects as go


app = dash.Dash()

fig = ff.create_annotated_heatmap(
    z = [np.arange(0,50), np.arange(0,50), np.arange(0,50)]
)

fig['layout'].update(
    title='test',
    width=1200,
    height=300
)


config={'toImageButtonOptions':{'format':'svg'}}
#fig2 =fig.show(config=config)

app.layout = html.Div(children=[
    dcc.Graph(id='heatmap',
        figure=fig,
        config=config
               
    )
], style={'overflowX':'scroll','width':700, 'height':300}
    
)

#fig.show(config=config)
if __name__ == '__main__':
    app.run_server(debug=True, use_reloader=False)
```

**Comment by nickmelnikov82** [comment]
You can use `rangeslider`.

Example code:
```
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.figure_factory as ff
import numpy as np

app = dash.Dash()

fig = ff.create_annotated_heatmap(
    z = [np.arange(0,50), np.arange(0,50), np.arange(0,50)]
)

fig['layout'].update(
    title='test',
    width=1200,
    height=300,
)

fig.update_layout(xaxis=dict(rangeslider=dict(visible=True),
                             type="linear")
)

config={'toImageButtonOptions':{'format':'svg'},"displayModeBar":True}

app.layout = html.Div(children=[
    dcc.Graph(id='heatmap',
        figure=fig,
        config=config,
    )
], 
)

if __name__ == '__main__':
    app.run_server(debug=True, use_reloader=False)
```

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/53801797/154037570-90e5eeca-8fe0-4995-af98-006c02a12440.png">

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
