### ISSUE TITLE
Ability to access the wrapped function for testing or to import into other programs

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#1195]
i.e.
```
@app.callback(...)
def update_graph(value):
    ...
```

it would be helpful to be able to access or call `update_graph` _unwrapped_. Currently, if you call `update_graph`, you'll call the _wrapped_ version.

Three use cases:
1. Ability to unit test `update_graph`
2. Ability to call `update_graph` in e.g. Jupyter
3. Ability to call `update_graph` in other programs

I believe this violates how decorators work, so we might have to expose some method on the function like `.inner` so the caller would call e.g. `update_graph.inner(value)`

**Comment by alexcjohnson** [comment]
Actually we don't do anything with the return value of the decorator right now - internal to the decorator we add the wrapped function to the callback map:

https://github.com/plotly/dash/blob/3ec55b5a97fdd34ed8384085df884d86730b1a9c/dash/dash.py#L941

But then we return the wrapped function:

https://github.com/plotly/dash/blob/3ec55b5a97fdd34ed8384085df884d86730b1a9c/dash/dash.py#L943

I suspect if instead we just `return func` everyone will be happy 🤞 (aside from any of our own tests that use the wrapped function - those will have to reference `app.callback_map` instead)

**Comment by alexcjohnson** [comment]
Closed in #1839

**Comment by shea-parkes** [comment]
Just dropping a note a couple years later for others that might land here:

We were actually expecting that we'd have to do `myfunc.__wrapped__` in our unit tests type work.  But since the current `dash.callback` code returns the original func (instead of the wrapped version it created), you can just work directly with the function as-if it wasn't decorated with `dash.callback()`.

We basically overthought things.
