### ISSUE TITLE
Jupyter Dash does not render Plotly Treemap with multiple 'path'

### ISSUE THREAD

**Issue by ra00015ojp** [plotly/dash#1204]
When senting to Jupyter Dash, no Treemap is visualised:

html.H3(children='Heatmap Complete', style={'textAlign': 'left',}),
    
    dcc.Graph(
        id='ID30',
        figure = px.treemap(heat_data, path=['COUNTRY', 'TAG'],values='TOTAL',
                            color='TOTAL', color_continuous_scale='jet',
                            color_continuous_midpoint=36)

while with this code I obtain the Treemap the basic visualisation:

html.H3(children='Heatmap Complete', style={'textAlign': 'left',}),
    
    dcc.Graph(
        id='ID30',
        figure = px.treemap(heat_data, path=['COUNTRY'],values='TOTAL',
                            color='TOTAL', color_continuous_scale='jet',
                            color_continuous_midpoint=36)

**Comment by steven95421** [comment]
I faced the same issue as yours. I just found a workaround, just wrapped it within another dcc.div() and everything should work fine.

**Comment by ra00015ojp** [comment]
Thanks

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
