### ISSUE TITLE
Docstring generator is wrong for certain properties including `sort_by`

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash#1205]
![image](https://user-images.githubusercontent.com/203523/79871002-c3769500-83b1-11ea-93df-124ca962cd90.png)

**Comment by chriddyp** [comment]
While we're in the neighborhood, I'm sure there are many more fixes that we can make for markdown readability. Here are a few blocks that are pretty tough to digest:

Missing some newlines in here? Especially to split up `group` and `grouping`
![image](https://user-images.githubusercontent.com/1280389/80178785-ee303b80-85b3-11ea-8a3b-6bbdb469334b.png)

JS comment included in the default text
![image](https://user-images.githubusercontent.com/1280389/80178826-04d69280-85b4-11ea-8e47-45694bf5227f.png)

Nested dictionaries's lists aren't indendented
![image](https://user-images.githubusercontent.com/1280389/80178844-0f912780-85b4-11ea-984b-fb239ce38855.png)

Could use some more newlines + same nested dictionary issue
![image](https://user-images.githubusercontent.com/1280389/80178891-2768ab80-85b4-11ea-8146-901297f974a3.png)

`null` should be `None`
![image](https://user-images.githubusercontent.com/1280389/80178916-318aaa00-85b4-11ea-8590-2504602a4a54.png)

**Comment by chriddyp** [comment]
Another related issue: https://github.com/plotly/dash-docs/issues/836

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
