### ISSUE TITLE
`UNDEFINED` value isn't allowed for `id`

### ISSUE THREAD

**Issue by kuraga** [plotly/dash#1207]
With Dash 1.11.0, `id` attribute's value [should be `str` or `dict`](https://github.com/plotly/dash/blob/v1.11.0/dash/development/base_component.py#L124-L140). Although it isn't required. Why `dash.development.base_component.Component.UNDEFINED` isn't allowed?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
