### ISSUE TITLE
Adding sanic support in dash

### ISSUE THREAD

**Issue by nmiculinic** [plotly/dash#122]
> Sanic is a Flask-like Python 3.5+ web server that's written to go fast. It's based on the work done by the amazing folks at magicstack, and was inspired by this article.

https://github.com/channelcat/sanic

It's flask-like framework, meaning code changes would be minimal, yet benefits enormous. It supports async handler that I'd love to use:
* It shall allow me fetching data asynchronously without blocking the request. 
* I can async process some data in thread/process pool and return when it's completed without blocking event loop/whole server
* Since it's flask-like it's easy to switch and use.

Contrary in flask and WSGI I cannot easily have async data fetching/processing.

**Comment by ned2** [comment]
Gunicorn supports Flask very well and has async worker threads. If your Dash app was in an 'app' attribute' within a 'main.py' file, you could try this:

    pip install gunicorn gevent
    gunicorn --worker-class gevent --workers 1 --threads 4 --bind 0.0.0.0:5000 main:app.server

Although I believe you want to be running Gunicorn behind a buffering reverse proxy such as Nginx in order to truly take advance of the threading. See Gunicorn docs for more details: http://docs.gunicorn.org/en/stable/design.html

**Comment by chriddyp** [comment]
@nmiculinic - does @ned2 's suggestion of using `gunicorn` work for you? 

I won't be adding sanic to this implementation of Dash as Flask and Flask+Gunicorn is more widely used and proven.

If `sanic` is 1-1 compatibile with Flask, then it should be possible to pass in your own server instance with:
```
server = Sanic()

app = dash.Dash(__name__, server=server)
```

However, it seems like the `gunicorn`+`flask` solution should work well for now. If it doesn't, I would love to learn more :)
