### ISSUE TITLE
[BUG] from .dash import Dash, no_update # noqa: F401 & 

### ISSUE THREAD

**Issue by ahdukku** [plotly/dash#1221]
Describe your context
I am trying to deploy a dash app to cloudfoundary, and after all the dependencies have been installed. The app keep crashing due to the following errors:

[ERR] Traceback (most recent call last):
[ERR] import dash
[ERR] File "/home/vcap/deps/0/python/lib/python3.6/site-packages/dash/__init__.py", line 1, in <module>
[ERR] from .dash import Dash, no_update # noqa: F401
[ERR] File "/home/vcap/deps/0/python/lib/python3.6/site-packages/dash/dash.py", line 23, in <module>
[ERR] import plotly
[ERR] File "/home/vcap/deps/0/python/lib/python3.6/site-packages/plotly/__init__.py", line 30, in <module>
[ERR] from plotly import (
[ERR] File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[ERR] File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[ERR] File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[ERR] File "<frozen importlib._bootstrap_external>", line 674, in exec_module
[ERR] File "<frozen importlib._bootstrap_external>", line 780, in get_code
[ERR] File "<frozen importlib._bootstrap_external>", line 833, in get_data
[ERR] OSError: [Errno 14] Bad addres

**pip list**
gunicorn
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
Click==7.0
cryptography==2.9
dash==1.9.1
dash-core-components==1.8.1
dash-html-components==1.0.2
dash-renderer==1.2.4
dash-table==4.6.1
defusedxml==0.6.0
Flask==1.1.1
Flask-Compress==1.4.0
future==0.18.2
idna==2.9
itsdangerous==1.1.0
Jinja2==2.11.1
jira==2.0.0
MarkupSafe==1.1.1
numpy==1.18.1
oauthlib==3.1.0
pandas==1.0.1
pbr==5.4.5
plotly==4.5.2
pycparser==2.20
PyJWT==1.7.1
python-dateutil==2.8.1
pytz==2019.3
requests==2.23.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
retrying==1.3.3
six==1.14.0
urllib3==1.25.8
Werkzeug==1.0.0

**Describe the bug**

I have run this app on my local machine but these bugs do not appear except when I went to deploy.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
