### ISSUE TITLE
[BUG] dash.testing doesn't work with older versions of dash

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash#1230]
In Dash v1.11 - specifically #1103 - we changed the structure of the redux store used by `dash-renderer`. This wasn't a breaking change as far as most users are concerned, but `dash.testing` contains some deeper hooks into this store, and it would be nice to keep these working against older versions of dash, so that you can test an already-deployed app and not worry about the version you're using to test it.

The specific bit that came up in our own work is `redux_state_rqs` but there may be more. For that one though, we should support both the before and after versions of commit https://github.com/plotly/dash/commit/58eaa965521d68b1c969e6e4b4b8b7341a645a05

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
