### ISSUE TITLE
While uploading file through dash upload component, the page stays on with "Updating..." state and does not view the result

### ISSUE THREAD

**Issue by shanupriya8** [plotly/dash#1235]
I wrote a python dash program to upload an excel file and my callback function would read data from the file and insert it into postgresql DB and return the status of data refreshment in DB, which was working fine initially but while hosting the Dashboard created to IIS site the callbacks weren't working, so when I went back to run the program manually as usual the already working callbacks weren't working , when I uploaded an excel file the page when to "Updating..." state and never returned result. 
I honestly can't understand where no change was made to code before and after the callback stopped working what would be the reason.
I also tried updating dash package version but still not working. Kindly somebody help on this since this is been driving me crazy the whole day and wasted.

Note: Can't post the code since its against my organization policy. I am pretty sure the code is working fine because for the first several runs it was working but the next day it didnt and again it was working a couple of times and now it totally stopped working and stays with "Updating..." state.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
