### ISSUE TITLE
Use persist_to_workspace to DRY up CircleCI config for repo clones

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#1264]
The proposed CircleCI config which implements the R build test in #1238 repeats several repo clone steps performed in previous jobs. We could consider using `persist_to_workspace` to recycle these resources, and avoid having to request them again.

We already use the workspace feature, but currently we store package tarballs rather than the entire repositories.

More information is available here:

https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-artifacts-among-jobs

**Comment by alexcjohnson** [comment]
Can we consider this solved by #1280? cc @Marc-Andre-Rivet

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
