### ISSUE TITLE
[Feature Request] Support the use of Enums IDs for HTML components

### ISSUE THREAD

**Issue by mfreeborn** [plotly/dash#1272]
**Is your feature request related to a problem? Please describe.**
When I start to create more complicated, intertwined layouts, I like to use enumerations to store the id's etc of the dashboard components

**Describe the solution you'd like**
I'd like this to be valid:

```
# main.py
from enum import Enum

import dash
import dash_html_components as html

class Element(Enum):
    """Enumerations for HTML elements."""
    
    PAGE_CONTENT = "page-content"

app = dash.Dash(__name__)

layout = html.Div([html.P("Hi there!")], id=Element.PAGE_CONTENT)

app.layout = layout

app.run_server()
```

**Describe alternatives you've considered**
There is a simple workaround: using the `value` proprty of the enumeration to return the underlying string. The above example works if you modify the layout to:

`layout = html.Div([html.P("Hi there!")], id=Element.PAGE_CONTENT.value)`

**Proposal**
What are people's opinion on the idea of allowing _either_ `str`_or_ `Enum` instances as valid values to the `id` keyword argument for html elements?

**Comment by jeffzi** [comment]
I faced the same issue. The solution is to subclass both `Enum` and `str`:

```python
# main.py
from enum import Enum

from dash import Dash
import dash_html_components as html


class Element(str, Enum):
    """Enumerations for HTML elements."""

    PAGE_CONTENT = "page-content"


app = Dash(__name__)

layout = html.Div([html.P("Hi there!")], id=Element.PAGE_CONTENT)

app.layout = layout

app.run_server()

```

**Comment by mfreeborn** [comment]
I like it! I should've read further down the Python enumeration docs page. I could go one step further:

```python
from enum import Enum, auto


class BaseElement(str, Enum):
    def _generate_next_value_(name, start, count, last_values):
        return "-".join(name.lower().split("_"))


class Element(BaseElement):
    PAGE_CONTENT = auto()  # resolves to "page-content"
    SUBMIT_FORM_BUTTON = auto()  # resolves to "submit-form-button"
```

As a bonus, enum members must be unique, so the `@unique` decorator is no longer necessary.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
