### ISSUE TITLE
[Feature Request] Splice lose focus from debounce=

### ISSUE THREAD

**Issue by ghost** [plotly/dash#1294]
i read https://dash.plotly.com/dash-core-components/input
can you please remove the callback triggered if the input looses focus. **Often** the user goes to other field etc to come back to the input. It should NOT fire on loose focus if `debounce=True`. Can you please make a separate kwarg for it or else ?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
