### ISSUE TITLE
[Feature Request] dcc.Store causes Not secure warning in browser

### ISSUE THREAD

**Issue by max454545** [plotly/dash#1298]
Hello All,

We have recently purchased an SSL certificate for our new website, but I notice that we still have the warning "Not secure".  This is in the latest chrome browser.

![not secure pic](https://user-images.githubusercontent.com/66354962/84404334-f9dccd80-ac06-11ea-9936-4e667c0d4127.png)

On closer inspection, it is because of the cookies created by dcc.Store

![not secure 2](https://user-images.githubusercontent.com/66354962/84404652-68ba2680-ac07-11ea-9cc6-bf4dc93d5b96.png)

Is there a work around, or would it be possible to fix this?

**Comment by alexcjohnson** [comment]
`dcc.Store` doesn't use cookies, it uses `localStorage`, `sessionStorage`, or just memory depending on settings. But anyway just the presence of cookies (or local/session storage) doesn't make a site / connection insecure. I'm not sure what's going on but the cookies seem like a red herring to me.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
