### ISSUE TITLE
CSS is not working when running script using Pycharm

### ISSUE THREAD

**Issue by ninjakx** [plotly/dash#1308]
I am using PyCharm to debug the code. But when I open via PyCharm, The CSS file doesn't seem to work.

**Using Pycharm:**
![Screenshot from 2020-06-24 14-18-50](https://user-images.githubusercontent.com/29797787/85524511-ddd52500-b625-11ea-8ab9-90456b7000fb.png)

**Using Terminal:**
![Screenshot from 2020-06-24 14-19-54](https://user-images.githubusercontent.com/29797787/85524499-da419e00-b625-11ea-846e-398294acbe02.png)

According to [this](https://dash.plotly.com/external-resources), I need to have my css and js files inside assets folder. It will automatically serve all the files. I have that folder inside the pycharm also.

![Screenshot from 2020-06-24 14-22-22](https://user-images.githubusercontent.com/29797787/85524830-255bb100-b626-11ea-9a9b-f390a5d5a61c.png)

Am I missing something?

**Comment by willdone1337** [comment]
I guess Pycharm Community edition is not support css

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
