### ISSUE TITLE
Scattergl vs scatter [BUG]

### ISSUE THREAD

**Issue by tawabshakeel** [plotly/dash#1309]
For better speed and to present more data I am converting code from scatter to scattergl but I am facing issue in the color scheme
```
px.scatter(df2, x="xaxis", y="yaxis", color="color", hover_data=["hover"])

````
# changed to 
```
summary_plot = go.Figure()
summary_plot.add_trace(go.Scattergl(x=df2['xaxis'], y=df2['yaxis'],mode='markers',hovertext=df2['hover'],
                                     marker=dict(color=list(df2['color']),showscale=True,autocolorscale=False,cauto=False)))
```
chart created from `scatter`
![scatter](https://user-images.githubusercontent.com/24355495/85620694-937f9280-b67d-11ea-839b-12da9b211b8e.PNG)

chart created from `px.scattergl`
![scattergl](https://user-images.githubusercontent.com/24355495/85620632-7c40a500-b67d-11ea-9c46-ef826704540a.PNG)

I want to have a scatter color scheme in a scatter function.
Am I missing any parameter in scattergl?
Please guide me

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
