### ISSUE TITLE
How to get the hoverdata on plotlypbpx. scatter_mapbox 

### ISSUE THREAD

**Issue by pavi-ninjaac** [plotly/dash#1314]
I want to use the hoverdata on map to use further tasks. But I can't get the hoverdata from px.scatter_matbox() , how to get that

**Comment by julienbeisel** [comment]
You can set the `hoverinfo` attribute to display hoverdata.

For more details, you can check the API documentation here : https://plotly.com/python-api-reference/generated/plotly.graph_objects.Scattermapbox.html

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
