### ISSUE TITLE
datepickerrange is not changing to most current dates

### ISSUE THREAD

**Issue by acharjeeanirban** [plotly/dash#1316]
Hi,

We have a use case where we need to show data based on "start date" and "end date" on a daily basis. We are observing that the start date and end date are not changing as days pass but remaining the same (date) when the process (code) was started. When we restart the process it defaults to the current date again.

                    dcc.DatePickerRange(
                        id='my-date-picker-range',
                        calendar_orientation='vertical',
                        start_date=datetime.now().date() - timedelta(days=1),
                        end_date=datetime.now().date(),
                    ),

Can you please look into it.

**Comment by alexcjohnson** [comment]
If the snippet above is part of a constant `app.layout` then that's correct, it'll only change when you restart the server, because a constant `app.layout` is only evaluated when the server starts.

You can make `app.layout` a function - in which case it's re-evaluated every time a user requests the page. Your other option is to make `start_date` and `end_date` the output of a callback, whose input is a `dcc.Interval` (Set to perhaps 1 hour?) and then the dates will update even without the user reloading the page.

**Comment by KnopKirrie** [comment]
Have a look here: https://dash.plotly.com/live-updates -> shows an example for what @alexcjohnson mentions.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
