### ISSUE TITLE
How to run dash app in company server.

### ISSUE THREAD

**Issue by kvo-stp** [plotly/dash#1331]
I'm sorry if my question is not clear since I have zero knowledge about web hosting. 

I'm writing a dash app in Jupyter in a company server, since we are not allow to open a new port due to security purpose. I wonder if there is a way to display my app directly in Jupyter without a port.

**Comment by alexcjohnson** [comment]
I kind of doubt we'll be able to do anything without a separate port, but perhaps if you ask this question at https://community.plotly.com/ someone will have ideas that can help. Maybe Jupyter could be convinced to somehow proxy the Dash requests for you? Anyway, I'm going to close the issue here, as this use case is unlikely to require any new development in Dash itself, it's more about whether there's a way to use Jupyter and Dash together to get the desired behavior.
