### ISSUE TITLE
[BUG] px.line failed to display curves on browsers running on iOS

### ISSUE THREAD

**Issue by Chao-Jen** [plotly/dash#1345]
Below is my dash code and requirements.txt:
[application.py.txt](https://github.com/plotly/dash/files/4975540/application.py.txt)
[requirements.txt](https://github.com/plotly/dash/files/4975541/requirements.txt)

I test the code using Python 3.6.10 on Ubuntu 18.04.

- the result of `pip list | grep dash` 
```
dash                 1.13.4
dash-core-components 1.10.1
dash-html-components 1.0.3
dash-renderer        1.5.1
dash-table           4.8.1
```
-  frontend: Browser, Version and OS

    - OS: [iOS on iPhone 8]
    - Browser [Chrome and Safari]
    - Version [iOS 13.6]

**Describe the bug**

As shown in the attached screenshot taken from my iPhone 8, the attached dash code displays either no curves or fewer curves in the charts. This issue happens in both Chrome and Safari on iPhone. 

![IMG_0956](https://user-images.githubusercontent.com/5210856/88457499-b50cad80-ceb9-11ea-80bb-86876777d7eb.jpg)

**Expected behavior**
The same code can display properly all the curves in Chrome running on Desktop PC, as shown in the below screenshot.

![screenshot_of_correctly_displaying_curves](https://user-images.githubusercontent.com/5210856/88457510-cf468b80-ceb9-11ea-9729-ed37dfc58765.PNG)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
