### ISSUE TITLE
Remove timestamps within URLs generated by dash-renderer when soft reloading CSS

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#1359]
All references to `?m=` have been expunged from Dash for R within https://github.com/plotly/dashR/issues/201, yet this warning appears on soft reloading CSS:

![image](https://user-images.githubusercontent.com/9809798/82851968-7c5b5280-9ecf-11ea-98b9-3f988b77f13a.png)

I believe the cause is L35745 within `dash_renderer.dev.js`, which appends a CSS modification timestamp to the request coming in to the backend from the renderer:

```javascript
if (a.modified > 0) {
  var link = document.createElement('link');
  link.href = "".concat(a.url, "?m=").concat(a.modified);
  link.type = 'text/css';
  link.rel = 'stylesheet';

  this._head.appendChild(link); // Else the file was deleted.
}
```

Assuming it's reasonable, I suggest modifying `dash-renderer` so that these requests are no longer made when soft reloading stylesheets.

@Marc-Andre-Rivet @alexcjohnson

**Comment by Marc-Andre-Rivet** [comment]
Combined with https://github.com/plotly/dash/issues/1363 I would expect the renderer to not have to deal with modified timestamp and such. Instead, the reload service should return the fingerprinted css resources and a base resource name. The template could inject a `data-dash-attr` on link with the resource base name, the renderer would do the same. On reload the renderer can search for that instead of the url and disable the link. The new link is then created from the received fingerprinted url w/o modifications.

**Comment by chriddyp** [comment]
What's the downside for keeping these in? Seems harmless?

**Comment by rpkyle** [comment]
> @rpkyle What's the downside for keeping the timestamps within the URLs? Seems harmless?

My understanding (and @Marc-Andre-Rivet may correct me) is that this is an anti-pattern, and we've already implemented improved functionality in Dash via asset fingerprinting. As a result, the code referenced above is basically redundant at this point. 

We _could_ just keep it, but I think we've already elected to replace this approach with fingerprinting, so we should probably remove it.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
