### ISSUE TITLE
[BUG] Non-CSS assets are not hot-reloaded (or updated <= 12 hours) correctly

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash#1363]
Encountered while looking at https://github.com/plotly/dash/issues/1359 and https://github.com/plotly/dashR/issues/201.

`index.py`
```
import dash
import dash_html_components as html

app = dash.Dash(__name__)
server = app.server

app.layout = html.Div(id="transition-div")

if __name__ == '__main__':
    app.run_server(debug=True)
```

`/assets/custom.css`
```
#transition-div {
    height: 600px;
    padding: 10px;
    background: url('/assets/base.jpg')
}
```

Using `red.jpg` and `blue.jpg` as files copied to `base.jpg`
![blue](https://user-images.githubusercontent.com/8092993/90065532-6da85e80-dcba-11ea-9e57-c2cea4c13024.jpeg)
![red](https://user-images.githubusercontent.com/8092993/90065533-6da85e80-dcba-11ea-8f75-4c39203608dc.jpg)

Loading the app with `debug=True` and switching the base.jpg file (e.g. `cp blue.jpg base.jpg`) hot reloads but reuses the previous (red) image instead of the new one.

This is caused by the assets folder blueprint at https://github.com/plotly/dash/blob/dev/dash/dash.py#L403 assigning both a cache duration of 12 hours and an eTag. Because unlike css files these files are not loaded with a cache buster (`?m=...`, https://github.com/plotly/dash/blob/dev/dash/dash.py#L611) the cache policy is applied and the old file loaded (cache-control >> eTag)

This is also observable with `debug=False` across app reloads and standard page reload.

Expected behavior would be for the images to be correctly updated when modified - on a standard page reload and on hot reloading.

This can be achieved by using the same approach as for the component suites resources (https://github.com/plotly/dash/blob/dev/dash/dash.py#L701), (1) using cache control if-and-only-if a fingerprint is present (also, use the new fingerprint instead of the cache buster anti-pattern), (2) reverting to eTag if no fingerprint is found (e.g. images loaded from css)

The fixed behavior of non-css assets should be tested with a new test as part of this issue.

@rpkyle

**Comment by drewyang-datavedik** [comment]
I'm having the same issue here. I have to clear browser data every time I make some changes in CSS, but the JS code is reloading fine because it's loading dynamically.

```
class CustomDash(dash.Dash):
    def interpolate_index(self, **kwargs):
        # Inspect the arguments by printing them
        return '''
        <!DOCTYPE html>
        <html>
            <head>
                <title>SmartWellReport</title>
                <link rel="icon" type="image/x-icon" href="/assets/img/favicon.ico">
                <link rel="stylesheet" href="/assets/css/common.css">       <!--This is the css file-->
            </head>
            <body>
                {app_entry}
                {config}
                {scripts}
                {renderer}
            </body>
        </html>
        '''.format(
            app_entry=kwargs['app_entry'],
            config=kwargs['config'],
            scripts=kwargs['scripts'], // JS is dynamically loaded, so it's fine
            renderer=kwargs['renderer'])
```

This might help: I was writing a Flask backend before . There is a `SEND_FILE_MAX_AGE_DEFAULT=timedelta(seconds=1)` config which you can set the static file expiring time. I know dash uses Flask, so I tried this on dash app config. However, it drops all the css files and won't return it back after refreshing.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
