### ISSUE TITLE
[Feature Request] - Mapbox viewport coordinates in relayoutData

### ISSUE THREAD

**Issue by jcfbeardsley** [plotly/dash#1369]
Hi,

Is it possible to have the viewport coordinates (lower left, lower right, upper left and upper right lat/lons) returned as part of the relayoutData when using Mapbox? Currently only mapbox.center, mapbox.zoom, mapbox.bearing and mapbox.pitch are returned. The viewport coordinates would be a massive help when generating dynamic layer content based on user interactions.

I note this feature has already been requested and implemented in plotly.js ([see here](https://github.com/plotly/plotly.js/pull/4413)), but am unsure what's required to get that same data returned through a Dash server-side callback?

Thanks in advance,
J.

**Comment by nicolaskruchten** [comment]
Hello! In order to get the latest plotly.js bundle you need to be using the latest version of `dash` and `dash_core_components`.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
