### ISSUE TITLE
Simplified redirects

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#1370]
Several modifications are proposed in https://github.com/plotly/dashR/pull/225 to support user-defined server routes in Dash for R, which will include a convenience function for URL redirects. 

Following discussion with @alexcjohnson, it seems that we could make the same UI improvements within Dash for Python as well. 

For example, this `server.route` decorator:

```python
@server.route('/daq')
def redirect_daq():
    return redirect('/dash-daq', code=301)
```

could be rewritten more concisely as

```python
app.redirect('/daq', '/dash-daq')
```

Further, a parameterized redirect such as 

```python
@server.route('/daq/<path:subpath>')
def redirect_daq_part(subpath):
    return redirect('/dash-daq/{}'.format(escape(subpath)), code=301)
``` 

... might look instead like

```python
app.redirect('/daq/<path:subpath>', lambda subpath: '/dash-daq/{}'.format(escape(subpath)))
```

@Marc-Andre-Rivet

**Comment by Marc-Andre-Rivet** [comment]
@rpkyle Should we expose the redirect code in the simplified redirect?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
