### ISSUE TITLE
[Feature Request] Enable hot Reloading in WSL 2

### ISSUE THREAD

**Issue by maulberto3** [plotly/dash#1390]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an adjustment, I think. 

**Describe the solution you'd like**
Pretty much hot realoading dash apps using WSL 2 through Windows Terminal

**Additional context**
If it's any help. On a related reddit thread, there seems to be change in the file sharing protocol, which might be relevant to this request.

https://www.reddit.com/r/bashonubuntuonwindows/comments/c48yej/wsl_2_react_not_reloading_with_file_changes/

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
