### ISSUE TITLE
Interval component doesn't work when Dash app is an iframe of a Flask app

### ISSUE THREAD

**Issue by louis-red** [plotly/dash#1405]
Dash modules installed : 

```dash                      1.13.4
dash-bootstrap-components 0.10.5
dash-core-components      1.10.1
dash-html-components      1.0.3
dash-renderer             1.5.1
dash-table                4.8.1
```
I have a Dash app displayed as an iframe inside a Flask app. All components work fine, but not the Interval one, which is never updated.

If I run my Dash app as a standalone app, it works.

Would there be a workaround ?

**Comment by oadriandiaz** [comment]
Can you elaborate? I Have a Dash app in an embedded iframe served with a Flask app, and the `dcc.Interval` works fine triggering a callback to do some job in both client and server sides ;)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
