### ISSUE TITLE
[BUG] dash_daq.gauge errors when changing minimum

### ISSUE THREAD

**Issue by TheDrEmil** [plotly/dash#1418]
**Describe the bug**

Here is the link to my forum post regarding this issue. There are also some more infos about the things I tried:
https://community.plotly.com/t/dash-daq-gauge-buggy-broken/45250

To summarize:
When using dcc.gauge and setting the parameter "min" to something other than 0 (In my case I set it to 1), the errors shown in the forum post are thrown. 
It is important to note, that the gauge is displayed correctly and works, although with the slight problem, that the marks on the scale are not labeled. 

**Expected behavior**

No Errors should be shown in the browser console

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
