### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by leo-smi** [plotly/dash#1431]
**Context:**
I'm trying to resize my image with style properties or by a css, in both cases only width works for the image that I have:

Image formats tried: .png and .jpg
Image original size: 994x668

**Dash versions:**
```
dash                      1.12.0
dash-bootstrap-components 0.10.1
dash-core-components      1.10.0
dash-html-components      1.0.3
dash-renderer             1.4.1
dash-table                4.7.0
```
**Bug:**

The image height doesn't change with the codes:

```
.graphOutrosDados{
    max-height:50%;
}

or

.graphOutrosDados{
    height:50%;
}

or

html.Img(style={'height':'50%'})
```

**Expected behavior**

Image be the height that I have set up

![image](https://user-images.githubusercontent.com/20663547/95520162-0e568a00-099d-11eb-8050-b57bfb248132.png)

Only width propertie works, but I do not want my image with wrong height in mobile plataform, or other srcreen size!

the website is : https://4life.gyro.ct.utfpr.edu.br/#
second menu option "outros dados" and select the last dropdown option

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
