### ISSUE TITLE
Dash.jl package generator does not appear to support different folder structures for dependencies

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#1435]
As originally described in https://github.com/plotly/dash/pull/1125, some component library authors may store their components in a location other than the one we're used to seeing. For `dash-bootstrap-components`, the JS bundle is actually stored within a `_components` subdirectory.

The lines in the Julia component generator which copy in the CSS & JS dependencies date from the initial version I wrote, before the changes in #1125 were added:

https://github.com/plotly/dash/blob/938c3cae72bc66b5f6de9610573f7834569acbfa/dash/development/_jl_components_generation.py#L519-L528

I suggest updating the component generator to support different folder structures for Dash.jl libraries as well.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
