### ISSUE TITLE
[BUG] loading_state property is undefined

### ISSUE THREAD

**Issue by AureClai** [plotly/dash#1441]
Helle everyone,

I'd like to attach a spinner in a button when a div with a lot of graphs inside is loading. I found the use of `dcc.Loading` was good enough to attach the spinner to the loading div but not if I want the loading state of the div displayed anywhere else (in another element).

So, I'd like to catch the `loading_state` property of my div in a callback and render the children of the button depending on the `loading_state['is_loading']` value..

I'm working with theses versions :
```
dash                               1.16.3
dash-bootstrap-components          0.10.7
dash-core-components               1.12.1
dash-html-components               1.1.1
dash-leaflet                       0.1.4
dash-renderer                      1.8.2
dash-table                         4.10.1
```
-  My environnent is :

    - OS: Windows 10
    - Browser : chrome
    - Version 86.0.4240.75

**Bug description**

I have the following code adapted from the [`dcc.Loading` documentation page](https://dash.plotly.com/dash-core-components/loading):

```python
import dash
import dash_html_components as html
import dash_core_components as dcc
import time

from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = html.Div(
    children=[
        html.H3("Edit text input to see loading state"),
        dcc.Input(id="loading-input-1", value='Input triggers loading'),
        html.Div(id="loading-output-1"),
        html.Div(id='loading-info')
    ]
)

@app.callback(Output("loading-output-1", "children"), [Input("loading-input-1", "value")])
def input_triggers_spinner(value):
    time.sleep(1)
    return value

@app.callback(Output('loading-info', 'children'), [Input("loading-output-1", "loading_state")])
def update_loading_info(ld_state):
    if ld_state is None:
        return 'Loading State is None'
    if ld_state['is_loading']:
        return 'The div is loading'
    return 'The div is not loading'


if __name__ == "__main__":
    app.run_server(debug=True)
```

The property `loading_state` of the div is always `undefined` so the call back is called once with `None` as its value.
The `children` property of the div with `loading-info` as ìd` remains "Loading state is None".

**Expected behavior**

As explained in the documentation of all components, the `loading_state` property has to be a dict including the `is_loading` key.

When I type in the input, the `loading_state` of `loading-output-1` should change to `{is_loading': True, ... }`.
Then, during ~1s, the `children` property of the `loading-info` div should be "The div is loading".
Finally, the `loading_state` of `loading-output-1` should change back to to `{is_loading': False, ... }` and the `children` property of the `loading-info` div should become "The div is not loading".

**Screenshots**

![bug_loading_state](https://user-images.githubusercontent.com/15649177/96888137-96e92600-1485-11eb-9fb2-ca8ec55832ab.png)

Here we see the behavior I tried to explain before.

Is this a bug or did I not understand the expected behavior of the `loading_state` property which seems to don't even exists.

Thank you

**Comment by alexcjohnson** [comment]
Hi @AureClai - yes, this is a confusing situation: within the individual React components, `loading_state` is a real prop; but it's not included in the layout object, that we use to create those components as well as to fire and respond to callbacks. So (as you've discovered) it won't work to have a callback directly using `loading_state`, and I think we'd like to keep it this way, otherwise we're mixing transient status with real data and could get into some very strange situations like infinite loops.

My suggestion here would be to make some prop of the `loading-info` component be a second output of the main callback. Doesn't really matter what prop, as you wouldn't really be using it, it would just be a way to mirror the loading state on that component. Then you can use the strategies in https://dash.plotly.com/loading-states to control what's displayed in this component.

I guess the exact behavior you're shooting for here would one way or another involve some CSS to change the text. There are various features we could add to make this more flexible; perhaps something like:
```py
dcc.Loading(type='text', loading_text='The div is loading', children='The div is not loading')
```
Or even more flexible, since we don't support nested components in anything but the `children` prop, perhaps we could make a new component like `dcc.WhileLoading` that could be included in the `children` of `dcc.Loading` and appear only when the `dcc.Loading` is active. That would allow displaying arbitrary components only in the loading state.

**Comment by AureClai** [comment]
Hi @alexcjohnson, 

As a novice I was not aware of multiple outputs for callbacks. I managed to follow your instructions to change my code to something with the expected behavior. I put it below.

```python
import dash
import dash_html_components as html
import dash_core_components as dcc
import dash_bootstrap_components as dbc
import time

from dash.dependencies import Input, Output

app = dash.Dash()

app.layout = html.Div(
    children=[
        html.H3("Click Button for loading"),
        html.Button(
            'Launch Loading',
            id='loading-button',
            className="validate-button"
        ),
        html.Div(id='loading-output'),
        dcc.Loading(type='graph', children=html.Div(
            id='loading-hidden-div', children=None, style={'display': 'none'}))
    ]
)

# Loading hidden prop included as Callback output


@app.callback([
    Output("loading-output", "children"),
    Output("loading-hidden-div", "children")],
    [Input("loading-button", "n_clicks")])
def button_triggers_loading(n_clicks):
    if n_clicks is None:
        return (None, None)
    time.sleep(5)
    return ('Loading Done', None)


if __name__ == "__main__":
    app.run_server(debug=True)
```

Now, when the button is clicked, a spinner is spinning during 5s in a uncorrelated div in the components hierarchy. In my projet, I found that the `fullscreen`  prop of `dcc.Loading` corresponded more to what I tried to achieve. Anyway, this was interesting and thak you very much for your help.

**Comment by alexcjohnson** [comment]
OK great! I'll close this issue then, but I've opened https://github.com/plotly/dash-core-components/issues/873 to follow up on some of the ideas that popped out above.

**Comment by luggie** [comment]
> My suggestion here would be to make some prop of the `loading-info` component be a second output of the main callback. Doesn't really matter what prop, as you wouldn't really be using it, it would just be a way to mirror the loading state on that component. Then you can use the strategies in https://dash.plotly.com/loading-states to control what's displayed in this component.

This sounds very interesting. In my case I'd use a 'loading-info' prop as State of a callback. This cannot be done with the example, provided by https://github.com/plotly/dash/issues/1441#issuecomment-715204170
