### ISSUE TITLE
[Feature Request] Add a __call__ method to dash.Dash allowing to directly use it as a WSGI app

### ISSUE THREAD

**Issue by segevfiner** [plotly/dash#1450]
**Is your feature request related to a problem? Please describe.**
To deploy a dash app to a production WSGI server you currently need to add a `server` variable (`server = app.server`) so as to expose the underlying WSGI app, unlike in Flask where you can just use the `app`/`Flask` object directly.

**Describe the solution you'd like**
Implement a `__call__` method like Flash does: [pallets/flask/app.py:2031-2035](https://github.com/pallets/flask/blob/5d60cce2429e2c7e11e9acc5ea030464bf169f84/src/flask/app.py#L2031-L2035), pointing to the server.

```python
def __call__(self, environ, start_response):
    return self.server(environ, start_response)
```

**Describe alternatives you've considered**
Have to keep defining such a `server` variable, having to modify apps that forget to add it.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
