### ISSUE TITLE
[Feature Request] Need error messages on fail

### ISSUE THREAD

**Issue by nyck33** [plotly/dash#1452]
Thanks so much for your interest in Dash!

Before posting an issue here, please check the Dash [community forum](https://community.plotly.com/c/dash) to see if the topic has already been discussed. The community forum is also great for implementation questions. When in doubt, please feel free to just post the issue here :)

**Is your feature request related to a problem? Please describe.**
When it fails, say clicking Enter after finishing input on dcc.input(debounc=True) and something is wrong so nothing gets executed, there is not even an error message. That is baffling. There should be error messages in this case.
**Describe the solution you'd like**
Error message pointing to line of code that is causing the error.  On Pycharm debugger, I get everything under the sun but not this.
**Describe alternatives you've considered**
inserting print statements circa 1974.
**Additional context**
I have a dcc.Input that acts as input to two callbacks:  1.  updates a dropdown, 2. outputs a dashtable Datatable to a `html.Div` with all the nutrients and amounts.  These work.
Now when I try to add another callback to update the table that was outputted in the step above, it just fails silently.  
I know this means there is something wrong with my third callback mentioned above but no line numbers, no message, makes it quite an ordeal to trace it down.  I guess it's good in a way that I'm forced to use TDD but in such tiny snippets and anyways TDD would be easier with error messages.  
It's frustrating that I can't even run the debugger to hit on any breakpoints I set in the third callback function.

**Comment by nyck33** [comment]
I have my code up here but the problem callback is `def update_nutrients_table()`.  This is a school project and as a student error messages is pretty much the only way besides print statements that I can figure out what's wrong.  Please add this.  Also is it available on Enterprise edition and are there student discounts if so?
I posted my code on community: https://community.plotly.com/t/callbacks-stop-working-when-i-add-another-callback/46737

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
