### ISSUE TITLE
I cant see the same result

### ISSUE THREAD

**Issue by bilative** [plotly/dash#1460]
Hi,

Nowadays im focused on dash, and i wanna create a side by side graph but when I tried the code from [this tutorial](https://dash-building-blocks.readthedocs.io/en/latest/examples/multigraph.html), I cant see the same result as expected. My graphs are one under the other.

Is this tutorial is not up to date or what is the problem?

Can you recommend me to another way to do clean side by side graphs like this or with the dropdowns?

Thanks in advance!

**Comment by bilative** [comment]
I solved the problem by using dbc.Row() function. It is so useful.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
