### ISSUE TITLE
[BUG] Memory Leak - dash_daq.Gauge when using custom range for the color

### ISSUE THREAD

**Issue by ranajaydas** [plotly/dash#1462]
When the dash_daq.Gauge object's **color** is set to something like -
{'default': some color, 'ranges': some ranges}
and the callback uses n-intervals to update the color, there's a memory leak (the GPU usage in Chrome keeps increasing).

This only happens when the 'ranges' key is used (and I suspect it might also occur if a gradient is used) but not when the Gauge only uses the 'default' key by itself.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
