### ISSUE TITLE
[BUG] 51 "Id not found in layout" errors but my app works

### ISSUE THREAD

**Issue by nyck33** [plotly/dash#1464]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment so we can easily reproduce the issue.
I posted in community: https://community.plotly.com/t/51-id-not-found-in-layout-errors-but-my-app-works/47492
-  replace the result of `pip list | grep dash` below
```
dash                      1.17.0
dash-bio                  0.4.8
dash-bootstrap-components 0.10.7
dash-core-components      1.13.0
dash-html-components      1.1.1
dash-renderer             1.8.3
dash-table                4.11.0
jupyter-dash              0.3.1

```
-  if frontend related, tell us your Browser, Version and OS

    - OS: [e.g. iOS] ubuntu 18.04 lts
    - Browser [e.g. chrome, safari] firefox
    - Version [e.g. 22] 83.0 64 bit

**Describe the bug**

Sometimes the links to switch pages stops working but otherwise everything works.  
My NCBI APi calls, biopython alignments, all work.  Just switching from the Dash Bio Demo page that has Dash Bio alignment chart and back to the middle Entrez page stops working just now.

**Expected behavior**

Errors stop appearing or a different error telling me what else could be triggering those error messages.

**Screenshots**

Please refer to the community page above, link to my repo is also provided.
It can be run from the directory where main.py resides.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
