### ISSUE TITLE
[Feature Request] allow extension hooks in Dash

### ISSUE THREAD

**Issue by sdementen** [plotly/dash#1465]
I am relying on dash-extensions on one side for some features (memoization, ...)
On the other side, I would like to wrap the dash app in django with django-plotly-dash for other features (full website with django + store state in DB).
These two projects (dash-extensions and django-plotly-dash) both implement a new Dash object that reuse the original Dash objects but rewrite callbacks, or do other manipulations on top of the standard Dash object.
There are also incompatibles AFAIK.

I wonder if it would not be interesting to see in these two projects the hooks that would be needed in the dash framework to allow for a smoother extension of Dash (and also make these extensions compatible with each others).
Has there already been some discussion on this topic ? @emilhe you may be more aware ...

**Comment by emilhe** [comment]
I am not aware of any such efforts from an official side, but I think it would be an awesome feature. I also think it would lower the barrier of entry, in particular for new users, if they didn't have to replace all of their objects with 3rd party clones (as i do in dash-extensions) :)

**Comment by sdementen** [comment]
From your experience with dash-extensions, what would be the hooks needed for dash-extensions to be able to be "plug and play"?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
