### ISSUE TITLE
[Feature Request] [Question] react native for Windows

### ISSUE THREAD

**Issue by AdamJel** [plotly/dash#1469]
Hi,
I have a question and maybe a feature request.

I would like to achieve a windows GUI app written entirely in python. I though of doing it with this chain:
python -> dash -> react native -> [react native for windows](https://microsoft.github.io/react-native-windows/) -> windows app.
But to achieve this, it would be needed to translate app.py to app.js (as far as I understand it). Can this be done and how? And if not, hence the feature request.

I think, it would be absolutely awesome, to have this possibility, as it would allow for easy python-only windows/android/iOS app development.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
