### ISSUE TITLE
[Dropdown]

### ISSUE THREAD

**Issue by RammySekham** [plotly/dash#1494]
Multiselect Dropdown (dcc.dropdown) captures the selection in the form of list. 
I believe the primary purpose of dcc components is to query data and update graphs.
It is difficult to query the list in SQL database ? Why not it capture it as Tuples.

i.e.  dropdown values : USA,UK,AUS,SPAIN
Selection with multi =True: countries:  ['USA', 'UK', 'AUS' ]
But SQL database syntax have tuples: WHERE Country IN ('UK', 'USA', 'SPAIN');  

Alternative I consider   Country IN {tuple(countries)}

Secondly, when I use tuple and I have only one country selected in my dash app dropdown.
 It has this 'additional ' comma at the end => ('UK',)
Can't be directly queried with SQL database. Need to use other python function with it.

Aboutme: I am bit new to Dash, started building my first app. I used this as alternative :
` if len(countries) == 1:
         countries = "('" + countries[0] + "')"
  else:
         countries = tuple(countries)`

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
