### ISSUE TITLE
Sankey diagram link shading inconsistent when saved as static

### ISSUE THREAD

**Issue by xaviernogueira** [plotly/dash#1524]
The sankey diagram function, when applied within this script :
`nodes = {
                "label": ['Oversized', 'Const.Pool',  'Wide Bar', 'Nozzle', 'Oversized', 'Const.Pool', 'Wide Bar', 'Nozzle', 'Oversized', 'Const.Pool',  'Wide Bar', 'Nozzle'],
                "x": [0.1, 0.1, 0.1, 0.1, 0.5, 0.5, 0.5, 0.5, 0.9, 0.9, 0.9, 0.9],
                "y": [0.2, 0.4, 0.6, 0.8, 0.2, 0.4,  0.6, 0.8, 0.2, 0.4, 0.6, 0.8],
                "color": ['black', 'blue', 'orange', 'red', 'black', 'blue', 'orange', 'red', 'black',
                          'blue', 'orange', 'red'],
                'pad': 15}

fig = go.Figure(go.Sankey(
        arrangement="snap",
        node=nodes,  # 10 Pixels
        link={
            "source": source,
            "target": target,
            "value": value}))`

With no link colors specified is causing the darkness of the links to vary randomly across the plot when saved as a static. There will be paths that are dark grey, or segments of paths that are said dark grey while most is the default light grey. 
Let me know if this is a common issue, and if not I am happy to have alerted the plotly team.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
