### ISSUE TITLE
[Feature Request] Async callbacks

### ISSUE THREAD

**Issue by nikkolasg** [plotly/dash#1566]
Hi,

I have been searching but without any good results on how to call async functions inside dash callbacks. I imagine dash callbacks would be needed to be async as well. Is there an async version of Dash ? Any plans ?
Of course I may be able to go back to the regular version of the lib I want to use, but it'd be nice to be able to use async logic :)

Thank you

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
