### ISSUE TITLE
Integration with pandas-profiling

### ISSUE THREAD

**Issue by kart2k15** [plotly/dash#1599]
There is no html/core component to integrate a pandas-profiling report in a dash app. I even saved the report as a html file and tried inserting it as an Iframe but it did not work.

[Pandas Profiling](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/getting_started.html)

Streamlit is available as an integration--
[https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/integrations.html](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/integrations.html)

**Comment by Mashnak** [comment]
Did you find a solution for this issue jet?

**Comment by pihash252** [comment]
Yes, I was trying to achieve the same. Did anyone find a workaround for this?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
