### ISSUE TITLE
[Feature Request] Provide better support for Flask-routed Dash apps

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash#1621]
Not 100% certain this is an interesting idea but we do run into issues hosting large apps with multiple routes having collisions, requiring more resources, etc. and generally requiring app developers to be aware of more implementation details than might be otherwise required.

At the moment to create a Dash App with multiple routes one does this: https://dash.plotly.com/urls with the key part being:

```
# Update the index
@app.callback(dash.dependencies.Output('page-content', 'children'),
              [dash.dependencies.Input('url', 'pathname')])
def display_page(pathname):
    if pathname == '/page-1':
        return page_1_layout
    elif pathname == '/page-2':
        return page_2_layout
    else:
        return index_page
    # You could also return a 404 "URL not found" page here
```

Suggesting we provide better Flask integration by allowing Flask to control the routes instead, providing isolated Dash apps

server.py
```
import app1.app as app1
import app2.app as app2

server = Flask()
app1(server, url_base_pathname='/app1')
app2(server, url_base_pathname='/app2')

server.run(port=8000)
```

The key here would be to then find a way to handle all routes with the pattern `/_dash-component-suites/<string:package_name>/<path:fingerprinted_path>` as coming from the same app, with redirection, in order to allow proper browser caching.

This would allow individual apps / routes to be fully isolated from one another when writing them (no callback / component id collisions) and to minimize the JS budget of each route to what it actually needs instead of all the required dependencies for all routes.

Shared templating layout and callbacks could be imported and used from the individual apps. Store data should work fine as long as the id stays the same.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
