### ISSUE TITLE
When run via poetry, process introspection for reloading is flawed

### ISSUE THREAD

**Issue by rbpawle** [plotly/dash#1641]
I honestly don't know if this is a bug with Dash or with Poetry.

When running in debug mode, Dash does some introspection on the process about how it was called in order to spin up a subprocess. When Poetry is used to run dash (as in `poetry run my_dash_app`), the actual python command is a little different than the traditional `python my_dash_app.py`. On my Mac it was `/path/to/myenv/python /path/to/my/module`, where I think it should have been `/path/to/myenv/python /path/to/my/module/app.py`.

Anyway, the program crashes with`/path/to/myenv/python: can't find '__main__' module in /path/to/my/module`.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
