### ISSUE TITLE
[BUG] click on `Scattergeo` not registered

### ISSUE THREAD

**Issue by stoufa** [plotly/dash#1650]
**Context**

`pip list | grep dash` output:
```
dash                            1.19.0
dash-bootstrap-components       0.11.3
dash-core-components            1.15.0
dash-dangerously-set-inner-html 0.0.2
dash-html-components            1.1.2
dash-renderer                   1.9.0
dash-table                      4.11.2
dash-treeview-antd              0.0.1
```

**Bug Description**

When you perform the following tasks:
1. click on a country
2. choose an option from the dropdown menu
3. click on the same country you clicked on in step 1.

The second click will be ignored (i.e. it won't be registered)

**Expected behavior**

The second click should be detected even in the case where the user chose to click once again on the same country he clicked on before. The current behavior "might" be understandable in the case where the map component received two successive clicks on the same country but in our case, there is another event on another component of the dashboard (separating the two clicks), which should clear the state of the map.

**Screenshots**

The following YouTube video showcase the bug I was talking about in detail:

<p align="center">
  <a href="https://www.youtube.com/watch?v=Ru5yP1kR1ok" target="_blank">
    <img src="https://img.youtube.com/vi/Ru5yP1kR1ok/0.jpg" alt="Dash Bug | 2021 05 24 17 12" />
  </a>
</p>

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
