### ISSUE TITLE
Could usage of `__slots__` in automatically generated class components further improve performance of Dash apps?

### ISSUE THREAD

**Issue by anders-kiaer** [plotly/dash#1657]
After reading [this StackOverflow post](https://stackoverflow.com/questions/472000/usage-of-slots), and also the [official Python documentation](https://docs.python.org/3/reference/datamodel.html#slots), I started wondering if there is an easy performance improvement that can be done for Dash applications (or if the below has been considered before):

Basically adding `__slots__` to the Python classes (e.g. https://github.com/plotly/dash-html-components/blob/v1.1.3/dash_html_components/Div.py) automatically generated by `dash-generate-components`, and populate this with the attributes the component build tool already knows it will populate the component with. Potentially a small change, which could save both memory for Dash apps with many components, and performance improvement (quicker attribute lookup).

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
