### ISSUE TITLE
Adding timestamps in dashboard using dash library in python

### ISSUE THREAD

**Issue by willows-1** [plotly/dash#1660]
Hi, how can I add multiple timestamps using dash library in python? My intention is to achieve something like this:

![image](https://user-images.githubusercontent.com/66007300/120092660-4cc8d100-c147-11eb-8a17-9f604e6e6174.png)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
