### ISSUE TITLE
[Feature Request] Toggle between graphs and reset animation frame to 0

### ISSUE THREAD

**Issue by Bytecat01** [plotly/dash#1667]
I am new to Dash and I am trying to implement something very similar to [this](https://plotly.com/python/animations/). (section: Animated figures in Dash), but instead of dcc.RadioItems, I am using dcc.dropdown.

However, if you select the first graph (scatter), press play, then pause it during the mid animation, and then switch to the bar graph, the animation resets to 1952 as expected. However, when you press play, it continues from where you paused in the scatter plot.

For my purposes, I have two different graphs with two different scales, and I would like to have it reset to 0 and start at 0 if a user toggles between the graphs.

Is there any functionality built in to get around this?

**Comment by griko** [comment]
The "not so nice" solution is to add a slider by yourself and add animation through the Interval component. An example of such an app can be found [here](https://github.com/griko/tutorials/tree/master/dash-controllable-slider).

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
