### ISSUE TITLE
[BUG]Layout not reloaded when changing page-content in Multi-Page app

### ISSUE THREAD

**Issue by denisesato** [plotly/dash#1669]
Hello all,

   I have followed the documentation for creating a Multi-Page app in https://dash.plotly.com/urls. I have applied the suggested structure define in the topic "Structuring a Multi-Page App". But I have a problem. One of my pages (page 3 - app_process_models) has a component that should start invisible and it changed to visible in a callback function. But, after I go back to the first page of my app (for instance), and selected page 3, the layout is not reloaded, the component is visible without any calls to the callback function. I am not sure if this is a bug or if I am not correctly using the architecture, but I have no ideas how to solve it.

Kind regards,
Denise

Source code:

index.py

```
@app.callback([Output('page-content','children'),` Output('hidden-filename', 'children')],
              [Input('url', 'pathname')],
              [State('url', 'search')])
def display_page(pathname, search):
    filename = ''
    if search:
        filename = search.partition('?filename=')[2]

    if pathname == '/':
        return app_manage_files.layout, filename
    if pathname == '/apps/app_manage_files':
        return app_manage_files.layout, ''
    elif pathname == '/apps/app_process_models':
        return app_process_models.layout, filename
    elif pathname == '/apps/app_preview_file':
        return app_preview_file.layout, filename
    else:
        return '404'`
```

app_process_models.py - LAYOUT - COMPONENT THAT IS STARTED INVISIBLE
```
dbc.Col([
            ...
        ], id='models-col', width=9, style={'height': '100vh', 'display': 'none'})
```

app_process_models.py - CALLBACK
```
@app.callback([Output('models-col', 'style'),
               Output('window-slider', 'min'),
               Output('window-slider', 'max'),
               Output('window-slider', 'value')],
              Input('current-final-window', 'children'),
              State('window-slider', 'min'),
              State('window-slider', 'max'),
              State('models-col', 'style'),
              State('window-size', 'value'), 
# this callback is triggered when mining have finished
def update_slider(current_final_window, min, max, models_col_style, win_size):
    if current_final_window:
        app.logger.info(f'Atualiza window-slider min: 1, max: {current_final_window - 1}, value: 0')
        return {'height': '100vh', 'display': 'block'}, min, current_final_window - 1, 0
    else:
        return {'height': '100vh', 'display': 'none'}, min, max, -1`
```

My environment:
dash                      1.20.0
dash-bootstrap-components 0.12.2
dash-core-components      1.16.0
dash-html-components      1.1.3
dash-interactive-graphviz 0.3.0
dash-renderer             1.9.1
dash-table                4.11.3

**Comment by jlfsjunior** [comment]
I believe this behavior happens because the callback will be re-evaluated when you go back to page 3 and `current_final_window` is no longer `None` as in the first time you opened it. If that's the case, this is not a bug.

Please refer to [Advanced Callbacks](https://dash.plotly.com/advanced-callbacks#when-dash-components-are-added-to-the-layout) for more information, especially the subsection on *When Dash Components Are Added To The Layout*.

The solution depends on which functionality you want from your application.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
