### ISSUE TITLE
Dash returns a blank page from time to time on a reload without cache

### ISSUE THREAD

**Issue by JonasDeBoeck** [plotly/dash#1672]
I have deployed my dash dashboard on an ubuntu server using uwsgi.
Everything was running smoothly untill I got reports from users that the webpage they got was blank and that the tabs weren't working.
I took a look into the problem and I saw that once every while when I reload the webpage without using my cache I get a blank page too. Until now I haven't been able to reproduce the tab bug.
I see some errors in my js console though. These are the following:
![image](https://user-images.githubusercontent.com/43340565/122804685-7bf6dc00-d2c8-11eb-89a5-7807d699b2f2.png)
The webpage I get is:
![image](https://user-images.githubusercontent.com/43340565/122804725-89ac6180-d2c8-11eb-8cdb-124774dc64d6.png)
Because the code normally works I don't think there is a problem in my code, but I don't know what else the problem might be.
Perhaps network speed?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
