### ISSUE TITLE
[BUG] Callbacks can update non-exposed props

### ISSUE THREAD

**Issue by tcbegley** [plotly/dash#1673]
Perhaps this is intended, but I found it pretty surprising. Callbacks can be used to update props of Dash components that aren't actually exposed as keyword arguments in the Python components.

Here's a simple example

```python
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash()

app.layout = html.Div(dcc.Input(id="input"), id="div")


@app.callback(Output("div", "doesnt-exist"), Input("input", "value"))
def return_value(value):
    return value


if __name__ == "__main__":
    app.run_server()
```

If you run this app you will get an error in the browser console (which I think might be easily missed), but nothing else suggests anything is wrong (story is quite different if you run in debug mode). Typing in the box now passes through a `doesnt-exist` prop to the component which in this case naively passes it on to the underlying HTML component.

![image](https://user-images.githubusercontent.com/15220906/122878402-a334c400-d32f-11eb-90bc-8b34fbd5d2ff.png)

I found out about this when [someone reported](https://github.com/facultyai/dash-bootstrap-components/issues/610) that they could set the `title` of `dash_bootstrap_components.Button` with a callback, but weren't able to provide an initial value to the component.

I'm not sure what the right thing is here. Clearly the error is already being detected, hence the message in the console. Should the error terminate the app or surface more visibly though? Maybe it's just harmless and the current behaviour is fine? 🤷‍♂️ 

The above example was run locally with the following versions of Dash libraries.

```
dash                            1.20.0
dash-core-components            1.16.0
dash-html-components            1.1.3
dash-renderer                   1.9.1
dash-table                      4.11.3
```

**Comment by AnnMarieW** [comment]
Prior to  1.11.0 the app halts with an error message.  This might be part of this change that was noted in the CHANGELOG.md:

- Callback validation is now mostly done in the browser, rather than in Python. A few things - mostly type validation, like ensuring IDs are strings or dicts and properties are strings - are still done in Python, but most others, like ensuring outputs are unique, inputs and outputs don't overlap, and (if desired) that IDs are present in the layout, are done in the browser. This means you can define callbacks BEFORE the layout and still validate IDs to the layout; and while developing an app, most errors in callback definitions will not halt the app.

**Comment by alexcjohnson** [comment]
Yes, this can be surprising behavior, but it is as intended: when you run in debug mode (more specifically, `dev_tools_props_check` which is one of many flags turned on with debug mode) we validate props against the components you’re giving them to, but following React itself we remove that check in production mode, for better performance. I’m actually a little surprised that prior to 1.11 we didn’t disable this check, I think that was always our intent, but I guess during that refactor this behavior got cleaned up.

**Comment by tcbegley** [comment]
Makes sense, thanks for clearing it up!
