### ISSUE TITLE
I got a interval in my callback inputs,How can I choose to do sth or just do nothing.

### ISSUE THREAD

**Issue by NekoGaHoshiyi** [plotly/dash#1682]
I noticed that when I put a interval input in the callback Input list, I surely can make changes to the outputs,but I also want to do nothing with the outputs according to some "if"( at some circumstances), I find the callback keep refereshing the output.
That makes the elements on the page can't  keep some opearations available like zoom in/out, etc even if I just return the same outputs as the page holds at the first time.

**Comment by alexcjohnson** [comment]
> does dash callback func must have at least one input and one output?

Yes. If you just want to do something on the back end, use a dummy output that you don't care about. I recommend `data-<whatever>` on an html element.

> one output could only exist in only one callback func.

Correct. Otherwise the app state becomes ambiguous.

> if a callback func takes a long time to run(not asynchronous)，it appeared that the callback func would blocking other callbacks.

If the output of the long callback is an input to those other callbacks then yes, it will block. But aside from that you can get around this by running multiple workers on the server. [gunicorn](https://gunicorn.org/) is a good way to do this, as described in https://dash.plotly.com/deployment.

I'm going to close this issue, as we try to reserve GitHub for bug reports and feature requests, but like @lucasjamar I encourage you to continue this discussion on https://community.plotly.com/ 😄

**Comment by NekoGaHoshiyi** [comment]
Yep, I just used an extra hidden element as a output when I needed no output. And I used celery woker to take the code lines which cost a long time.
Thanks for ur reply, i gotta say it is a pity that dash's callbacks may not fullfill all needs as flexible as  the orignal  front/backend way.
However, Dash still is a powerful tool to build a wonderful data visualization  proj in a quite short time.
Again,Thanks a lot~
