### ISSUE TITLE
Reset view problem within multi tabs mapbox

### ISSUE THREAD

**Issue by maghaali** [plotly/dash#1686]
I have a problem with reset view of a simple dash app with multi tab that each tab has separate mapbox, please take a look at gif
file
Note: When I use the same code without dash and add them to custom template in django there is no problem

https://gfycat.com/thosesolidkakapo

Versions:
Latest version of packages
Python 3.8

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
