### ISSUE TITLE
Create a updateable dashboard from multiple tables in a SQL database

### ISSUE THREAD

**Issue by idinsmore1** [plotly/dash#1688]
Hello,

This is my first foray into creating dash apps. I've gone through the tutorials and found them very helpful, but my end goal is a bit tricky. I work in bioinformatics, and I want to create a dash app where I connect the app to a database which houses multiple tables of genome wide association studies' results, and create manhattan plots based on the data that is housed there through a user input. For example, if a user were to type "Diabetes" into the input part of the app layout, the app would search through the tables and create a manhattan plot based on a python class that I've created. I've searched for examples of using multiple tables within a SQL database, but can only find examples of pulling one set of data from a database and then filtering upon that data. Is this something that is feasible in Dash? Thanks!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
