### ISSUE TITLE
[BUG] pytest plugin breaks tests with __init__.py files

### ISSUE THREAD

**Issue by bmerry** [plotly/dash#1690]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**

```dash                 0.42.0
dash-core-components 0.47.0
dash-html-components 0.16.0
dash-renderer        0.23.0
dash-table           3.6.0
```

**Describe the bug**

When dash is installed, it seems to alter how pytest sets up sys.path for tests. If a test directory is arranged as a package (with `__init__.py` files, it seems to prevent the root of the package from being added to `sys.path`.

To reproduce, create a directory with the following empty files:
```
└── test
    ├── conftest.py
    └── __init__.py
```

Create a virtual environment with just pytest and dash. Run `pytest` (in the parent of `test`).

Note that this doesn't require dash to be imported anywhere; simply having it installed in the environment is enough to break pytest.

**Expected behavior**

Without dash installed, the following is output:
```
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/bmerry/work/sdp/bugs/dash-breaks-pytest
collected 0 items                                                              

============================ no tests ran in 0.00s =============================
```

With dash installed, the output is:
```
ImportError while loading conftest '/home/bmerry/work/sdp/bugs/dash-breaks-pytest/test/conftest.py'.
ModuleNotFoundError: No module named 'test.conftest'
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by bmerry** [comment]
I can confirm that I can no longer reproduce this issue with the latest version of dash.

**Comment by gvwilson** [comment]
thanks @bmerry - much appreciated
