### ISSUE TITLE
DataTable not printing the Pivoted dataframe

### ISSUE THREAD

**Issue by Prerakshah98** [plotly/dash#1692]
I tried to print pivoted dataframe using datatable using Dash in Python. I cannot get the output of pivoted dataframe in the dashboard. I can only print the dataframe with original columns, but cannot print dataframe when the column names changes using the df.Pivot function. Is there a way I can print the pivoted table in the dashboard.

**Comment by AnnMarieW** [comment]
Hi @Prerakshah98 
After the pivot both the `columns` and the `data` need to be updated.   If you have more questions please post this question on the [Dash forum](https://community.plotly.com/c/dash) and I'll meet you there and work through some examples.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
