### ISSUE TITLE
[BUG] dcc Clipboard does not render

### ISSUE THREAD

**Issue by mwang87** [plotly/dash#1693]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash==1.21.0
dash-bootstrap-components==0.9.2
dash-core-components==1.17.1
dash-html-components==1.0.3
dash-renderer==1.4.0
dash-table==4.12.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS:  Windows
    - Browser Edge
    - Version - Latest

**Describe the bug**

```
dcc.Clipboard(
                target_id="usi1",
                title="copy",
                className="button",
                style={"padding": "0px 2px", "fontSize": 20,},
            ),
```
This does not render the clipboard item, does not appear in the DOM at all. 

**Expected behavior**

**Screenshots**

If applicable, add screenshots or screen recording to help explain your problem.

**Comment by AnnMarieW** [comment]
@mwang87 Could you please provide a MWE that shows the problem?

I can't replicate your error, Here is an example
```
import dash
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash(__name__)

app.layout = html.Div(
    [
        dcc.Textarea(
            id="usi1",
            value="Copy and paste here",
            style={"height": 100},
        ),
        dcc.Clipboard(
            target_id="usi1",
            title="copy",
            className="button",
            style={
                "padding": "0px 2px",
                "fontSize": 20,
                "verticalAlign": "top",
                "display": "inline-block",
            },
        ),
    ],
)

if __name__ == "__main__":
    app.run_server(debug=True)
```


![image](https://user-images.githubusercontent.com/72614349/127201758-0f0b6226-4b64-44d3-ba7d-56bf6623f64f.png)

**Comment by daniel-smit-haw** [comment]
I tried your example:
 I get the Textarea but not the Clipboard-Button.
My browser console says "Copy to clipboard not available with this browser"
I am using the newest Firefox, so I guess the Clipboard API should be available ..?

Firefox 91.0.2
Dash 1.21.0
Dash Core Components 1.17.1

**Comment by AnnMarieW** [comment]
Hi @daniel-smit-haw and thanks for trying out `Clipboard`

If the clipboard API is not available for _any_ reason, then you will see that message in the browser console and the clipboard icon won't appear.  

On one occasion, the cause was likely restrictions in a company network. See the forum discussion [here](https://community.plotly.com/t/dcc-clipboard-is-not-working-in-my-company-network/55899) for more info.   

I've tried in Firefox 90.0.2 with no issues.  Are there some setting in Firefox to allow clipboard access?

**Comment by daniel-smit-haw** [comment]
_Short update (FYI):_ 
In general the Clipbpboard-API works in my firefox-browser (I can acces `navigator.clipboard` in the console), e.g. on github.com.
On my local dev-jupyter-page `navigator.clipboard` is `none`.

My local dev-jupyter-page is served over `http`, my guess ist, that this is the issue.
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#clipboard_availability

**Comment by pfbuxton** [comment]
For the past day I have been struggling to get Clipboard working. In development it all works fine, but in production no Clipboard...

Turns out Clipboard **"requires a secure origin — either HTTPS or localhost"**

There I was thinking it was something to do with my apache2 settings 😂.

This can be verified by temporarily telling Chrome to treat your insecure site as secure:
chrome://flags/#unsafely-treat-insecure-origin-as-secure

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
