### ISSUE TITLE
Slower plotly graph loading after 1.21.0 

### ISSUE THREAD

**Issue by JanWanot** [plotly/dash#1696]
**Context**
```
dash                          1.21.0
dash-bootstrap-components     0.12.2
dash-core-components          1.17.1
dash-html-components          1.1.4
dash-table                    4.12.0
```

- OS: Mac OS Big Sur 11.5.1
- Browser: Firefox 90, Safari Version 14.1.1, Chrome 92

**Bug description**

After upgrading to dash 1.21.0, all dcc.Graph components take around twice as long to load, regardless of amount of data in the graph or the network conditions (i.e. even when running locally). After downgrading to 1.20.0 the issue is fixed. 

**Expected behavior**

Before it never took more then 2 seconds for a plot to fully load (see comparison below). 

**Screenshots**
**1.20.0**
![fast](https://user-images.githubusercontent.com/46744390/128221768-a42127fa-f2b8-4047-a440-ea86c0293182.gif)

**1.21.0**
![slow](https://user-images.githubusercontent.com/46744390/128221729-0a445985-bc21-4191-8843-c98d43042959.gif)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
