### ISSUE TITLE
[BUG] setProps called during unmount should be ignored?

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash#1704]
A really odd dash-renderer edge case (bug?) popped up in Dashboard Engine today: a component was calling `setProps` during its unmount process, which led to us re-creating a path in the layout that we had just removed. They’re able to fix it internally, but I’m trying to figure out if this is something we can detect and avoid at the renderer level.

The worst effects are pretty easy: if there’s no component at the path you’re trying to set props for, bail out. That would have fixed this case.

But what if there is a component there? Maybe even a component of the same type? I don’t think we can really tell 100% when the user intended a component to be new vs modified, but we can perhaps just follow whatever React decided to do. Fortunately it looks to me as though [parents call `componentWillUnmount` before children do](https://developmentarc.gitbooks.io/react-indepth/content/life_cycle/death_unmounting_indepth.html) so perhaps we can detect when a `TreeContainer` has been unmounted (`TreeContainer` is the immediate parent of each individual dash component) and disable its `setProps`?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
