### ISSUE TITLE
Filtering in datatable does not work properly when column contains numbers only

### ISSUE THREAD

**Issue by AltafHussain4748** [plotly/dash#1712]
Filtering in data table does not work properly when column contains numbers only

https://user-images.githubusercontent.com/28758144/129314869-afeb1cde-0431-47bc-b024-c6b96560b101.mp4

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
