### ISSUE TITLE
[BUG] suppress_callback_exceptions=true doesn't work in version 1.21

### ISSUE THREAD

**Issue by NikolaDare** [plotly/dash#1715]
![image](https://user-images.githubusercontent.com/36190616/129710409-ce8196e9-247a-4e85-b889-ed6ed7dfb900.png)
![image](https://user-images.githubusercontent.com/36190616/129710425-dfcc5786-18bf-4fd9-ac77-db5f1e4c3bf0.png)
![image](https://user-images.githubusercontent.com/36190616/129710431-2e927099-ac3b-4368-b1bb-d81d7cf765bc.png)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
