### ISSUE TITLE
[Feature Request] Dash native mobile app support?

### ISSUE THREAD

**Issue by jerryschen31** [plotly/dash#1716]
Is a Dash native mobile framework under development? There are many use cases for this - e.g., a stock/finance iOS/Android app with interactive technical charts. 

Translation of Dash-React components into React Native components would take some time (going from mouse gestures to touch gestures, translation of other events into mobile native, etc..), but I gotta think it's do-able. 

If there is a community that would like to work on this, please respond - thanks!

**Comment by notron30** [comment]
+1

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
