### ISSUE TITLE
[Feature Request] Display hover text when hovering on labels too

### ISSUE THREAD

**Issue by MatteoSid** [plotly/dash#1717]
Is it possible to add the option to display hover text information when hovering in labels? 
I need to display the labels description when hovering on its.

**Comment by banyous** [comment]
Hi, same issue facing here. In my case am trying it to hover words in a  wordcloud figure, is there anyway I can show the word frequencies when I hover over them?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
