### ISSUE TITLE
Investigate need for #1720

### ISSUE THREAD

**Issue by jonmmease** [plotly/dash#1721]
Investigate need for https://github.com/plotly/dash/pull/1720 and see if there's a way to remove the `_pytest` part from the `Dash` constructor.

**Comment by jonmmease** [comment]
I spent a while playing with this, but didn't get too for.  I don't think the current approach is causing any problems, so I'm not going to dig into it much more.  But @alexcjohnson may want to have a look when he has a chance.

**Comment by alexcjohnson** [comment]
Thanks for pointing this out @jonmmease 

Just to be clear: this code was added during #1679 in commit https://github.com/plotly/dash/commit/e169cbc98a1b3d935cdfa5f984660bce638f6d9a and then scoped more tightly in #1720, right? @HammadTheOne can you explain what prompted you to add this? Do you understand why it was only needed in the monorepo context but not before that?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
