### ISSUE TITLE
Store dropdown value 

### ISSUE THREAD

**Issue by jigsawcoder** [plotly/dash#1732]
I have used a dropdown menu in my app and I want to store the selected value from the dropdown as a variable (datatype - string) and use that variable for some calculation and display the results of that calculation on **dbc cards**. I have gone through the documents regarding **dcc.Store** but could not understand how to do it.
Can anyone please tell me how to do it.

Thanks in advance.

**Comment by jlfsjunior** [comment]
This type of question is more suitable to be asked on SO or in [the forum](https://community.plotly.com/). You'll find an answer quicker there.

You just need to pass the dropdown value to `dcc.Store` in a callback:

```py
@app.callback(
    Output("store-id", "data").
    Input("dropdown-id", "value")
)
def update_store(value):
    return value
```

Then use `Input("store-id", "data")` (or `State`) in whichever other callback it is needed.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
