### ISSUE TITLE
`flask_caching` has an open CVE which inhibits use of cache.memoize decorator (?)

### ISSUE THREAD

**Issue by aduggirala28** [plotly/dash#1740]
Hi, 
I use `cache.memoize` decorator in my flask app using the `flask-caching` library with redis. As mentioned in the docs here - https://dash.plotly.com/performance 

Flask-caching currently has an open CVE since it uses pickling for serialization/deserialization. 
https://github.com/sh4nks/flask-caching/pull/209#issuecomment-841101277
This open CVE is at 9.8 right now ^

Is there going to be an alternative to use a different library to continue using this decorator?

**Comment by anders-kiaer** [comment]
Have not tried it, but could something from https://docs.python.org/3/library/functools.html work?

Also, `dash==2.0` got the concept of "long callbacks caching/memoizing", which in our Dash based project we will try to see if can replace `flask-caching` in some cases. See https://dash.plotly.com/long-callbacks and "Caching Results" in the right menu.

**Comment by aduggirala28** [comment]
thanks @anders-kiaer, will check the options out

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
