### ISSUE TITLE
UserWarning:  The dash_core_components package is deprecated

### ISSUE THREAD

**Issue by Badruzaman** [plotly/dash#1755]
When I run my project shows such a warning and takes more run time  than before. I am using Pycharm editor.

**Comment by anders-kiaer** [comment]
To remove `UserWarning` for `dash >= 2.0` follow the migration guide: https://dash.plotly.com/dash-2-0-migration

I.e. instead of `import dash_core_components as dcc` do e.g. `from dash import dcc`.

**Comment by Badruzaman** [comment]
Thank you so much it worked for me

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
