### ISSUE TITLE
dash not dispatching _dashprivate_historychange event on dcc.Location change in Callback

### ISSUE THREAD

**Issue by ghost** [plotly/dash#1785]
Hi, i'm not sure if it would be desired for dash to dispatch a _dashprivate_historychange event if the URL was changed in a callback.

Please also refer to:
https://community.plotly.com/t/react-to-pathname-or-href-change-in-dash-component/55619

Use Case:
Components, for example the Navigation of dash-bootstrap-components can set the "active" style based on the current url. If the URL is changed in a callback (clicking on a dcc.Link does fire the event), the _dashprivate_historychange event is not dispatched and needs to be fired manually, for example:
```
app.clientside_callback(
    """
    function(n_clicks) {
        if (n_clicks > 0){
            console.log(n_clicks);
            history.pushState({}, '', "/url_base_pathname/pathname/");
            const ON_CHANGE = '_dashprivate_historychange';
            window.dispatchEvent(new CustomEvent(ON_CHANGE));
        }
    }
    """,
    Output("url", "pathname"),
    Input("testbutton", "n_clicks"),
)
```

But it is generally desired to dispatch this event if a callback changes the pathname of the URL?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
