### ISSUE TITLE
Dropdown is not working in DataTable with bootstrap css

### ISSUE THREAD

**Issue by akksi** [plotly/dash#1814]
https://dash.plotly.com/datatable/dropdowns
Error is coming from this rule:
![image](https://user-images.githubusercontent.com/14875243/138280759-75b5b60e-6aa1-4ffc-ba19-3c0f64ce5e2f.png)

To reproduce it with bootstrap, this can be added to the examples from the docs:
```
import dash_bootstrap_components as dbc

app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
