### ISSUE TITLE
[BUG] - Docs example 'Non-Linear Slider and Updatemode' doesn't render correctly in Dash 2.1  

### ISSUE THREAD

**Issue by LiamConnors** [plotly/dash#1843]
This Slider example: https://dash.plotly.com/dash-core-components/slider#non-linear-slider-and-updatemode has a functioning slider on the docs page. 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/12749831/143492931-523df790-8dd5-41ee-a7aa-8fdf3634799c.png">

Using Dash 2.1, and without any update to the example code, the slider no longer works.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/12749831/143492909-0e9806c4-67f3-4732-9bdf-a547c3bed799.png">

I can't see any changes in the Slider's functioning that should cause this. `step` and `marks` are both provided.

**Comment by HammadTheOne** [comment]
Just wanted to note - this example works if the `min` prop is set for the slider. The marks are actually broken in the existing page as well, although the slider works. I'm adding a change to the slider so that an undefined min and max are determined if marks are set, but I think we should still update the example anyways:

```
    dcc.Slider(
        id='slider-updatemode',
        marks={i: '{}'.format(10 ** i) for i in range(4)},
        min=0
        max=3,
        value=2,
        step=0.01,
        updatemode='drag'
    ),
```
