### ISSUE TITLE
[BUG] px.imshow(text_auto=True), text not visible in dash

### ISSUE THREAD

**Issue by mikulatomas** [plotly/dash#1875]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

```
dash                 2.0.0
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
plotly               5.5.0
plotly-express       0.4.1
```

  - OS: MacOS 12.1 (21C52)
  - Browser Chrome/Safari - does not matter

**Describe the bug**
The `fig` created via `plotly.express.imshow` with parameter `text_auto=True` does not show values as expected.

Minimal example:

```python
import dash
from dash import dcc
from dash import html
import plotly.express as px


z = [[.1, .3, .5, .7, .9],
     [1, .8, .6, .4, .2],
     [.2, 0, .5, .7, .9],
     [.9, .8, .4, .2, 0],
     [.3, .4, .5, .7, 1]]

fig = px.imshow(z, text_auto=True)

app = dash.Dash()
app.layout = html.Div([
    dcc.Graph(figure=fig)
])

app.run_server(debug=True)
```

**Expected behavior**
Described here https://plotly.com/python/heatmaps/#text-on-heatmap-points
![Screenshot 2021-12-30 at 16 12 00](https://user-images.githubusercontent.com/510112/147763962-4c56bdeb-9da6-4317-a419-6266c05082e9.png)

**Screenshots**
Screenshot of code above:
![Screenshot 2021-12-30 at 16 11 16](https://user-images.githubusercontent.com/510112/147763889-16933234-f85b-45cb-8b11-5d4dadd41d8e.png)

**Comment by alexcjohnson** [comment]
`dash.dcc` includes its own version of plotly.js, which hasn't been updated yet to include this new feature. We're hoping to get that done this week, but in the meantime you can use the plotly.js version you want - perhaps https://cdn.plot.ly/plotly-2.8.3.min.js - either by downloading it and putting it in your `assets/` folder or by linking to the cdn in `external_scripts`.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
