### ISSUE TITLE
[BUG] App doesn't work when ran from a different directory

### ISSUE THREAD

**Issue by Hunter2809** [plotly/dash#1889]
**Describe your context**
```
dash                          2.0.0
dash-core-components          2.0.0
dash-html-components          2.0.0
dash-table                    5.0.0
pydash                        5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows

**Describe the bug**
I have a files directory like this
```
root
 |
 |-- website
        |
        |-- main.py
```

So now, when I run the main.py from the root directory in VSCode (since I have opened the whole folder in VSCode), it stops running with the following output

```bash
Dash is running on http://127.0.0.1:8000/

 * Serving Flask app 'main' (lazy loading)
 * Environment: production
 * Debug mode: on
No module named main
```

I have never experienced this issue with either PyWebIO or Flask

**Expected behavior**
It should run the file normally without any error

**Screenshots**

![image](https://user-images.githubusercontent.com/46440327/149375756-c20d39ef-38e3-446f-b23b-ab17c3e8965b.png)

**Comment by JonThom** [comment]
Are you passing the __name__ as the first argument to dash.Dash()?

**Comment by Hunter2807** [comment]
Yea...

**Comment by seanslma** [comment]
Weird. Seems we must run the main.py from outside of the module/package. 
In this case, there is no issue if import the app in `main.py` and then run it as `app.run(host='127.0.0.1', port=8000, debug=True)`.

**Comment by rhigladney** [comment]
Appreciate the information

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
