### ISSUE TITLE
[Feature Request] Independent Axis Zoom

### ISSUE THREAD

**Issue by TonyMiri** [plotly/dash#1896]
**Is your feature request related to a problem? Please describe.**
When viewing financial timeseries data it is necessary to be able to zoom in on the data without having the visualization of the data become distorted. When increasing the granularity of the axis in only one direction, x or y, the data becomes 'stretched' and the visualization is no longer useful. This is the current behavior when using the range slider feature.

**Describe the solution you'd like**
I would like the ability to increase/decrease the granularity of each axis independently.

**Describe alternatives you've considered**
I have found a couple scripts online that achieve an effect that *somewhat* mimics this effect, but they are cumbersome to use and only moderately mitigate the issue. The other option is to use a different library for charting.

**Additional context**
![image](https://user-images.githubusercontent.com/10749424/150626353-ad9f5d1c-376d-478c-bbe0-4c6a2c0141b2.png)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
