### ISSUE TITLE
[BUG] Lost Edits in Dash DataTables

### ISSUE THREAD

**Issue by ekwan** [plotly/dash#1898]
Issue:
If I click on a cell and then start typing, the cell edits normally.  However, if I click on a cell, then select the text inside, type to replace the text, and click away, the changes are not saved.  But!  If I select the text inside, type to replace it, then press enter, the changes are saved.  This seems like a bug.

Code to Reproduce: (nearly the same as the first example in the docs)
```
import dash
import dash_table
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')

app = dash.Dash(__name__)

app.layout = dash_table.DataTable(
    id='table',
    columns=[{"name": i, "id": i, "editable":True} for i in df.columns],
    data=df.to_dict('records'),
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

Context:
```
dash                      2.0.0
dash-bootstrap-components 1.0.2
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
```
MacOS, Chrome 97

**Comment by frnhr** [comment]
I can confirm the bug. Here is how it looks like:
![Recording  157](https://user-images.githubusercontent.com/1173748/202689877-dd5708ed-3295-4ed8-82a9-d343efe1bbca.gif)

Only pressing Enter or Tab seems to lock the value in the cell.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
