### ISSUE TITLE
[BUG] Version mismatch between dash & dash extensions.

### ISSUE THREAD

**Issue by jingak01** [plotly/dash#1899]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
dash_extentions.snippets.py import html from dash which raise an import error.

ideally in dash_extentions.snippets.py html should be call from dash_html_components 

**Describe the bug**
dash_extentions.snippets.py import html from dash which raise an import error.

line: from dash import html

**Expected behavior**

ideally in dash_extentions.snippets.py html should be call from dash_html_components 

from dash_html_components import html

**Screenshots**

<img width="796" alt="Screenshot (27)" src="https://user-images.githubusercontent.com/45057990/150978220-14b5fed2-4191-47a6-98fb-11470be3990d.png">

**Comment by alexcjohnson** [comment]
`from dash import html` is the Dash 2.0 import - and I see that `dash-extensions` does include [`dash~=2.0.0`](https://github.com/thedirtyfew/dash-extensions/blob/f59655278eda1ff92ababdb3204953ae08f954e9/requirements.txt#L1) so it's a bit surprising that you have this with an older version of Dash 🤔

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
