### ISSUE TITLE
[BUG]     from .dash import Dash, no_update  # noqa: F401,E402

### ISSUE THREAD

**Issue by paula-nextsense** [plotly/dash#1957]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

-  if frontend related, tell us your Browser, Version and OS

    - OS: Mac OS Monterey (Apple M1 Pro)
    - Version  dash==1.21.0

**Describe the bug**
Using Python3.8 in a venv environment with dash==1.21.0 installed, I'm unable to import it into my python program

I checked the libraries installed in this environment via pip3 and Dash is installed.  We're looking to update the version of dash, but would like to get the current project working.  

~/PycharmProjects/data_analysis/venv/bin
beehive@ciderhouse bin % ./pip3 list
Package                   Version
------------------------- ------------
appdirs                   1.4.4
audioread                 2.1.9
dash                      1.21.0
dash-bootstrap-components 0.13.1
dash-core-components      1.17.1

**Expected behavior**

This has been working, and when trying to install it on a new laptop/M1 Pro chit, it appears to be failing.  Note I also have Rosetta installed and have used it to work around other library issues.  But it does not appear to be helping here.  

**Screenshots**

```
Python 3.8.9 (default, Oct 26 2021, 07:25:53) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/PycharmProjects/data_analysis/venv/lib/python3.8/site-packages/dash/__init__.py", line 5, in <module>
    from .dash import Dash, no_update  # noqa: F401,E402
```

**Comment by alexcjohnson** [comment]
Is there an error listed after the line you show? That doesn't look like the end of the traceback.

**Comment by JoeBarrett01** [comment]
I receive the same error in vscode

**Comment by alexcjohnson** [comment]
@JoeBarrett01 is there anything more to the traceback than what's shown above? It doesn't say what the error is.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
