### ISSUE TITLE
[Feature Request] DataTable -- Support displaying sequential row numbers derived after filtering

### ISSUE THREAD

**Issue by ned2** [plotly/dash#1966]
When navigating through a large DataTable, I want to be able to provide context to the user around which number row they are up to in order to assist with the task of reviewing multiple pages. 

The challenge is that when using a column of numeric row indexes attached to the original data source, these indexes will not be guaranteed to reflect the position in the current state of the client data table after filtering has been performed, as some rows could have been dropped. Here is a [Dash community forum post outlining this issue](https://community.plotly.com/t/continous-row-numbers-in-dash-datatable/58204).

One solution I could imagine would be DataTable offering a new param, eg a boolean `show_row_numbers`, which would add a derived column with the row numbers for the current state of the data.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
