### ISSUE TITLE
Ability to launch a dash app with it's source code

### ISSUE THREAD

**Issue by cpsievert** [plotly/dash#197]
Similar to [`shiny::runApp()`](https://www.rdocumentation.org/packages/shiny/versions/1.0.5/topics/runApp)'s `display.mode`. Note how when code re-executes, it is highlighted. It seems as though the relevant layout/ui "components" are not highlighted, but that seems like it would be nice feature as well

![shiny-code](https://user-images.githubusercontent.com/1365941/34887906-cf790368-f78d-11e7-9245-699d55346299.gif)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
