### ISSUE TITLE
lodash vulnerabilities, need version bump 

### ISSUE THREAD

**Issue by lrepno** [plotly/dash#1982]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Hello! I was able to find some lodash related vulnerabilities in my dashboard created on top of the dash. I am not using any nodejs libraries or any other dependencies, so I would assume that the version of lodash has to be bumped.

-  replace the result of `pip list | grep dash` below
```
dash                      2.3.0
dash-bootstrap-components 1.0.3
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
```

**Describe the bug**

**lodash version 4.17.4 has 7 vulnerabilities**
Versions of lodash lower than 4.17.12 are vulnerable to Prototype Pollution. The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.
Fixed in: 4.17.12 >2 years ago
[CVE-2019-10744](https://nvd.nist.gov/vuln/detail/CVE-2019-10744)

Lodash versions prior to 4.17.21 are vulnerable to Command Injection via the template function.
Fixed in: 4.17.21 >10 months ago
[CVE-2021-23337](https://nvd.nist.gov/vuln/detail/CVE-2021-23337)

Prototype pollution attack when using _.zipObjectDeep in lodash before 4.17.20.
Fixed in: 4.17.20 >1 year ago
[CVE-2020-8203](https://nvd.nist.gov/vuln/detail/CVE-2020-8203)

to be continued...

**Expected behavior**

Can you please provide some guidance how to bump the version. Is there any specific reason why it not happened yet? Should we expect this to be considered in a next release?

*

**Comment by alexcjohnson** [comment]
I see `lodash@4.17.15` used in `dash-core-components` via `react-dates@21.8.0` and `styled-jsx@3.4.7`, and I see it included via various dev deps in all the sub-packages of dash. But I don't see anything older than `4.17.15`, where are you seeing `4.17.4`?

We do generally try to keep these dependencies up-to-date, but dev deps are less of a concern because they aren't included in the bundles we ship, only in the developer tooling or test frameworks. I seem to recall trying to upgrade `styled-jsx` and giving up after running into some sort of problem, but that was probably part of an "upgrade every package" effort so I didn't have time to look into detail on the ones that failed. And `react-dates` and others that generate DOM elements we'll want to be careful about backward compatibility, in case they change structure or class names or the like, that Dash users may depend on via their own CSS. If you'd like to take a shot at making a PR to upgrade either or both of those, we'd be happy to support you and help with any roadblocks you encounter!

**Comment by lrepno** [comment]
Hi @alexcjohnson thanks for your response! 

I have tried replacing all dependencies on package-lock.json files to be 4.17.21 but it looks like there are sub dependencies (e.g. `minipass-sized-1.0.3` has its own dependency on lodash including 4.17.4 (for babel-core and some other babel tools) and 4.17.15 for its own) are not being updated. 

And even if I do `npm list lodash` I cannot see these subdependencies in a list (for all packages including dcc, dash-html-components and dash-table):
```bash
dash@ /Users/LRepno/lrepno/dash
└─┬ lerna@4.0.0
  ├─┬ @lerna/clean@4.0.0
  │ └─┬ @lerna/prompt@4.0.0
  │   └─┬ inquirer@7.3.3
  │     └── lodash@4.17.21 deduped
  ├─┬ @lerna/create@4.0.0
  │ └─┬ whatwg-url@8.7.0
  │   └── lodash@4.17.21
  └─┬ @lerna/version@4.0.0
    └─┬ @lerna/conventional-commits@4.0.0
      └─┬ conventional-changelog-core@4.2.3
        ├─┬ conventional-changelog-writer@5.0.0
        │ └── lodash@4.17.21 deduped
        ├─┬ conventional-commits-parser@3.2.1
        │ └── lodash@4.17.21 deduped
        ├─┬ git-raw-commits@2.0.10
        │ └── lodash@4.17.21 deduped
        └── lodash@4.17.21 deduped
```

I have also tried using overrides statement in package.json file but it had no effect:
```json
"overrides": {
    "lodash": "4.17.21"
  }
```

Even though 4.17.21 works fine for my dashboard and I didn't get any kind of difficulties or exceptions, I gave up approach of building dash locally. 

I don't have much experience in nodejs and node package manager, is there any other ways to override version for all dependency tree?

**Comment by alexcjohnson** [comment]
Thanks for investigating @lrepno!

It's generally dangerous to override a subdependency version; there's a reason for the version spec, even it that reason is no longer valid. If the latest version of a direct dependency requires a vulnerable subdependency, the best thing to do is try to contribute a fix to that direct dependency and then when a new version is published there, use that version here.

But I still don't understand where you're seeing the packages of concern, can you say more? If `npm ls` doesn't show `4.17.4`, and `package-lock.json` matches what I see in `npm ls`, where DO you see this? I don't see the `minipass-sized` package either, where do you see that?

**Comment by lrepno** [comment]
Thanks @alexcjohnson 

It's hard for me to understand how actually Twistlock works and how dependencies are analysed, but it still insists that `4.17.4` is still there.
After ```npm i``` global search for "lodash": "4.17.4" is showing following results:

File **components/dash-table/node_modules/element-resize-detector/package.json**
```
{
  "name": "element-resize-detector",
  "version": "1.2.4",
  "description": "Resize event emitter for elements.",
  "homepage": "https://github.com/wnr/element-resize-detector",
  "repository": {
    "type": "git",
    "url": "git://github.com/wnr/element-resize-detector.git"
  },
  "main": "src/element-resize-detector.js",
  "private": false,
  "license": "MIT",
  "dependencies": {
    "batch-processor": "1.0.0"
  },
  "devDependencies": {
    "grunt": "1.0.1",
    "grunt-banner": "0.6.0",
    "grunt-browserify": "5.2.0",
    "grunt-contrib-jshint": "1.1.0",
    "grunt-contrib-uglify": "2.3.0",
    "grunt-karma": "2.0.0",
    "jasmine-core": "2.9.0",
    "jquery": "3.1.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-firefox-launcher": "1.1.0",
    "karma-jasmine": "1.1.1",
    "karma-safari-launcher": "1.0.0",
    "load-grunt-tasks": "3.5.2",
    "lodash": "4.17.4"
  },
  "scripts": {
    "build": "grunt build",
    "dist": "grunt dist",
    "test": "grunt test",
    "test-ci": "grunt ci"
  }
}
```

File **components/dash-core-components/node_modules/babel-runtime/package-lock.json**
```
{
  "name": "babel-runtime",
  "version": "6.23.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
...
"babel-template": {
      "version": "6.25.0",
      "resolved": "https://registry.npmjs.org/babel-template/-/babel-template-6.25.0.tgz",
      "integrity": "sha1-ZlJBFmt8KqTGGdceGSlpVSsQwHE=",
      "dev": true,
      "requires": {
        "babel-runtime": "6.25.0",
        "babel-traverse": "6.25.0",
        "babel-types": "6.25.0",
        "babylon": "6.18.0",
        "lodash": "4.17.4"
      }
    },
"babel-traverse": {
      "version": "6.25.0",
      "resolved": "https://registry.npmjs.org/babel-traverse/-/babel-traverse-6.25.0.tgz",
      "integrity": "sha1-IldJfi/NGbie3BPEyROB+VEklvE=",
      "dev": true,
      "requires": {
        "babel-code-frame": "6.22.0",
        "babel-messages": "6.23.0",
        "babel-runtime": "6.25.0",
        "babel-types": "6.25.0",
        "babylon": "6.18.0",
        "debug": "2.6.8",
        "globals": "9.18.0",
        "invariant": "2.2.2",
        "lodash": "4.17.4"
      }
    },
"babel-types": {
      "version": "6.25.0",
      "resolved": "https://registry.npmjs.org/babel-types/-/babel-types-6.25.0.tgz",
      "integrity": "sha1-cK+ySNVmDl0Y+BHZHIMDtUE0oY4=",
      "dev": true,
      "requires": {
        "babel-runtime": "6.25.0",
        "esutils": "2.0.2",
        "lodash": "4.17.4",
        "to-fast-properties": "1.0.3"
      }
    }
...
```

File **components/dash-table/node_modules/babel-runtime/package-lock.json**
```
{
  "name": "babel-runtime",
  "version": "6.23.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
...
"babel-template": {
      "version": "6.25.0",
      "resolved": "https://registry.npmjs.org/babel-template/-/babel-template-6.25.0.tgz",
      "integrity": "sha1-ZlJBFmt8KqTGGdceGSlpVSsQwHE=",
      "dev": true,
      "requires": {
        "babel-runtime": "6.25.0",
        "babel-traverse": "6.25.0",
        "babel-types": "6.25.0",
        "babylon": "6.18.0",
        "lodash": "4.17.4"
      }
    },
"babel-traverse": {
      "version": "6.25.0",
      "resolved": "https://registry.npmjs.org/babel-traverse/-/babel-traverse-6.25.0.tgz",
      "integrity": "sha1-IldJfi/NGbie3BPEyROB+VEklvE=",
      "dev": true,
      "requires": {
        "babel-code-frame": "6.22.0",
        "babel-messages": "6.23.0",
        "babel-runtime": "6.25.0",
        "babel-types": "6.25.0",
        "babylon": "6.18.0",
        "debug": "2.6.8",
        "globals": "9.18.0",
        "invariant": "2.2.2",
        "lodash": "4.17.4"
      }
    },
"babel-types": {
      "version": "6.25.0",
      "resolved": "https://registry.npmjs.org/babel-types/-/babel-types-6.25.0.tgz",
      "integrity": "sha1-cK+ySNVmDl0Y+BHZHIMDtUE0oY4=",
      "dev": true,
      "requires": {
        "babel-runtime": "6.25.0",
        "esutils": "2.0.2",
        "lodash": "4.17.4",
        "to-fast-properties": "1.0.3"
      }
    }
...
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
