### ISSUE TITLE
[BUG] Installing dash breaks ability to run selenium / pylenium tests

### ISSUE THREAD

**Issue by rnestler** [plotly/dash#2014]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                 2.3.1
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
```

**Describe the bug**

After installing dash pylenium can't start the webdriver anymore:

```
$ pytests
...
$ poetry add dash==2.3.1
...
$ pytests
...
E           urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcd3eed0460>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

The full output is quite overwhelming since it triggers several errors in a cascade while trying to setup and tear down the test fixtures.

localhost:4444 is where the webdriver server should respond.

**Expected behavior**

That tests still work.

**Screenshots**

Repository to reproduce the error: https://github.com/rnestler/minimal-pylenium-dash-example

Full output of the failure: 
[output.txt](https://github.com/plotly/dash/files/8483128/output.txt)

**Comment by rnestler** [comment]
I debugged it a bit further: I can install every dependency of dash except dash itself and the tests still work! So something in the dash package itself must be the issue.

**Comment by rnestler** [comment]
OK the culprit seems to be the `dash/testing/plugin.py`. When I just remove the file with `rm /home/raphael/.cache/pypoetry/virtualenvs/minimal-pylenium-dash-example-0I1Y-mga-py3.10/lib/python3.10/site-packages/dash/testing/plugin.py` then the tests work again.

**Comment by rnestler** [comment]
Ah I can also disable it with `pytest -p no:dash`

**Comment by bmerry** [comment]
Is this maybe related to #1690?

**Comment by rnestler** [comment]
@bmerry Looks related to the test plugin as well, yes. I guess disabling it with `pytest -p no:dash` could work for you as well as a workaround.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
