### ISSUE TITLE
Feature Request : Functionality to hide empty leaves in tree map. 

### ISSUE THREAD

**Issue by kambliameya** [plotly/dash#2021]
Kindly add a functionality to hide empty leaves in tree map.
For example :
I have 5 categories with different depths belonging to 1 single product , i would ideally want to limit the drilling of tree map based on max level of that particular catergory. For example CATEGORY A has just 3 LEVELS vs CATEGORY D has 8 levels, so ideally i would want to limit the drillng of treemap for Catergory A limited to 3 levels instead of 8 with 5 blank levels (HIDE EMPTY LEAVES).

Is there any way to achieve this, or any support that i can expect in the future

**Comment by alexcjohnson** [comment]
FYI this question may be better suited to https://community.plotly.com/ but we can take a stab here: You're referring to plotly.py treemaps https://plotly.com/python/treemaps/ I presume? The treemap itself doesn't require all branches to reach the same depth, but there may be some methods of constructing a treemap that force a constant depth. Can you give a concrete example of your code and its results?

**Comment by kambliameya** [comment]
Error : Non-leaves rows are not permitted in the dataframe

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
