### ISSUE TITLE
[BUG] form labels do not work with pattern-matching callbacks

### ISSUE THREAD

**Issue by jeslinmx** [plotly/dash#2026]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                      2.3.1   
dash-bootstrap-components 1.1.0   
dash-core-components      2.0.0   
dash-html-components      2.0.0   
dash-table                5.0.0
```

**Describe the bug**

With the introduction of pattern-matching callbacks, IDs can now be dicts in addition to strings. However, this does not extend to the `htmlFor` attribute of html.Label (and possibly other HTML elements which rely upon IDs, but I can't think of any off hand). Currently, setting `htmlFor={"id": "id1"}` results in

```
Invalid argument `htmlFor` passed into Label.
Expected `string`.
Was supplied type `object`.
Value provided: 
{
  "id": "id1"
}
```

**Expected behavior**

A `<label>` element is created with `for="{"id": "id1"}"` (i.e. the dict, stringified). This is consistent with the behaviour of dict IDs, which results in a HTML element with a stringified dict for an ID.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
