### ISSUE TITLE
replace dcc.Dropdown with a smart search input form to handle 50k items which make UI slow

### ISSUE THREAD

**Issue by nibu147** [plotly/dash#2030]
Hello,
I wrote a Dash UI where I've included a dash-core-components Dropdown with more than 50k items.

The issue with this solution is that the browser get stuck for 5~10 seconds to render a Dropdown with so many fields.

Therefore I want to switch to a search box with no preloaded items. Nice to have, the search box or dropdown should auto-populate with matching elements after that the user has typed N characters in the form.

Is possible to do this with plotly dash or extra components?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
