### ISSUE TITLE
Stub file not found for plotly and dash [BUG]

### ISSUE THREAD

**Issue by chiboreache** [plotly/dash#2031]
**Describe your context**

```
dash                 2.3.1
aur/python-plotly 5.7.0-1 (+36 4.72) (Installed)
arch4edu/visual-studio-code-bin 1.66.2-1 (71.9 MiB 281.1 MiB) (Installed)
```

    - Arch Linux - everything is bleeding edge.

**Describe the bug**

**Screenshots**

![2022-05-02x09:46:41](https://user-images.githubusercontent.com/16459251/166195593-70a0ea1f-8278-45f3-87c8-70569d8ab477.jpg)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
