### ISSUE TITLE
Cannot replicate documentation examples

### ISSUE THREAD

**Issue by anfoss** [plotly/dash#2040]
**Describe your context**
I just installed dash and I am trying to replicate the documentation examples. However all examples using callbacks fail.
 [this example](https://plotly.com/python/line-charts/) raise this import error.

`ImportError: cannot import name 'Input' from 'dash' (/opt/anaconda3/lib/python3.8/site-packages/dash/__init__.py)`

This is the code I used

```
from dash import Dash, dcc, html, Input, Output
import plotly.express as px

app = Dash(__name__)


app.layout = html.Div([
    html.H4('Life expentancy progression of countries per continents'),
    dcc.Graph(id="graph"),
    dcc.Checklist(
        id="checklist",
        options=["Asia", "Europe", "Africa","Americas","Oceania"],
        value=["Americas", "Oceania"],
        inline=True
    ),
])


@app.callback(
    Output("graph", "figure"), 
    Input("checklist", "value"))
def update_line_chart(continents):
    df = px.data.gapminder() # replace with your own data source
    mask = df.continent.isin(continents)
    fig = px.line(df[mask], 
        x="year", y="lifeExp", color='country')
    return fig

app.run_server(debug=True)`

```

-   `pip list | grep dash`
```
dash                          2.3.1
dash-bootstrap-components     1.1.0
dash-core-components          2.0.0
dash-extensions               0.1.0
dash-html-components          2.0.0
dash-renderer                 1.1.2
dash-table                    5.0.0
```

### EDIT

If I import Input and Output from dash.dependencies it compiles without error but raises this in the plot.

'Invalid argument `options[0]` passed into Checklist with ID "checklist".
Expected `object`.
Was supplied type `string`.'

**Comment by nickmelnikov82** [comment]
It looks like the environment you are running the example in is still using dash version `1.2.0`.
What is the output of the command `cat /opt/anaconda3/lib/python3.8/site-packages/dash/version.py`?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
