### ISSUE TITLE
PASTE ISSUE IN DASH TABLE

### ISSUE THREAD

**Issue by ghost** [plotly/dash#2055]
Hi,

I have an issue with a dash data table where I have the first few columns as uneditable and the last ones as editable dropdowns, when I copy a drop-down value and paste it works but when I change a dropdown and copy it doesn’t update the clipboard and paste the old value I copied.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
