### ISSUE TITLE
Being able to run dash applications from R markdown files (.Rmd)

### ISSUE THREAD

**Issue by eleonore-schneeg** [plotly/dash#2071]
Hi! 

I was wondering if you were planning to enable the rendering dash apps straight from an R markdown documents?
This option is currently available for shiny apps, by specifying 'runtime: shiny' in the yaml header and then running the markdown document from R (rmarkdown::run)

Thanks!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
