### ISSUE TITLE
[BUG]px.scatter_mapbox, map shows but hover is not working

### ISSUE THREAD

**Issue by ghost** [plotly/dash#2074]
px.set_mapbox_access_token(AccessToken)
fig = px.scatter_mapbox(data_frame=dff29, lat="latid", lon="long", center={"lat": 60, "lon": 10},
                        width=800, height=800, zoom=5, hover_name="Name", hover_data=["Name", "latid", "long"],
                        color_discrete_sequence=["fuchsia"],
                        title='Målepunkter veiobjekter 2021'
                        )
#fig.update_layout(mapbox_style="dark", mapbox_accesstoken=AccessToken)
fig.update_layout(mapbox_style="open-street-map")

fig.show()

Any idea??????

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
