### ISSUE TITLE
Possible feature request

### ISSUE THREAD

**Issue by rashedbt10** [plotly/dash#2076]
Hi,

I am trying to plot an azimuth and elevation graph, and so I am trying to customize my radial axis. Basically I want the units/numbers on the radial axis to ascend inward. I’ve attached a picture for more clarification. If anyone has a solution, that would be much appreciated. If this is not possible, is there any possibility that this feature can be added? 

Thanks a lot in advance !
![image](https://user-images.githubusercontent.com/76122610/171515054-370aa404-e43d-454e-b39a-cb5f4c8f2ff3.png)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by rashedbt10** [comment]
Hi,

Is there a way to delete the issue altogether?

Thanks
Rashed

**Comment by gvwilson** [comment]
@rashedbt10 not that I know of - but now that it's closed it shouldn't show up again
