### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EldhosePoulose** [plotly/dash#2103]
**Describe your context**

if __name__ == "__main__":
    app.run_server(debug=False)

this run into.... Internal Server Error... and in Jupyter Notebook I see the error as provided  below.

from plotly.io.json import to_json_plotly
ModuleNotFoundError: No module named 'plotly.io.json'

```
dash                               2.5.1
dash-core-components               2.0.0
dash-html-components               2.0.0
dash-table                         5.0.0
```

**Expected behavior**

The dashboard.

**Comment by EldhosePoulose** [comment]
! pip install dash   
! pip install dash-html-components                                         
! pip install dash-core-components                                     
! pip install plotly

**Comment by alexcjohnson** [comment]
Glad you solved it @EldhosePoulose - but I'm puzzled how you ended up with `dash` installed without `plotly`, since it should be automatically installed [as a requirement](https://github.com/plotly/dash/blob/ac7b37d0a40ffd7e48780e3c84f645c0554eb26f/requires-install.txt#L3) of `dash`.

Note that `dash-core-components`, `dash-html-components`, and `dash-table` should no longer be used or explicitly installed - though we still install them automatically as stub packages for backward compatibility.
