### ISSUE TITLE
How can I  transfer singnal between multiple pages

### ISSUE THREAD

**Issue by lihang598602** [plotly/dash#2115]
I want to make an app containing a chain of pages with ordered logical associations. That is,  output of page1 will be passed to page2. But when I finished data processing in page1 and then click page2, the data in page2(which was referred in page1) was in NoneType(no signal received). At this moment, when I come back to page1, it have been freshed, But I expect it to be cached. 

Could you please offer me a way to save the page1 status and transfer its output to page2?

**Comment by jbmulligan** [comment]
I am trying to do something that may be similar:  I have one page where the user makes a selection, which then redirects to another page that has the selected value as a variable path parameter.  That is fine for rendering the second page initially, but I want to be able to access the value of the variable path parameter in the callbacks, and the examples in the documentation don't show that.  I tried to get the information from flask.request.path, but the value returned is _dash-update-component, not the path that is displayed in the navigation bar.  Originally I had cached the variable value in a global, but I belatedly realized that this would break when more than one user is accessing the site at the same time.

So my approach to lihang's issue was to pass the data in the URL, but of course that only works when the "data" is a short string.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
