### ISSUE TITLE
[Feature Request] Allow circular (infinite!) callbacks

### ISSUE THREAD

**Issue by nirvana-msu** [plotly/dash#2139]
Hi, I have a feature request:  allow circular callbacks causing an infinite loop. 

Dash is going out of its way to detect and reject circular callback cycles (or allow cycle of 1 callback, but such that it gets prunned and still does not cause infinite loop) - which is what most users would want, but I have the exact opposite usecase.

You could argue my use-case is a little hack-ish, but I've found it to be a great way to build truly real-time apps in Dash. Basically my real-time data is made available on clientside via some other means (say, websocket), outside of Dash renderer. I then want to extend a chart with that data as soon as it's available. Now that Dash clientside callbacks support promises, what I could do (if infinite loop was allowed) was just to have a clientside callback that creates a promise, which I'd resolve with my data (either immediately or later, whenever data becomes available). As soon as that promise is resolved and chart is updated, I need a new promise (so I could feed new data to it) and so on. I'd like the same callback to trigger in a circular infinite fashion.

I understand this is contrary to all the effort of preventing infinite callback chains so far - but why not allow it with an option? In my case I only need a single callback firing infinitely  (I do not need chains of multiple callbacks).

Is there any workaround / hack I could use to bypass the pruning perfomed in #1525?

**Comment by emilhe** [comment]
As a workaround, you could try the cyclebreaker transform,

https://www.dash-extensions.com/pages/transforms/cycle-breaker-transform

**Comment by nirvana-msu** [comment]
@emilhe Thanks! I don't need the transform itself, but the `CycleBreaker` component is exactly the workaround I've been looking for!  Was previously using [react-trigger-change](https://github.com/vitalyq/react-trigger-change) to fire a change event on an input, but this is now much cleaner with  `CycleBreaker`.

Separately, would probably still be nice to have an official opt-in flag to allow infinite loops.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
