### ISSUE TITLE
[BUG] ios viewport not fitting.

### ISSUE THREAD

**Issue by turners1110** [plotly/dash#2144]
**Environment:**
dash==2.5.1 and 2.6.0
dash-bootstrap-components==1.2.0
dash-table==5.0.0

**Brower**
Safari and Chrome on IOS

**Describe the bug**

Prior to upgrading Dash (I was using 2.4.0 prior), my app displayed perfectly as an IOS website. Since upgrading, the scaling is off, whereas the website appears too zoomed in and the Boostrap components don't fit as before. It is as if the height of the components remained the same, but the width has gotten considerable tighter to accommodate to the screen size. 

The issue presents with identical code, just updated the version of Dash. Note, I have no issue on desktop or even my iPad. I was able to rollback to an earlier version of Dash to solve in the short-term, but I upgraded to incorporate the newly released pages feature

**Comment by AnnMarieW** [comment]
Hi @turners1110 
The default for the meta tags was updated in dash 2.5.0 to optimize page layout in mobile browsers.

You can find more information about this and how to override the default in the docs:
https://dash.plotly.com/external-resources#customizing-meta-tags

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
