### ISSUE TITLE
[Feature Request] Define your own expression query language for datatable backend filtering

### ISSUE THREAD

**Issue by prokie** [plotly/dash#2150]
I want to be able to define my own query language for backend datatable filtering.  In the [documentation](https://dash.plotly.com/datatable/callbacks#backend-paging-with-filtering) it is supposedly being worked on. But I can not find any issue for this feature.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
