### ISSUE TITLE
[BUG] Tests deadlock due to ThreadedRunner's KillerThread

### ISSUE THREAD

**Issue by rymndhng** [plotly/dash#2165]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                 2.5.1
dash-core-components 2.0.0
dash-html-components 2.0.0
```

**Describe the bug**

Some of our dash tests are timing out/deadlocking since upgrading to 2.5.1 from 2.2.0. 

We are using the ThreadedRunner. From investigation, the KillerThread that executes between tests is killing threads that are created during the test execution. 

This is causing timeout/deadlocks in our dash callback code when a second test in a suite runs.

**Expected behavior**

Retain old behavior -- only kill the server thread, or alternatively, allow users to choose the thread killer policy.

**Comment by alexcjohnson** [comment]
@rymndhng are you saying your tests make additional threads that need to stay active across multiple tests? Can you give us a simplified example of a situation that worked previously and now fails?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
