### ISSUE TITLE
datatable style_data_conditional based on duplicate column values

### ISSUE THREAD

**Issue by SterlingButters** [plotly/dash#2189]
I've been racking my brain trying to figure out how to implement this natively but have decided it can't be done with the current `filter_query` framework. The feature request is fairly simple (though execution may not be) - let me know if more info is needed. Thanks!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
