### ISSUE TITLE
[BUG] scatter_mapbox centering fails when fully zoomed out

### ISSUE THREAD

**Issue by Martynas99** [plotly/dash#2192]
**Describe your context**
dash==2.3.1
dash-bootstrap-components==1.1.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0

**Describe the bug**
When the map is fully zoomed out (some locations repeat on it), passing go.layout.mapbox.Center(lat, lon) fails to center on correct latitude (but centers on correct longitude).

**Expected behavior**
For any zoom level, map should center on correct coordinates.

**Screenshots**
[Screencast from 12-08-22 10:23:35.webm](https://user-images.githubusercontent.com/44123619/184325596-941ef8ba-9095-477d-a292-3078be39a843.webm)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
