### ISSUE TITLE
[Feature Request] Include ondrop and ondragover to html.Div

### ISSUE THREAD

**Issue by jjairitech** [plotly/dash#2203]
Greeting,

I just found today that html.Div, although has draggable argument, but ondrop and ondragover are missing.

I would like to implement a feature when I drag a child div from a parent div to another parent div, it will move the child div there. Similar to the below example.

https://www.w3schools.com/html/html5_draganddrop.asp

I tried to add function that update the parent div with a list of child div, but since there are no ondrop argument, I couldn't.
Also no ondragover to put PreventDefault in.

I already know about dash-draggable library, but that seems to only move things within draggable grid, but I don't see anything equivalent to ondrop event.

If you could suggest any dash feature to use for drag and drop event, that would be really helpful.

Thank you.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
