### ISSUE TITLE
dash-testing, mocking callback context, keys and multiple context data

### ISSUE THREAD

**Issue by martinschorb** [plotly/dash#2205]
Dear all,

I have a callback with a dynamic set of inputs.
I thus use `ctx.inputs` or `ctx.inputs_list` to capture which elements are available.

In the `dash-testing` documentation, it is well explained how the `triggered` context can be generated using `context_value.set`.

However, I run into the following issue:

It is not clear to me how the dictionary keys provided to  `context_value.set` map to those of `dash.callback_context`.

It seems that what is shown in the example, the key `triggered_inputs` affects all of the `ctx.triggered`, `ctx.triggered_prop_ids`, `ctx.triggered_id` attributes.

- How can I set `ctx.inputs` and `ctx.inputs_list` and their equivalents for `states` accordingly using `context_value.set`?
- Is this currently possible?
- In addition, is it possible to provide multiple attributes at once to `context_value.set` to for example set both `triggered` and `states_list` attributes?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
