### ISSUE TITLE
[BUG] multi_page layout (use_pages=True) won't recognize the pages if they are compiled .pyc files.

### ISSUE THREAD

**Issue by TheBubblePopped** [plotly/dash#2234]
As mention in the title, it looks like dash only bats an eye for .py files. Am i doing something wrong or are .pyc files just not supported "yet"?

**Comment by alexcjohnson** [comment]
Right, currently we only look for `.py` files, but with the usual caveats about requiring a consistent Python version we should be able to expand this to accept `.pyc` files. Thanks for bringing this up!

If you're interested in addressing this, the relevant code is here and below:

https://github.com/plotly/dash/blob/0df861f212cbd4a55dcbf77f64c1a1bffedb0bc7/dash/dash.py#L1976

We'll need to ensure that if both `.py` and `.pyc` of the same file are present we only import one (`.py` would be safest).

**Comment by AnnMarieW** [comment]
@TheBubblePopped 
Can you say more about your use-case?  Are you just trying to make the app load faster?  Or are you doing a .pyc only distribution?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
