### ISSUE TITLE
[BUG] Error using background callbacks with Dash Pages

### ISSUE THREAD

**Issue by weisenje** [plotly/dash#2239]
Context:
```
dash                      2.6.1
dash-bootstrap-components 1.2.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
```

I have a working Dash application that is using background callbacks and Dash Pages.

The app is instantiated like this:
```
cache = diskcache.Cache(CACHE_PATH)
background_callback_manager = DiskcacheManager(cache)
app = Dash(__name__, background_callback_manager=background_callback_manager, use_pages=True)
```

A given page is registered like this:
```
dash.register_page(__name__, name='Store Fruit', title="Fruit", order=1)
```

The given page has callbacks like this:
```
@dash.callback(
    output=Output("fruit", "data"),
    inputs=Input("my-button", "n_clicks"),  # callback triggered by button click
    background=True,
    running=[
        (Output("my-button", "disabled"), True, False), # disable button while running
    ],
    prevent_initial_call=True
)
def store_fruit(button_clicks):
    time.sleep(10)
    return “pineapple” 
```

**_When I run in one environment (Linux), everything works as expected._**

**_However, when I run in another environment (Windows), I get this error when clicking the button:_** 
```
dash.register_page() can’t be called within a callback as it updates dash.page_registry, which is a global variable.
             For more details, see https://dash.plotly.com/sharing-data-between-callbacks#why-global-variables-will-break-your-app
```
I noticed that when I comment out `background=True`, the error above does not appear.

Appreciate any help!  Thanks

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
