### ISSUE TITLE
[Feature Request] Allow `fixed_columns` from the right hand side

### ISSUE THREAD

**Issue by gofford** [plotly/dash#2248]
I haven't been able to find this mentioned in the forums.

**Is your feature request related to a problem? Please describe.**
`fixed_columns` allows users to fix columns from the left. E.g., `fixed_columns={'headers': True, 'data': 2}` will fix the cells and header associated with the first 2 columns. As far as I can tell there is no native way of fixing columns to the right-hand side; i.e., if I want to fix the first column and the last column in a data in my table -- I cannot.

Is there a way to do this that I have perhaps missed, or via CSS?

**Describe the solution you'd like**
It would be really useful to be able to fix columns from either the left, or the right. This would allow, for example, a fixed ID to be on the left hand side of the table and a per-row button on the right hand side, with the data scrolling in between. An example of what I mean can be found here, only in the R Shiny ecosystem: https://glin.github.io/reactable/articles/examples.html#sticky-columns

**Describe alternatives you've considered**
I have tried overriding the CSS but it is quite complex.

**Comment by alexcjohnson** [comment]
Interesting idea @gofford! I'm not aware of any way this could be achieved today, in CSS or otherwise. We construct `dash_table` fixed as two html `<table>` elements, one for the fixed columns on the left, another for the scrolling columns on the right. I think to make fixed columns on the right we'd need a third `<table>` element - and if we extend this concept to also allow a fixed row at the end we're up to in principle 9 total tables... this isn't to say we shouldn't do this, not at all. Just that it would need to be new code rather than something you could achieve today by finding the right tricks.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
