### ISSUE TITLE
[Feature Request] Long Polling / Web Sockets for background / long callbacks

### ISSUE THREAD

**Issue by ArtsiomAntropau** [plotly/dash#2250]
**Is your feature request related to a problem? Please describe.**
Too many requests, when we're using background/long callbacks with simple pooling, may break the page due to low latency between requests and page overload. 

**Describe the solution you'd like**
What about using [Long Polling](https://javascript.info/long-polling) (dash-like way), when we will send to the FE only different events supporting reconnections or [WebSocket](https://javascript.info/websocket) (modern way)? 

**Alternatives**
We can research [Server Sent Events](https://javascript.info/server-sent-events)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
