### ISSUE TITLE
 size in pixel of a html.Div

### ISSUE THREAD

**Issue by davidpasquale** [plotly/dash#2258]
Hi,
for some reason I need to know the size in pixel of a container.
Is there any way to get the actual size of a html.Div container with a clientside or serverside callback?

I can see those props in the browser inspection but in dash I cannot acces to them.

Can someone create a simple example?

Here a  JS example that works
[https://stackoverflow.com/questions/3839227/how-to-get-height-of-div-in-px-dimension](https://stackoverflow.com/questions/3839227/how-to-get-height-of-div-in-px-dimension)

Thank you so much!!

**Comment by alexcjohnson** [comment]
This kind of question is best addressed to https://community.plotly.com/ - but yes, it should be possible in a clientside callback assuming the div has a unique ID - you can pass that ID to the callback as `Input` or `State` then find the DOM element as `var myDiv = document.getElementById(div_id)` - then continue with any of the solutions from that SO question (not the jQuery answers though, unless you separately load it)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
