### ISSUE TITLE
[Feature Request] Offer encoding options for the dash dataTable export

### ISSUE THREAD

**Issue by halemade** [plotly/dash#2259]
**Is your feature request related to a problem? Please describe.**
A user is frustrated when they cannot specify the type of encoding used in dataTable exports. Currently you can select a download format from one of 'csv', 'xlsx' or 'none', and this user would like support for cp932 encoding because the default utf-8 doesn't offer support for Japanese characters in csv files.

**Describe the solution you'd like**
I would like to see the ability to select the type of encoding by passing an argument to the dataTable. Maybe something like export_format={"type":"csv","encoding":"cp32"}

**Describe alternatives you've considered**
Currently, we're passing the download data to a separate component for download.

**Comment by alexcjohnson** [comment]
> utf-8 doesn't offer support for Japanese characters in csv files.

Really? That's the first time I've heard utf-8 being unable to support ANYTHING that another encoding supports. Can you give an example? I wonder if we're just doing something wrong, that doesn't show up until you try it with Japanese characters?

**Comment by alexcjohnson** [comment]
Or is it just that the user has a pipeline where the next step assumes `cp932`, and the CSV format doesn't have a way to indicate otherwise?

**Comment by halemade** [comment]
Thanks for the questions, I'll check with the client!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
