### ISSUE TITLE
Register new pages during run-time

### ISSUE THREAD

**Issue by MLRadfys** [plotly/dash#2267]
Hi,

Iam trying to generate new dash pages (with layout) during runtime and populate a dropdown menu with these pages. 
Unfortunately, the pages are not registered.  Only when I stop my application and restart it, new pages appear in the dropdown.

I guess I have to update the page registry somehow and Iam wondering if this is possible?

Thanks in advance,

kind regards,

Michael

**Comment by ned2** [comment]
Under the hood, Dash Pages works by using a callback that targets a `dcc.Location` component in your app. As with all Dash callbacks, they need to be registered before you run the app. So, this constraint applies to Dash Pages as well. Registering a new page while the app is running is essentially like trying to modify a callback while the app is running, which is to say, it won't work.

Remember that while your layouts have to be registered before you start your app, they don't have to be statically defined upfront. If you make them a function, they can be dynamic, changing at request handling time.

Since this isn't a bug report or feature request, this would probably be better placed as a conversation in the Dash community forums, where lots of folks hang out helping each other out :)  https://community.plotly.com/c/python/25

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
