### ISSUE TITLE
[BUG] Scattermapbox throws a JS error when zoomed during selection mode

### ISSUE THREAD

**Issue by Coding-with-Adam** [plotly/dash#2280]
This bug was brought up by a community member in [this post](https://community.plotly.com/t/scattermapbox-throws-js-error-when-zoomed-in-during-selection-mode/69095?).

You can reproduce the error using [scattermapbox documentation page](https://plotly.com/python/scattermapbox/). When you click “Zoom In” button after clicking “Box Select”, you can see the error in devtool console. It also happens with “Zoom Out” or “Lasso Select”.

![scatter-gif](https://user-images.githubusercontent.com/32049495/197246214-852b6e18-e195-46cf-bc58-a74cba4c877c.gif)

**Comment by archmoj** [comment]
Addressed in [`plotly.js v2.16.2`](https://github.com/plotly/plotly.js/releases/tag/v2.16.2).

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
