### ISSUE TITLE
[BUG] High CPU usage when typing in text field and plotly graphs on screen

### ISSUE THREAD

**Issue by astrowonk** [plotly/dash#2297]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                              2.6.2
dash-bootstrap-components         1.2.1
dash-bootstrap-templates          1.0.4
dash-core-components              2.0.0
dash-dataframe-table              0.1.3
dash-extensions                   0.1.5
dash-html-components              2.0.0
dash-renderer                     1.9.0
dash-table                        5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Mac
    - Browser Safari

**Describe the bug**

High cpu usage when typing characters in a text field if there are plotly graphs on screen.

**Expected behavior**

Minimal CPU usage

**Screenshots**

![](https://aws1.discourse-cdn.com/business7/uploads/plot/original/3X/e/e/ee0be17af835f7cbdd9ae20a9b484dac42b8749a.jpeg)

** Simple example app

https://github.com/astrowonk/streamlit_lag_example/blob/main/dash_example.py

* Discussion

I tried to get some guidance via this [post on the community forum](https://community.plotly.com/t/high-cpu-usage-when-typing-in-text-fields-with-plotly-graphs-on-screen/68161) but did not get any feedback.

No callback is watching the TextArea. I can't think of any reason CPU usage should be high here. On older Macs/computers this creates a lot of input lag just typing.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
