### ISSUE TITLE
[Feature Request] Allow custom web store implementations for persistence

### ISSUE THREAD

**Issue by mger-hrt** [plotly/dash#2305]
Thanks so much for your interest in Dash!

Before posting an issue here, please check the Dash [community forum](https://community.plotly.com/c/dash) to see if the topic has already been discussed. The community forum is also great for implementation questions. When in doubt, please feel free to just post the issue here :)

**Is your feature request related to a problem? Please describe.**
Dash [persistence](http://dash.plotly.com/persistence) is great but it doesn't cover all cases. For instance, Dash doesn't offer url persistence (storing values in the url query string) or persistence in a file on disk. Ideally, Dash would not place any limitations on the `persistence_type` (currently, only `'memory'`, `'session'`, and `'local'` are supported), and allow users to implement their own web stores, e.g., for url persistence.

**Describe the solution you'd like**
It would be great if Dash would allow users to implement their own web store backends for persistence, creating new `persistence_type`s. Looking at code of the Dash renderer, one way to achieve this would be to relax [the requirement](https://github.com/plotly/dash/blob/7afb2edbccff0af98f87df083dd6fbedece10463/dash/dash-renderer/src/persistence.js#L258) that the given `persistence_type` is present in the [`backEnds` object](https://github.com/plotly/dash/blob/7afb2edbccff0af98f87df083dd6fbedece10463/dash/dash-renderer/src/persistence.js#L216), and see if a web store object with `persistence_type` exists on the `window` object. This change would be small and easy to make. Another option could be to explicitly allow users to register custom web stores.

If there is support for the idea, then I'd be happy to put a PR together for review.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by alexcjohnson** [comment]
@mger-hrt this is an interesting idea! I feel like query-string persistence would be very useful, enough to warrant adding to dash core, also because we may need to tread carefully to make it work with `dcc.Location`.

Are there reasons different users would need different url persistence implementations? And file-on-disk persistence, how would that work? Is there a way that could be done directly from the browser or would it need to go through the server? I’m just trying to figure out to what extent we can address the use cases you’ve identified just by extending the built-in feature, or if we really need to make it so users can add their own.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
