### ISSUE TITLE
Wrapping text in a editable datatable

### ISSUE THREAD

**Issue by joseberlines** [plotly/dash#2350]
I am looking for the possibility of using the plotly editable datatable as it would be a excel table, i.e. the user can a) edit cells and enter New data b) select a range of cells and c) when a text does not fit the witdth of a column the row should accomodate the text by wrapping the text into several lines.

I found these examples useful:
https://dash.plotly.com/datatable/editable

But the wrapping text feature is not there. When editing any of those cell values if you add a text that does not fit the column will get wider but no multi-line text in cell looks to be possible.

Is it then at all possible with plotly?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
