### ISSUE TITLE
How to access an Iframe from an external source without uncaught DOMexception?

### ISSUE THREAD

**Issue by matthewyangcs** [plotly/dash#2354]
I have some other website I own and I want to embed html from that website as Iframes. I want to access some properties of the actual element (such as scroll height) to adjust the Iframe in dash.

But I get a `Uncaught DOMException: Blocked a frame with origin "http://localhost:8050" from accessing a cross-origin frame.`, which is to be expected. In flask there's a way to whitelist other sites, is there a way to do this in Dash?

thank you!

**Comment by ned2** [comment]
As Dash is based on top of Flask, if what you want to do can be done in Flask, then there's a good chance it can be done in Dash.

As this isn't an issue or feature request, a better place to ask this question is the [Dash Community Forums](https://community.plotly.com/c/python/25). I'd suggest posting your question there along with a link to examples of the Flask functionality you know works.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
