### ISSUE TITLE
[BUG] Background callback returns 502

### ISSUE THREAD

**Issue by ArtsiomAntropau** [plotly/dash#2372]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
I have some high CPU/RAM efficient workflow that handling by celery and in the same time I have background callback that triggering this workflow and partially doing some CPU-related calculations too. 

-  replace the result of `pip list | grep dash` below
```
│ dash                 │ 2.7.0       │                                            │
│ dash-dv2             │ 1.0.95      │                                            │
│ fef-dash             │ 4.4.4       │                                            │
│ dash-table           │ 5.0.0       │                                            │
│ dash-core-components │ 2.0.0       │                                            │
│ dash-html-components │ 2.0.0       │                                            │
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: macOS
    - Browser Chrome
    - Version 108

**Describe the bug**

When I'm starting only one this loading in parallel – all is ok, when more than three (including) – I'm receiving 502 error:
The issue reproducing regularly, not one-time issue and not fixing by restarting containers (we're using k8s: 2 pods of dash app, 2 Redis instances, 2 scalable pods of nginx-ingress). 

```
HTTP/1.1 502 Bad Gateway
Date: Thu, 29 Dec 2022 03:15:18 GMT
Content-Type: text/html
Content-Length: 552
Connection: keep-alive
Content-Security-Policy: <HIDDEN>
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
```

**Expected behavior**

Not receiving 502 or with described output. 

**Screenshots**

<img width="666" alt="image" src="https://user-images.githubusercontent.com/82237255/209899363-09cf4ec7-6d24-491c-9266-434c9402533e.png">

**Comment by nickmelnikov82** [comment]
Hmm, how is your load balancer working?

What does it say for the routing of these, are they going to the same backend?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
