### ISSUE TITLE
[Feature Request] Long Polling instead of Short Polling

### ISSUE THREAD

**Issue by ArtsiomAntropau** [plotly/dash#2373]
**Is your feature request related to a problem? Please describe.**
Sometimes with some values for background callback interval (less than 50 ms for an example), user may have some issues in browser connected with high amount of requests to the BE. 

**Describe the solution you'd like**
Implement Long Polling instead of Short Polling, or provide clear explanation of why Short Polling approach is used now.  

**Describe alternatives you've considered**
Web Sockets may be investigated too as an alternative.

**Comment by T4rk1n** [comment]
Long polling alone wouldn't allow for progress updates which is part of the background callback API so it use periodic polling with tasks id to retrieve the progress or callback result.

**Comment by T4rk1n** [comment]
I think long polling currently with sync flask would freeze a thread while it wait for the result/progress, limiting the amount of concurrent users you can have in a production setting.

When we drop support for Python 3.6, we could add flask[async] for async callbacks and then we could await the result/progress without blocking.

When we did the background callback refactor we also looked at an SSE implementation but we found that 5 connections maximum per browser was too limiting.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
