### ISSUE TITLE
[BUG]dcc.Store in main layout, ctx.triggered_id and prevent_initial_call are abnormal

### ISSUE THREAD

**Issue by xiongyifan** [plotly/dash#2421]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                 2.7.1
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-renderer        not install
dash-table           5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: [e.g. iOS] win10
    - Browser [e.g. chrome, safari] edge
    - Version [e.g. 22] 109.0.1518.78

**Describe the bug**

if dcc.Store in main layout, 
1. when reload page ctx.triggered_id is not None.
2. when prevent_initial_call = True, and reload page, the callback is Executed.

**Expected behavior**

if dcc.Store in main layout, 
1. when reload page ctx.triggered_id is None.
2. when prevent_initial_call = True, and reload page, the callback is not Executed.

**Screenshots**

https://github.com/AnnMarieW/dash-multi-page-app-demos/tree/main/multi_page_store

this project can reproduce the bug.

```python
# the code location: multi_page_store/pages/graph.py
@callback(
    Output("store", "data"),
    Input("year", "value"),
    prevent_initial_call=True  # !!! not work
)
def get_data(year):
    print(ctx.triggered_id)  #  !!! when reload page ctx.triggered_id is not None.
    dff = df.query(f"year=={year}")
    store = {
        "data": dff.to_dict("records"),
        "columns": [{"name": i, "id": i} for i in dff.columns],
    }
    return store
```

**Comment by nickmelnikov82** [comment]
One way to solve this problem is to add a check on the first call using dash.callback_context in your callback. You can change your get_data code to the following method:

```
@callback(
    Output("store", "data"),
    Input("year", "value"),
    prevent_initial_call=True
)
def get_data(year):
    ctx = CallbackContext()
    if not ctx.triggered:
        raise dash.exceptions.PreventUpdate
    triggered_id = ctx.triggered[0]['prop_id'].split('.')[0]
    if triggered_id == 'year':
        dff = df.query(f "year=={year}")
        store = {
            "data": dff.to_dict("records"),
            "columns": [{"name": i, "id": i} for i in dff.columns]
        }
        return store
    else:
        raise dash.exceptions.PreventUpdate
```

In this code, we use dash.callback_context to get the callback context. If ctx.triggered is empty, we call dash.exceptions.PreventUpdate to prevent the callback from being executed. Check triggered_id to make sure that the change that triggered the callback is a year change. If it is not, also call dash.exceptions.PreventUpdate to prevent the callback from being executed.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
