### ISSUE TITLE
[BUG] html.iframe not loading properly when not in initial active tab

### ISSUE THREAD

**Issue by toastisme** [plotly/dash#2436]
Unsure if this behaviour is intentional, so making an issue just in case.

```
dash                          2.8.1
dash-bootstrap-components     1.4.0
dash-core-components          2.0.0
dash-extensions               0.0.71
```

    - OS: Ubuntu 20.04.4 LTS
    - Browser Firefox 110.0 (also tried on Chrome)

**Describe the bug**

I have a tab with an `html.iframe`. When the tab is the default active tab on startup, everything works correctly. But if the tab is not the active tab, the html in the iframe fails to load properly as things like the component height and width are zero, which are used in some code. Can/should the `html.iframe` component loading be deferred until it is visible, in case any contained code relies on the parent container being fully loaded? I get around this currently by only creating the `html.frame` when the tab is selected for the first time.

MWE not loading correctly

```
from dash import Dash, html, Output, Input
import dash_bootstrap_components as dbc

app = Dash(external_stylesheets=[dbc.themes.DARKLY])

app.layout= html.Div([
	dbc.Tabs(
		children=[
			dbc.Tab(
				label="test tab"
			),
			dbc.Tab(
				html.Iframe(
					src="assets/test.html",
				),
				label="html iframe tab",
			),
		]
	),
]
)

if __name__ == "__main__":
	app.run_server(host="127.0.0.1",debug=True, port=8052)
```

MWE loading correctly

```
from dash import Dash, html, Output, Input
import dash_bootstrap_components as dbc

app = Dash(external_stylesheets=[dbc.themes.DARKLY])

app.layout= html.Div([
	dbc.Tabs(
		children=[
			dbc.Tab(
				html.Iframe(
					src="assets/test.html",
				),
				label="html iframe tab",
			),
			dbc.Tab(
				label="test tab"
			),
		]
	),
]
)

if __name__ == "__main__":
	app.run_server(host="127.0.0.1",debug=True, port=8052)
```

Callback workaround

```
from dash import Dash, html, Output, Input
import dash_bootstrap_components as dbc

app = Dash(external_stylesheets=[dbc.themes.DARKLY])

app.layout= html.Div([
	dbc.Tabs(
		children=[
			dbc.Tab(
				label="test tab"
			),
			dbc.Tab(
				label="html iframe tab",
                                id="html-frame-tab"
			),
		]
	),
]
)

@app.callback(
    Output("html-iframe-tab", "children"),
    Input("state-tabs", "active_tab"),
    State("html-iframe-tab", "children")
)
def update_html_iframe(active_tab, html_iframe):
    if active_tab == "tab-1":
        return html.Iframe(src="assets/test.html")
    return html_iframe

if __name__ == "__main__":
	app.run_server(host="127.0.0.1",debug=True, port=8052)
```

**Expected behavior**
Behaviour of the `html.iframe` component is the same regardless of if the parent tab is active on load.

**Comment by nickmelnikov82** [comment]
In your example, when the tab with the html.Iframe becomes active, the update_html_iframe function is called, which checks the active tab and returns the html.Iframe if the active tab is "tab-1". Otherwise, the original content of the html.Iframe is returned. Change the structure of your code using this approach, and it is likely that the html.iframe will load correctly regardless of the tab activity.

I noticed that you use the "html-frame-tab" identifier in the callback, but this identifier is not defined in your layout structure. For this example to work, you need to add the "html-frame-tab" identifier to the corresponding tab in the dbc.Tabs component.

For example.

```
from dash import Dash, html, Output, Input, State
import dash_bootstrap_components as dbc

app = Dash(external_stylesheets=[dbc.themes.DARKLY])

app.layout= html.Div([
    dbc.Tabs(
        children=[
            dbc.Tab(
                label="test tab"
            ),
            dbc.Tab(
                label="html frame tab",
                id="html-frame-tab"
            ),
        ]
    ),
    html.Div(id="iframe-container")
])

@app.callback(
    Output("iframe-container", "children"),
    Input("html-frame-tab", "id")
)
def update_html_iframe(active_tab):
    if active_tab == "html-frame-tab":
        return html.Iframe(src="assets/test.html")
    return None

if __name__ == "__main__":
    app.run_server(host="127.0.0.1", debug=True, port=8052)
```
In this example, we have created an id "iframe-container" for the <div> where we display the html.Iframe. Using the callback, we detect when the active tab is "html-frame-tab" and return an html.Iframe with the appropriate src.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
