### ISSUE TITLE
[BUG] x unified with hoverinfo

### ISSUE THREAD

**Issue by asicoderOfficial** [plotly/dash#2443]
When creating a plot where each datapoint is an independent trace with graph_objects, if I want to hide some values when hovering, I have to  use hoverinfo together with hover text.

However, when doing so, if I set hovermode="x unified", the x axes value does not show when hovering at the top of the hover label.

**Comment by nickmelnikov82** [comment]
To solve this problem, you need to use the hovertemplate parameter instead of hoverinfo in your code. hovertemplate allows you to customize the content of the hover.

Here's an example of how to use hovertemplate to include x-axis values even when hovermode is set to "x unified":

```
import plotly.graph_objects as go

x_data = [1, 2, 3, 4, 5]
y_data = [10, 20, 30, 40, 50]

fig = go.Figure()

for x, y in zip(x_data, y_data):
    fig.add_trace(go.Scatter(
        x=[x],
        y=[y],
        mode='markers',
        hovertemplate='x: %{x}<br>y: %{y}'
    ))

fig.update_layout(
    hovermode='x unified'
)

fig.show()
```

In the hovertemplate parameter, %{x} and %{y} are placeholders that will be replaced with the corresponding x- and y-axis values when the cursor is moved. This way, the x-axis value will be displayed even at the top of the hover label. You can customize the hovertemplate string to include any other information you want.

Note that in this example, separate graphs were created for each data point. If you have multiple data points within the same graph, you can modify the hovertemplate to display the appropriate information for each point.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
