### ISSUE TITLE
[BUG] DataTable containing List behaves inconsistently between display and export

### ISSUE THREAD

**Issue by avarsava** [plotly/dash#2457]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                      2.8.1
dash-bootstrap-components 1.4.0
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-renderer             1.5.0
dash-table                5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Ubuntu 20.04
    - Browser: Firefox
    - Version: 111.0

**Describe the bug**

Create a pandas DataFrame where one cell is a python List. 
The items in the list are displayed concatenated in the front end, but when Exported to csv, the cell is blank.

**Expected behavior**

The exported CSV should be the same as the display in the front end.

**Screenshots**

Minimal example:

```
import pandas
from dash import Dash, html, dcc, dash_table

app = Dash(__name__)

df = pandas.DataFrame({"Column": ["one", "two", ["three","four"]]})

app.layout = html.Div(children=[
    dash_table.DataTable(
        id="tableid",
        columns=[{"name": col, "id": col} for col in df.columns],
        data=df.to_dict('records'),
        export_format="csv"
    )
])

if __name__ == '__main__':
    app.run_server("0.0.0.0", 5000, debug=False)
```

Browser display:
![image](https://user-images.githubusercontent.com/17747491/225624259-84e7bb90-24e3-4e6a-b3fe-55ec57a1e140.png)

Data.csv:
```
Column
one
two

```

Please note the blank line after 'two'

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
