### ISSUE TITLE
[Feature Request] Dash Pages - custom page_container in dash.register_page

### ISSUE THREAD

**Issue by m-ganko** [plotly/dash#2484]
**Is your feature request related to a problem? Please describe.**
I think it would be convenient to be able to redirect some pages to custom `page_container`. There might be case when we don't want to display our page in standard way in `page_container`, but for example as a whole new page.

**Describe the solution you'd like**
`dash.page_registry` could have new field `page_container` which could be passed as `dash.register_page(__name__, page_container='container_id')`

**Describe alternatives you've considered**
Alternative way is to use old approach - callback to `dcc.Location` id. The problem is before page loading you will see for a brief time page with 404 error. Maybe it would be possible to somehow check if any other callback has `Input` with `pathname` before showing error page?

```python
@callback(
    Output('container_id', 'children'),
    Input('url', 'pathname')
)
def custom_endpoint(pathname):
    if pathname and (pathname == '/custom'):
        return "Custom page"
    else:
        raise PreventUpdate
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
