### ISSUE TITLE
[BUG] There is no response to clicking on scatter_3d on mobile devices.

### ISSUE THREAD

**Issue by AndreyM0** [plotly/dash#2532]
There is no response to clicking on scatter_3d on mobile devices. Works correctly on desktop devices. Clicking on a 2D chart works correctly on mobile devices as well.

For example, this code does not work correctly on mobile devices, does not display information about clickData in html.Div(id='click-data').

import plotly.express as px
from dash import Dash, html, dcc, Input, Output

df = px.data.iris()
fig = px.scatter_3d(df, x='sepal_length', y='sepal_width', z='petal_width',
                    color='petal_length', symbol='species')

app = Dash(__name__)
app.layout = html.Div([
    html.Div(id='click-data'),
    dcc.Graph(id="scatter-plot",figure=fig)
])

@app.callback(
    Output('click-data', 'children'),
    Input("scatter-plot", "clickData"))
def display_click_data(clickData):  
    return(str(clickData))

app.run_server(port=8050, host="0.0.0.0", debug=True)

**Comment by nickmelnikov82** [comment]
Good afternoon! I am trying to understand your situation and help you solve the problem.
The open page in my laptop browser looks like this:
![Screenshot from 2023-06-01 09-01-55](https://github.com/plotly/dash/assets/53801797/5ee1aedb-223b-4ef8-98a4-3cd03f30592e)

And here is how it is displayed on my phone:
![photo_2023-06-01_09-04-16](https://github.com/plotly/dash/assets/53801797/6b94fc73-4295-45d8-b820-62d659a76c63)

Please provide me with a more detailed description of your problem and also send me screenshots so that I can better understand the problem and assist you in solving it.

**Comment by AndreyM0** [comment]
When I click on a dot.
PC:
![pc](https://github.com/plotly/dash/assets/63886896/244aa83c-da95-4bc8-a00b-452dfe187807)
Phone:
![phone](https://github.com/plotly/dash/assets/63886896/de582d4b-48bf-48e9-9783-28252aff6404)

**Comment by nickmelnikov82** [comment]
This is actually a very interesting question, because the code you attached above works perfectly on both my phone (iOS and Android) and my laptop. I think the problem is in the browser.

One possible solution is to check if your mobile device settings allow you to use click events on web pages. Some mobile browsers have this feature disabled by default for security reasons. Check if the "allow clicks" or "allow click events" option is enabled on mobile devices in your browser settings.

Also, make sure your mobile device supports JavaScript and has an up-to-date browser version, as Plotly and Dash use JavaScript to handle events.

Please let me know if this was helpful to you.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
