### ISSUE TITLE
[BUG] dcc.input does not show up on blackberry browser on iPad

### ISSUE THREAD

**Issue by e-wallace** [plotly/dash#2534]
**Describe your context**
The spinner box for dcc.input(value=number) did not show up on Blackberry Access browser on an iPad or on other browser types on IOS devices

    - OS: iOS
    - Browser: all iOS devices use the same web rendering engine

**Describe the bug**

dcc.input(value=number) does not render the up/down arrows on mobile devices.
<img src="https://user-images.githubusercontent.com/44043492/239574584-829563e6-99c8-4a09-a08b-6a57853710ef.jpg" alt="IMG_0187" width= "400">

**Expected behavior**
Expected the arrows to show up and modify the number input.

<img width="604" alt="Screen Shot 2023-05-19 at 11 05 30 AM" src="https://github.com/plotly/dash/assets/44043492/772ea7d5-30dd-4de1-b346-f3ec24b8459d">

**Comment by nickmelnikov82** [comment]
Greetings! Would it be possible for you to provide me with the code snippet that utilizes these arrows? It would greatly aid my comprehension of the error at hand.

**Comment by alexcjohnson** [comment]
Curious what this looks like on various browsers on Android. On iOS it may be intentional, but it looks like there may be CSS tricks to force the arrows to show up: https://davidwalsh.name/always-show-arrows-for-number-input (that post uses vendor-prefixed attributes, so there may be more)

**Comment by alexcjohnson** [comment]
Note that `dcc.Input` is a very light wrapper around the browser native `<input>` element, so we're dependent on the browser itself for extra features like this. You can also try [dash-daq `NumericInput`](https://dash.plotly.com/dash-daq/numericinput) that's a bit more custom-built.

**Comment by nickmelnikov82** [comment]
Hello again. I managed to find an [article](https://stackoverflow.com/questions/67091659/how-to-always-display-numerical-input-spinners-on-mobile-and-ipad) with the same error as yours.
And also two articles with similar errors: [article1](https://community.plotly.com/t/hiding-number-field-control-buttons/15908) and [article2](https://community.plotly.com/t/dcc-input-number-up-down-arrows/24799)
I hope this helps you, if you have any questions, please do not hesitate to contact me, I will be happy to help or suggest something

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
