### ISSUE TITLE
[Feature Request] Improve documentation on clientside callbacks

### ISSUE THREAD

**Issue by Vasallius** [plotly/dash#2535]
It took me so long to be able to try to figure out how to run javascript in dash. The documentation was not really verbose and helpful. I hope we can update this. Cheers.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
