### ISSUE TITLE
[BUG] Dash 2.11 triggers build recommended for @plotly/dash-jupyterlab 

### ISSUE THREAD

**Issue by melanopsis** [plotly/dash#2580]
Greetings, 

After upgrading to Dash v2.11, I see a build recommended pop-up window for @plotly/dash-jupyterlab. 

![build_recommended](https://github.com/plotly/dash/assets/620072/0fd2efd6-55e5-429e-a38d-7b12b36b9549)

`jupyter-labextension list` shows 

````
Other labextensions (built into JupyterLab)
   app dir: /usr/local/share/jupyter/lab
        @plotly/dash-jupyterlab v0.4.3 enabled OK

Build recommended, please run `jupyter lab build`:
    @plotly/dash-jupyterlab needs to be included in build
````

Here are the installed dash packages 

```
dash                         2.11.0
dash-bootstrap-components    1.4.1
dash-core-components         2.0.0
dash-daq                     0.5.0
dash-extensions              1.0.1
dash-html-components         2.0.0
dash-table                   5.0.0
```

Observed both with JupyterLab v3.6.4 and v3.6.5

Secondary build shouldn't be required

**Comment by likewei92** [comment]
I'm seeing this too, is it possible to switch to using a prebuilt extension?

**Comment by Coding-with-Adam** [comment]
hi @likewei92 
Are you seeing this in later versions of Dash as well? version 2.12 or 2.14?

**Comment by likewei92** [comment]
yes. Actually it only happens after 2.11. But this should not be a surprise? It's mentioned in the docs here: https://dash.plotly.com/dash-in-jupyter#display-modes

"To use jupyterlab mode, you'll also need to build the @plotly/dash-jupyterlab extension. When you launch a new JupyterLab notebook after installing Dash, you'll be prompted to build @plotly/dash-jupyterlab."

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by krassowski** [comment]
Hi @gvwilson, a JupyterLab maintainer here. Just FYI using source extensions is deprecated and I would warmly encourage you to ship a prebuilt extension instead as it is much better UX for users. Otherwise, you are just missing out on anyone who cannot find a right combination of node.js and other tooling (or cannot install them altogether).

Of note, plotly itself ships a prebuilt extension since https://github.com/plotly/plotly.py/pull/3142 (with a follow up fix in https://github.com/plotly/plotly.py/pull/3231).

The prebuilt extensions are documented in https://jupyterlab.readthedocs.io/en/latest/extension/extension_dev.html#overview-of-extensions

This was previously tracked in https://github.com/plotly/jupyter-dash/issues/49.

**Comment by gvwilson** [comment]
cc @marthacryan
