### ISSUE TITLE
[BUG] Dash with `serve_locally=False` is not caching the `plotly.min.js` in the browser after first load

### ISSUE THREAD

**Issue by cfloressuazo** [plotly/dash#2646]
**Describe your context**
Using Dash in production with the server initiated with the flag `serve_locally=False` so it can fetch JavaScript from the UNPKG CDN is failing or never able to cache the `plotly.min.js` file from the memory of the browser, and it is always fetching from the URL (or local).

```
dash                 2.13.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: any
    - Browser Chrome
    - Version 116.0.5845.187

**Describe the bug**
When using `serve_locally=False` I can see in the browser network tab that most of the JS that are loaded from UNPKG are cache in memory so when I refresh the page I can see that these files are with the `(memory cache)` in the size column, except for the `plotly.min.js`.

**Expected behavior**
The `plotly.min.js` should be cached in the browser and loaded from the `(memory cache)` after the first load.

**Screenshots**
These are fine:
<img width="1270" alt="Screenshot 2023-09-22 at 09 58 47" src="https://github.com/plotly/dash/assets/19332496/20f62917-9e11-42fc-b1bc-397c1baef1fa">

This is not.
<img width="1325" alt="Screenshot 2023-09-22 at 10 00 26" src="https://github.com/plotly/dash/assets/19332496/37bca44a-62f7-4ff0-9305-42cbada52ce9">

**Comment by T4rk1n** [comment]
It is using a cached version in the screenshot, 304 response is Not Modified and the size is 516B not the actual size of plotly js.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304

**Comment by alexcjohnson** [comment]
Also those filenames are the `serve_locally=True` versions, with the cache-busting `v#_#_#m######` in the entrypoint bundle filenames. `plotly.min.js` (like `async-graph.js`) doesn't have that because it's loaded async and we don't have the opportunity to add that to the filename so it uses an ETag, hence the request and `304` instead of a straight cache hit. `False` gives filenames like this:

<img width="974" alt="Screenshot 2023-09-22 at 11 18 14" src="https://github.com/plotly/dash/assets/2678795/73f1634d-78a2-403c-8f15-cf302ff9071f">

Are you perhaps using `debug=True` which doesn't support `serve_locally=False`? If so you should have this message in the console:
```
WARNING: dev bundles requested with serve_locally=False.
This is not supported, switching to serve_locally=True
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
