### ISSUE TITLE
[Feature Request] Manually clear dynamically registered callback functions

### ISSUE THREAD

**Issue by CNFeffery** [plotly/dash#2664]
The `_allow_dynamic_callbacks` in 2.14 could be more useful than it was designed to be, to build more flexible applications, but as the continuous dynamic callback registration, the info comes from `/_dash-dependencies` increases too, for example, create callbacks with random `uuid ` every time, is there any way to manually clear dynamically created callbacks?:

![image](https://github.com/plotly/dash/assets/49147660/9c5b87e1-faf0-4662-9038-6f1004882e6f)

![image](https://github.com/plotly/dash/assets/49147660/d036047e-9921-429e-a93c-61b7082f9c3d)

**Comment by alexcjohnson** [comment]
@CNFeffery I appreciate your interest in this feature, but because of its strict limitations (single-process, single-user, otherwise you end up in a really strange state) we're not intending to document it, support it beyond our internal use cases where we're very confident those limitations apply, nor are we committing to not break it in the future (this is why it starts with `_`). That said if you're similarly confident there's likely a way to do what you want if you fiddle with `app._callback_list` and `app.callback_map` but due to these limitations I'd request that you not build this into any packages that will be widely distributed or used in ways you don't control.

**Comment by CNFeffery** [comment]
Got it, thank you!
