### ISSUE TITLE
TypeError: __init__() takes at most 2 arguments (3 given)

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#268]
When making a simple mistake like:
```
html.Table('a', 'b')
```
instead of 
```
html.Table(['a', 'b'])
```
you get a pretty tough-to-debug error message:
```
TypeError: __init__() takes at most 2 arguments (3 given)
```

We should catch these types of errors and provide a better error message

**Comment by rmarren1** [comment]
We should get this for free in #340

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
