### ISSUE TITLE
[Feature Request] Run dash in jupyter without additional server iframe

### ISSUE THREAD

**Issue by zba** [plotly/dash#2688]
The problem with Iframe approach is that you need to pass additional ports from your dev environment which could be hard sometime, which makes troubles when you trying to make for example interactive chart, using dash-cytoscape

However as I understand jupyter have own data pipe between server and client.

So may be we can somehow avoid do app.run() the way it creates iframe on 127.0.0.1 ?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
