### ISSUE TITLE
[Feature Request] Validate Arguments to components

### ISSUE THREAD

**Issue by zevaverbach** [plotly/dash#2691]
If I break my Dash app by supplying, for example, the wrong type for `marks` when instantiating a `dcc.Slider`, the error message is not useful: "Error loading layout" is displayed in the browser, and nothing at all is logged on the back end.

What I'd hope for, and to some extent expect, is a helpful error message pointing to the issue, something like:

```python
Slider(marks={year: year for year in df["Year"].unique()}, ...) 
  is an invalid type, as what's required is dict[str, str | dict].
```

Or I guess the actual values which were fed into `Slider`, I think you get what I mean.

**Describe alternatives you've considered**
The only alternative is to revert (hopefully) your most recent changes which broke the app; otherwise, to go bug-hunting.

**Additional context**
Possibly something like `pydantic` could be useful here, and if type hints were added to the components, either directly or via Pydantic models, there might not be a lot of additional work to implement such a validation feature. I haven't dug too deeply into the React-side props validation and how you've implemented "React Component" -> "Python Class", but maybe it would make sense to tackle it from that end and generate the Python component classes from that.

I'm happy to implement this, by the way!

Cheers,

Zev

**Comment by AnnMarieW** [comment]
@zevaverbach 

You will get an error message if you run the app with `debug=True`:

```

if __name__ == '__main__':
    app.run(debug=True)

```

![image](https://github.com/plotly/dash/assets/72614349/f24fa960-bace-4d06-b2ab-181020a4d861)

**Comment by zevaverbach** [comment]
@AnnMarieW thanks for your quick response! I can't replicate what you're showing here, it only offers "Error loading layout" and doesn't have a modal like the one you pasted:

<img width="1792" alt="image" src="https://github.com/plotly/dash/assets/2838836/17df83e7-dcb5-437b-8aa6-3f7b012d2985">

To be clear, I am running it with `app.run(debug=True)`.

Here's some version info if that helps:

dash==2.14.1
python==3.11.6

Running on MacOS 14.0

**Comment by AnnMarieW** [comment]
I'm not running python 3.11, so that might be an issue?  But here is the app - can you try running the following, or posting a complete minimal app I could try?

```

from dash import Dash, html, dcc
import numpy as np

app=Dash(__name__)

app.layout = html.Div(dcc.Slider(marks={year: year for year in [2012, np.nan, None]}))


if __name__ == '__main__':
    app.run(debug=True)



```

**Comment by zevaverbach** [comment]
Thanks for that suggestion, @AnnMarieW. Before you responded, I tried casting the values here to `int` and got a helpful error message like the one you showed:

```python
year_slider = dcc.Slider(
    min=df["Year"].min(),
    max=max_year,
    value=max_year,
    marks={int(year): int(year) for year in df["Year"].unique()},
)
```

However, doing this -- leaving the keys as `numpy.int64`s -- is what causes the "no error message" problem:

```python
year_slider = dcc.Slider(
    min=df["Year"].min(),
    max=max_year,
    value=max_year,
    marks={year: str(year) for year in df["Year"].unique()},
)
```

Does that make the problem clearer? (and reproducible?)

**Comment by AnnMarieW** [comment]
yes, that's reproducible now.  Thanks

**Comment by alexcjohnson** [comment]
Thanks @zevaverbach - very frustrating! I don't think the solution is having components validate their props though. We want to keep that on the client side, both for performance reasons (unless we only do it in debug mode) and because the components themselves might not know which types will serialize to the correct JSON type.

We definitely want to track down whatever is generating these `Error loading layout` messages (and related like `Error loading dependencies`) which give you no useful information. Here it seems like the `numpy.int64` type isn't handled by our JSON serializer, which is something we should fix (it lives in [`plotly.py`](https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/io/_json.py)) but the broader issue is that these errors are being swallowed and we need to figure out where that's happening and surface them in a way that helps you fix them.
