### ISSUE TITLE
[BUG] dcc.Dropdown value does not update when an option is removed (regression from #1868)

### ISSUE THREAD

**Issue by Thuener** [plotly/dash#2733]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                 2.13.0
```
**Describe the bug**
Regression #1868 
When the options of a dcc.Dropdown are updated to remove a currently selected option, the UI updates to remove that value, but the value parameter does not update.

**Expected behavior**

Removing an option from options should also remove that option from value, that way it will be sync with the UI.

**Screenshots**

Using the same code as #1868 but with version 2.13.0 we have 
![msedge_oxESf4Irhm](https://github.com/plotly/dash/assets/770605/79516863-9dd6-4e9b-86b0-32f9b6cc7138)

**Comment by TillerBurr** [comment]
I was able to pinpoint the problem to the code 
https://github.com/plotly/dash/blob/f7f8fb4c5893506e35cdeaec141310a95fe1486a/components/dash-core-components/src/fragments/Dropdown.react.js#L123-L129

In particular, the searchable check is somewhat problematic. Removing it fixes the issue because the dropdown in the example is searchable by default. The reason that it was there to begin with is that without that check, it reintroduces the issue https://github.com/plotly/dash/issues/2099.
