### ISSUE TITLE
Dangerous link detected error after upgrading to Dash 2.15.0

### ISSUE THREAD

**Issue by emilhe** [plotly/dash#2764]
```
dash                      2.15.0
dash-bootstrap-components 1.5.0
dash-core-components      2.0.0
dash-extensions           1.0.12
dash-html-components      2.0.0
dash-iconify              0.1.2
dash-mantine-components   0.12.1
dash-table                5.0.0
```

After upgrading to Dash 2.15.0, I have apps that are now breaking with `Dangerous link detected` errors, which are emitted when I use `Iframe` components to display embedded data, e.g. PDF files.  Here is a small example,

```
import base64
import requests
from dash import Dash, html

# Get a sample PDF file.
r = requests.get("https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf")
bts = r.content
# Encode PDF file as base64 string.
encoded_string = base64.b64encode(bts).decode("ascii")
src = f"data:application/pdf;base64,{encoded_string}"
# Make a small example app.
app = Dash()
app.layout = html.Iframe(id="embedded-pdf", src=src, width="100%", height="100%")

if __name__ == '__main__':
    app.run_server()
```

I would expect the app would continue to work, displaying the PDF, like it did in previous versions. 

I guess the issue is related to the fixing of XSS vulnerabilities as mentioned in #2743 . However, I am not sure why it should be considered a vulnerability to display an embedded PDF file.

**Comment by AnnMarieW** [comment]
Please see more information in this forum discussion:
https://community.plotly.com/t/dangerous-link-detected-error-in-dash-debug-window-after-upgrading-from-2-14-2-to-2-15-0/82311/3

**Comment by ndrezn** [comment]
Maybe for components which had sanitization added to prevent the XSS issue should have a new `disable_validation=` property which if flagged `True`, would revert to the previous behaviour, but would default to `False` with the current behaviour.

I am hesitant to introduce specific exceptions for example _only allowing_ `data:`, or in essence manually overriding parts of our URL sanitizer.

**Comment by AnnMarieW** [comment]
A `disable_validation` prop would be helpful. 

@alexcjohnson had mentioned handling the URL sanitation on the Dash framework level rather than the component level -- then it would apply to all components including custom components or libraries such as dbc and dmc.  Is that still on the radar?

**Comment by emilhe** [comment]
I like the idea of the `disable_validation` flag with a default value of `False`. That protects the majority of users, while maintining the option to (consciously) opt out to enable specific usecases.

**Comment by ndrezn** [comment]
1. Disable validation at the component level
- After some thought & more conversation with @alexcjohnson, hesitant about this solution. It basically puts us back to square one: Given an app with a mechanism to save a layout statefully, a bad actor could add a `dcc.Link(disable_validation=...)` component to the layout before saving, meaning we're back to not protecting at all against XSS.
2. Disable validation at the framework level
- This avoids the issue above, because a bad actor can't change the setting at the `app` configuration level via the layout, but it means that apps with this setting might be unsafe (in @emilhe's PDF example, now this app is vulnerable even though we might want to prevent any other links besides the one with the embedded PDF from working).
3. More fine-grained validation to avoid warnings for safe links (which often, `data:` is safe)
- We might be able to further scan the URL string to check whether to allow it or now. Blanket preventing `data:` might be overkill, essentially. We're [using](https://github.com/plotly/dash/blob/f7f8fb4c5893506e35cdeaec141310a95fe1486a/components/dash-html-components/scripts/generate-components.js#L261-L275) https://github.com/braintree/sanitize-url  as the mechanism to check for bad URLs rather than something custom, which is quite popular, and which wholesale prevents `javascript:`, `vbscript:`, and `data:` URLs. It might be worth checking with the maintainers of this package to see if they have considered more fine-grained control.

In general the real risk is a specific class of applications (applications which allow you to save a portion of the layout as state, for example https://github.com/plotly/all-in-ai-demo-app -- observe what happens when you click/how "Save this chart" works). 

There's also the reasonable point that for the original example, maybe using `data:` in the first place isn't a great way to e.g. display a PDF or embedded data. But `data:` also isn't going to be deprecated so we might need to allow it generally. 

I'm going to open a ticket in https://github.com/braintree/sanitize-url to see if they're thinking about this problem.

**Comment by emilhe** [comment]
While I am not expect in web technology, I get the impression looking at the literature that using `data:` to display media (e.g. PDFs) is not considered bad practice.  I am curious; @ndrezn do you consider it bad practice? If yes, do you have an example (a conceptual description, a link to a resource, ...) of good practice realising the same functionality?

At a holistic level, I see Dash being used for a great variety projects, many of which that do not have strict security requirements (e.g. a scientific single-user app running locally). For such users, the proposed change is removing (potentially important) functionality to address concerns ((e.g. the save-layout-state example) they'll never face. In general, I consider the ability to adopt standard web technology solutions a key strength of Dash. Hence, removing this flexibility at framework level (without the ability to opt out) feels like a step in the wrong direction - unless there is a **really** strong argument for doing so.

I of course understand the security concerns, and I appreciate the work being put into addressing them. However, with Dash being such a general framework, I believe that we should strive to keep as much flexibilty as possible. Even if that means enabeling users to shoot them self in the foot, if they really want to.

**Comment by alexcjohnson** [comment]
The specific type of `data:` urls I’ve seen as exploitable are `text/html`, which unfortunately is exactly what we document in https://github.com/plotly/plotly.py/issues/4559. That’s not to say there aren’t others that could be abused, we need to do a little more research. In fact it’s possible browsers have even closed the entire `data:` loophole, see eg https://security.stackexchange.com/questions/258306/how-is-object-tag-data-uri-xss-actually-xss - if so we can perhaps whitelist that whole protocol.

**Comment by ndrezn** [comment]
@AnnMarieW pointed me to the interesting perspective from Mozilla: https://blog.mozilla.org/security/2017/11/27/blocking-top-level-navigations-data-urls-firefox-59/

> Whereas the following cases will be allowed:
> - User explicitly entering/pasting “data:…” into the address bar
> - Opening all plain text data files
> - Opening “data:image/*” in top-level window, unless it’s “data:image/svg+xml”
> - Opening “data:application/pdf” and “data:application/json”
> - Downloading a data: URL, e.g. ‘save-link-as’ of “data:…”

**Comment by BSd3v** [comment]
Hello all,

Curious as to your thoughts on this as a workaround?

https://community.plotly.com/t/dangerous-link-detected-error-in-dash-debug-window-after-upgrading-from-2-14-2-to-2-15-0/82311/8?u=jinnyzor

Basically, you have a flask template, which is setup to pull the data: back and display it. Flask templates are driven from the server and therefore should be safe to use. 

Plus the template is outside the ecosystem of dash. So, it should be safe as far as saving layouts and other props as well. 

In this example, the weight falls on the dev to make sure the template is rendering safe and secure files.

**Comment by BSd3v** [comment]
Another possible concern would be what this person used as the workaround. 

https://community.plotly.com/t/dangerous-link-detected-error-in-dash-debug-window-after-upgrading-from-2-14-2-to-2-15-0/82311/14?u=jinnyzor

This adjusted the srcDoc. Does this potentially expose the same vulnerability?

**Comment by ndrezn** [comment]
@T4rk1n -- I think the strategy will be to use Mozilla's heuristic for detecting safe URLs and using that custom strategy rather than `sanitize-url`. We can plan @ libraries meeting this week but we should get this resolved. Curious if you have other thoughts in advance or other strategies you'd recommend.
