### ISSUE TITLE
[Feature Request] Supports more flexible and free component type properties

### ISSUE THREAD

**Issue by CNFeffery** [plotly/dash#2788]
Currently, as mentioned in the documentation ( https://dash.plotly.com/component-properties ), only a few valid formats are supported for component elements as attributes, the hope is that dash will support freer component-type property definitions under the hood, including arbitrary depth nesting, to cope with some tree-like data structures.

**Comment by Coding-with-Adam** [comment]
Hi @CNFeffery 
Can you please share a specific use case for this feature request?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
