### ISSUE TITLE
Exception: Access Denied 

### ISSUE THREAD

**Issue by cchen0630** [plotly/dash#2861]
I recently upgraded my dash version from 2.8.1 to 2.14.2. It gave me this exception and stops me from access the internal sever. 

![image](https://github.com/plotly/dash/assets/157086300/5b0b4a94-9a20-48bb-931d-e530c38c73d5)

![image](https://github.com/plotly/dash/assets/157086300/e0ede9e9-3286-4c9e-89d3-b97b19db20dd)

I realized this issue might come with the function jupyter_dash.run_app(). However, my code didn't define or use anything related with jupyter. Is there anyway I can disable or avoid this function so the exception won't be raised?

Thank you.

**Comment by cchen0630** [comment]
> The condition for running in jupyter is running in Ipython which seems to be the case here, but it need to run inside a jupyter notebook or jupyterlab not just the ipython prompt.

Thank you for your comment. I‘m running in Jupyter notebook now, however, it still gives me the same exception message. Does this new function require online communication with any external website? if so, how can I edit the code if I have to run it in an offline environment? 

![image](https://github.com/plotly/dash/assets/157086300/216fe2d9-9c79-4d0b-abe2-b8c7ac2196f3)

![image](https://github.com/plotly/dash/assets/157086300/c6170876-0541-4522-b689-cddad0c0d2c6)

**Comment by T4rk1n** [comment]
I think you may need to set the `jupyter_server_url` to run on a hosted notebook, you can find the documentation for running with jupyter here: https://dash.plotly.com/dash-in-jupyter

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
