### ISSUE TITLE
KeyError 'callback' is raised if you forget the `@` in the `@callback`

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#300]
If you write:
```
app.callback(...)
def some_func(...):
```
instead of 
```
@app.callback(...)
def some_func(...):
```

then a very hard to debug error is raised:
```
File "./venv/lib/python3.6/site-packages/dash/dash.py", line 556, in dispatch
    return self.callback_map[target_id]['callback'](*args)
KeyError: 'callback'
```

It would be nice if we did some validation on callback instantiation here

**Comment by T4rk1n** [comment]
The `@` is just syntax sugar for decorators, you can write a callback as such:
```
def some_func(...):
    ...

app.callback(...)(some_func)
```
As you see, the `callback` method doesn't apply to func immediately but instead is appended by the `wrap_func` that is returned by `callback`. When there is no `@` , it will not insert the callback function in the callback_map but will insert the inputs, states and events because those are inserted out of the `wrap_func`, meaning we get a key error when we try to access `self.callback_map[callback_id]['callback']` because it does not exist in that dictionary.

If we move the inputs, states and events inside `wrap_func`, the callback will never register and there won't be any error. But the user will not get it's callback called and no output at all, which is worse because the user will wonder why it's not called.

For a solution:

In `_setup_server`, check that all callback have a 'callback' in it's dict, if not, throw an error with the output id and prop to identify faulty callback register.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
