### ISSUE TITLE
41 security alerts by dependabot

### ISSUE THREAD

**Issue by chgiesse** [plotly/dash#3086]
Hi there! 

I've forked Dash and turned on dependabot security alerts, which triggered 41 alerts. Is this due to the dev branch? 

Thanks in advance and kind regards,
Christian 

![Image](https://github.com/user-attachments/assets/556637ab-a1e9-4808-a4d6-cdcbd54b5e64)

**Comment by T4rk1n** [comment]
> Is this due to the dev branch?

No, we have multiple packages and the js ecosystem for them has ton of dev dependencies that get hit with alerts. Most of them are not exploitable since they are only for bundling, I usually update the importants one before releasing new version, but some of them we can't easily do (eg: Markdown in dcc need a overhaul of the markdown component).

Then there are all those in the `@plotly` packages, they are not part of the framework but only used for testing purpose and we don't update them as often.

**Comment by chgiesse** [comment]
Ah okay, thanks for the clarification! 

Keep up your great work! Looking forward to 3.0!
