### ISSUE TITLE
Dash flow tests errors.

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash#319]
Running the tests locally, I get this SyntaxError:

```
  File "C:\Users\t4rk\dev\plotly\dash\tests\test_integration.py", line 8, in <module>
    import dash_flow_example
  File "C:\Users\t4rk\dev\plotly\dash\venv\lib\site-packages\dash_flow_example\__init__.py", line 10, in <module>
    'dash_flow_example'
  File "C:\Users\t4rk\dev\plotly\dash\dash\development\component_loader.py", line 51, in load_components
    namespace
  File "C:\Users\t4rk\dev\plotly\dash\dash\development\base_component.py", line 441, in generate_class
    exec(string, scope)
  File "<string>", line 23
    def __init__(self, id=Component.UNDEFINED, label=Component.REQUIRED, value=Component.UNDEFINED, options=Component.UNDEFINED, config=Component.UNDEFINED, encrypted_*=Component.UNDEFINED, **kwargs):
                                                                                                                                                                        ^
SyntaxError: invalid syntax
``` 
The invalid part:
`encrypted_*=Component.UNDEFINED, `, cannot have a `*` in a explicit keyword arg (would work in dict passed as kwargs).

When I comment the `import dash_flow_example`, it works and it somehow works on circleci.

**Comment by chriddyp** [comment]
> Remove the notion of valid wildcard attributes in dash, and accept any string of the form '<string>-*' as a wildcard attribute, or even remove the - and accept '<string>*'.

This seems reasonable to me. I think that this is how I thought things worked anyway. I don't think that this has any implications besides for Python validation.

I'd like to think about this for a couple of more days just to make sure that there aren't any other long term implications of this.

cc @plotly/dash as well

**Comment by rmarren1** [comment]
The original use case for wildcards was only to add functionality for the `data-*` and `aria-*` attributes for basic HTML elements.

I don't see any technical reason for limiting wildcards, but I also can't really think of a use case where wildcard attributes are necessary.

For example, if you re-implemented a HTML component you could just use `data = {attr1: 'value1', ...}` and `aria = {attr1: 'value1', ...}` javascript objects. It seems wildcards only exist in HTML because there was no syntax to represent a map/dict/object, but we have that already in Dash.
