### ISSUE TITLE
Idea: renaming app.callback

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash#353]
It occurred to me the other day that `callback` is a very implementation-centric/imperative/procedural/"how" kind of name, as opposed to an explanatory/declarative/functional/"what" kind of name. It also doesn't really capture the notion that any given prop can/should only be the output of a single callback.

I wonder if a name like `bind` (we're binding outputs to inputs via a function) or `define`/`definition` (defining the outputs in terms of the inputs) or `derive`/`derivation` or `dependency` or `rule` or something like that might not be better for the developer experience in terms of being much clearer, in the long term.

**Comment by T4rk1n** [comment]
I like trigger, like an output is triggered by inputs.

**Comment by mungojam** [comment]
Coming from a functional style and way of thinking I think of callbacks of functional bindings between the inputs and outputs, so I would prefer `bind` as it describes the what rather than how which both `trigger` and `update` seem to do

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
