### ISSUE TITLE
(Idea) Preserve application state when in debug mode.

### ISSUE THREAD

**Issue by rmarren1** [plotly/dash#357]
The reason https://github.com/plotly/dash-renderer/pull/60 was added in `dash-renderer` is that application state is maintained in the front-end Redux store and not in the back-end. This makes sense for production applications since we want Dash servers to be completely stateless, but I don't see why this has to be true when in development mode. As long as we carefully code it as to use the state only to do validation and debugging and not affect actual app execution, and figure out a way to clear this state on page refresh, it should be be fine.

Some cool things we can do if `app.layout` is constantly updated:
* Implement https://github.com/plotly/dash-renderer/pull/60 in the back-end throwing a specific Dash Exception. We can effectively remove 'suppress_callback_exceptions' and do this step dynamically
* Print a 'diff' of the state tree after each callback
* Make bug reports super simple, 
* Make it super easy to create test fixtures for Dash apps

This would be relatively simply to implement too.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
