### ISSUE TITLE
dispatching update to multiple component

### ISSUE THREAD

**Issue by StephaneKazmierczak** [plotly/dash#375]
Hi, 

I am having trouble dispatching an event to multiple components.
I am trying to use the tutorial: https://dash.plot.ly/sharing-data-between-callbacks. 
The first part work, I can update the children property of the hidden div
but the event generated after updating the children property of the hidden div doesn't have data.
In the code below the print data return None.  

```py
@app_mts.callback(
    dash.dependencies.Output('dispatch-div', 'children'),
    [dash.dependencies.Input('dropdown-load-data', 'value')])
def dropdown_mts_selected(value):
    if len(value) > 0:
        return value

@app_mts.callback(
    dash.dependencies.Output('drug-table', 'rows'),
    [dash.dependencies.Input('dispatch-div', 'children')])
def update_table_drugs(data):
    print data
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
