### ISSUE TITLE
Releases not being tagged in source (git)

### ISSUE THREAD

**Issue by r-chris** [plotly/dash#378]
**What's going on?**
It is difficult to identify the released code version from looking at the git repository. It seems sensible to me to continue tagging the source repo as shown here: https://github.com/plotly/dash/releases

You can see there that a few releases have been tagged nicely in the past, but for majority of releases on https://pypi.org/project/dash/#history no such tags exist in the git repo.

**Why is this relevant?**
I can see a few use cases, where having the git tags would be very beneficial:
1. It would be much easier for me to see the differences between releases if they were tagged in the git repository. I am aware that there is an actively maintained CHANGELOG for dash here: https://github.com/plotly/dash/blob/master/CHANGELOG.md but in mission critical deployments I rather have a look at the changes in the source.

2. I could easily pull the correct source code into my build system directly from GitHub without having to go through pypi.

Thank you!

**Comment by rmarren1** [comment]
https://github.com/plotly/dash/issues/332

**Comment by rmarren1** [comment]
I added git tagging to a checklist here

https://github.com/plotly/dash/pull/379

**Comment by T4rk1n** [comment]
I tagged the latest release (0.26.5).

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
