### ISSUE TITLE
remove werkzeug url print statements by default?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#382]
In many of my projects, I turn off the URL print statements with:
```
# Remove URL route logging
logging.getLogger('werkzeug').setLevel(logging.ERROR)
```

Should we do the same in Dash? Some thoughts:
- If we do it, we'll need a way to make it overridable in case users actually do want it. That is, placing it in `run_server` might be too late.
- Sometimes I find these statements useful when the dash is autorestarting and I'm refreshing the page. When the server has finished restarting, I'll see a flurry of print statements and I know that I'm ready to check out the web site. Of course, hopefully hot-reloading solves this in a more elegant way.
- The URLs themselves aren't that useful since all of the callbacks are just `POST /_dash-update-component`. We could make more useful debugging statements like `-> 'my-graph.figure start', `-> 'my-graph.figure.end` as part of a default dev tools / environment thing

**Comment by T4rk1n** [comment]
> Of course, hopefully hot-reloading solves this in a more elegant way.

Hot reload in #362 also adds a bunch of log since it's a requests loop. I think we should definitely remove them when hot-reload is activated.

> If we do it, we'll need a way to make it overridable in case users actually do want it. That is, placing it in run_server might be too late.

Please have a look at #369, @ned2 had the same kind of concern. I put the dev tools activation in a separate method. I think the logs should be activated in production, but not when the application is started via `run_server` so it could go in the `activate_dev_tools` method.
