### ISSUE TITLE
Some questions about using dash to build an enterprise data platform

### ISSUE THREAD

**Issue by cixingzhici** [plotly/dash#389]
Dash is amazing. I want to use Dash to develop an enterprise-level data platform that enables multiple account access. Here are a few questions to ask:

1. What framework is recommended? Is FLASK can be used?

2. Which authority control component is best？

3.For the view part, use the Dash_html with the original HTML, or use the Dash_html for all

**Comment by chriddyp** [comment]
> What framework is recommended? Is FLASK can be used?

Dash uses flask under the hood.

> Which authority control component is best？

We maintain `[dash-auth](https://github.com/plotly/dash-auth/)` for basic auth and plotly oauth login. Our enterprise product, [Dash Deployment Server](https://plot.ly/dash/pricing), supports corporate logins like LDAP, AD, Kerberos. 

Otherwise, Dash is open source and you can build on it however you want.

> For the view part, use the Dash_html with the original HTML, or use the Dash_html for all

`dash_html_components` for all. By using Python classes, you can create functions that generate markup and easily compose and parameterize your markup. We've built very large enterprise web apps for clients using these patterns.
