### ISSUE TITLE
Changing the name parameter to required.

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash#399]
@ned2 and I had a thread on the `assets_folder` parameter being absolute if you provide it. We thought it would be better if it would conform to how flask handles the static folder relative to the module.

Turns out the blueprint static folder is activated by `__name__` but I put `assets` as the parameter so it cannot find the root folder unless a module is named assets then it will take that path. This make the assets folder be absolute instead of relative to the module directory.

When I tested to make it relative, it broke if you didn't explicitly put the `__name__` in the dash constructor because of our default of `__main__`. If we replace the default by an empty string it works (it will fallback to os.cwd) but it might be too brittle and dependent on the os.

I think requiring the import_name like flask does would solve that issue and we would always be sure to have the right folder relative to the running project.

This would be a breaking change and would go in Dash 2.0

**Comment by ned2** [comment]
I've been thinking for a while that making the name parameter of Dash mandatory would simplify _a lot_ of things. I don't think there's any default value for this parameter that won't break some particular setup. Which is why I think Flask made this parameter mandatory. There's certainly a trade-off of adding a small amount of complexity to users for whom it may not be that relevant. But I would argue that the widespread adoption and popularity of Flask has shown that it's a viable approach.

**Comment by chriddyp** [comment]
> would simplify _a lot_ of things

Besides handling assets, what would it simplify?

**Comment by T4rk1n** [comment]
> Besides handling assets, what would it simplify?

Only the assets, the `import_name` parameter of flask is only used for template/static folders resolution and we only use static for the assets.

**Comment by ned2** [comment]
Well, a lot of things... but all pertaining to asset handling. Fair point!
