### ISSUE TITLE
legend positioning

### ISSUE THREAD

**Issue by IdrissMdb** [plotly/dash#410]
Hello,

I'm trying to implement pie chart having a big number of elements in legend.
and as soon as the scroll bar is added, the legend goes over the chart (trying it with orientation v and h)

(the chart on the left is the same as the one on the right, but with less elements shown)
![cap](https://preview.ibb.co/eOOuHU/Capture_d_e_cran_2018_09_29_a_07_48_45.png)

i found a similar issue on the plotly.js project
https://github.com/plotly/plotly.js/pull/3024

**Comment by chriddyp** [comment]
Thanks for reporting! This issue is indeed related to the plotly.js project, so feel free to reopoen or discuss there. It looks like a fix is getting made in https://github.com/plotly/plotly.js/pull/3024, so you might want to wait for that fix to get through to the Dash libraries (in particular dash-core-components: https://github.com/plotly/dash-core-components/blob/master/CHANGELOG.md)
