### ISSUE TITLE
RangeSlider's multiple handles keep resetting

### ISSUE THREAD

**Issue by michael-ziedalski** [plotly/dash#412]
Hello, all. I searched through the rest of the issues here as well as the forums, but this doesn't seem to have come up for anyone else.

When I create a Rangeslider with multiple handles (have only tested it to 3), and also having the following options, `marks` set up for the "available" values for the handles, `step=None`, and `allowCross=False`, the handles exhibit weird and breaking behaviour.

The middle handle can move around just fine among the `marks`, but as soon as either the left/right handle is moved, the opposite one resets to the middle handle's position. Eventually, the long-run of this behaviour is all 3 handles sitting one space apart from each other and unable to move.

```
bug = dash.Dash()
bug.layout = html.Div(children=[
    
    dcc.RangeSlider(
        id='buggy',
        min=0,
        max=100,
        value=[23, 65, 89],
        marks={
            0: {'label': '0°C', 'style': {'color': '#77b0b1'}},
            26: {'label': '26°C'},
            37: {'label': '37°C'},
            50: {'label': '50°C'},
            60: {'label': '60°C'},
            70: {'label': '70°C'},
            100: {'label': '100°C', 'style': {'color': '#f50'}}
        },
        step=None,
        allowCross=False
    )
])
```

Is there an easy fix for this?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
