### ISSUE TITLE
Dirty checks on updates

### ISSUE THREAD

**Issue by nite** [plotly/dash#415]
Dash would greatly benefit from dirty checks on app.callbacks. Currently user interaction can easily run into redundant multiple updates .

For a simple repro, take the datatable example in https://github.com/plotly/dash-table-experiments/blob/master/usage.py, stick some & logging or breakpoints into update handlers for `selected_row_indices`, spin it up and sort the columns in the grid. You should easily see multiple updates hit, even though `selected_row_indices` is not changing. The impact is otherwise not visible with this app, however if anything longer than a third of a second is fired on each update, it starts to become pretty obvious.

Dirty checks are a standard feature in most UI frameworks as of angular 1, including react which dash is built upon - hopefully this would be a javascript-only update.

**Comment by chriddyp** [comment]
It's up to the component to determine when to fire the callbacks (through the component's `setProps` property). So, if a callback is changing excessively, then that's a bug in the component.

There maybe be cases where the callback should still be fired even if the data values didn't change but the user made an interaction. There are also cases where checking whether the data has changed would be too expensive. So, I think that this should continue to be handled on the component's level rather than higher up in `dash-renderer`.

**Comment by nite** [comment]
Ok - cheers. Planning to try my hand soon at a custom component & wrap http://www.ag-grid.com, so I'll handle this there

**Comment by T4rk1n** [comment]
@nite you can try the new dash-component-boilerplate cookiecutter to create a custom component.

```
$ pip install cookiecutter
$ cookiecutter https://github.com/plotly/dash-component-boilerplate.git --checkout=cookie-cutter
```

https://github.com/plotly/dash-component-boilerplate/pull/14
