### ISSUE TITLE
Dash components: Review checklist

### ISSUE THREAD

**Issue by VeraZab** [plotly/dash#420]
Hey guys,
I was wondering if you'd find it useful to have a Dash app review checklist. I know that there's review apps set up for most dash repos now, and that's great.

But I'm thinking that, especially for new reviewers and makers of Dash components, it would be useful to have a few checkpoints to look at before saying a component is ready for release.

Example of things I'm thinking of:
- Component props: making sure that for each one we've thought about whether dash should be able to set them, or whether its something that should only be dealt with in the front-end, or if both front-end and dash should be able to affect their value.
- React doc strings, should all components have a basic set of info in Doc strings?
- Should all components work with any set of external data input? Is it up to the component or user to transform data in an acceptable format.
- Are all my assets properly included so that when I publish my component, the community will also have access?

That's just an example of questions I'm thinking of when looking at components, but I'm sure there's others we could think. 

Also, if we did make such a checklist, where would it live?

**Comment by valentijnnieman** [comment]
Yeah I think that's a good idea, it would certainly help in getting more users to make Dash components. I don't really know where it should live though. I'm thinking it should go somewhere in the [component boilerplate](https://github.com/plotly/dash-component-boilerplate), because that's what people will be using. Perhaps just in the readme of that repo?

**Comment by nicolaskruchten** [comment]
I would add that if any of these checks can be automated (i.e. insufficient docs, assets in MANIFEST) then they should raise warnings during the build step, to help people do things right :)

**Comment by T4rk1n** [comment]
There's a section about publishing your component in the boilerplate. Can add more info there. But I think the bulk of the information to build/publish components should be in dash-docs.

> Should all components work with any set of external data input? Is it up to the component or user to transform data in an acceptable format.

I don't understand this part, you mean validating the props in the component ?

> Are all my assets properly included so that when I publish my component, the community will also have access?

This definitely needs to be documented somewhere as you need to edit the `__init__` file.

**Comment by T4rk1n** [comment]
> I would add that if any of these checks can be automated (i.e. insufficient docs, assets in MANIFEST) then they should raise warnings during the build step, to help people do things right :)

The docstring validation could be added to `extract-meta` script.
The assets validation could be a prepublish script.

**Comment by VeraZab** [comment]
> Personally, I only test my components in a full python dash environment, there's no point in testing them on react except that it may faster to write.

I think that may not be what a lot of newbies do :) especially if we tell them that the only thing you need in order to make a Dash component, is to write a React one, compatible with the Dash ecosystem. I think that the fact of writing mostly javascript for your component may make you forget about how you'll interact with this component from the Python end. And having a reminder to think about those interactions may be good.

**Comment by T4rk1n** [comment]
Added missing docstring warnings to the cookiecutter.

https://github.com/plotly/dash-component-boilerplate/pull/14/commits/8d684d1cbe017c185e7b3174742cabd2c649e256

**Comment by T4rk1n** [comment]
Added assets check warnings in the cookiecutter.

https://github.com/plotly/dash-component-boilerplate/pull/14/commits/0988a63a2fe5fc798c7621da32d6012e3738240a

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
