### ISSUE TITLE
Include dash_core_components, dash_html_components in setup.py install_requires?

### ISSUE THREAD

**Issue by hinnefe2** [plotly/dash#433]
Thanks for a great tool!

Quick question about the suggested installation approach: I see in the [user guide](https://dash.plot.ly/installation) that the preferred approach is to install `dash` and the two component libraries separately. Is there a reason those libraries aren't included in the `setup.py` `install_requires` section?

I ask because when I went to install `dash` my first instinct was just `pip install dash`. This gave me `ModuleNotFoundError: No module named 'dash_core_components'`, so my next instinct was to clone the repo and `pip install -r requirements.txt` (since I thought there might be lots of missing dependencies and I didn't want to install them all by hand), which sent me down a rabbit hole leading to #14 and #18. 

This is definitely not a big deal, but I think it might make for a smoother user experience if `pip install dash` just worked.

If you're amenable, I'm happy to open a PR for this.

**Comment by chriddyp** [comment]
> I ask because when I went to install dash my first instinct was just pip install dash. This gave me ModuleNotFoundError: No module named 'dash_core_components',

Yikes! I wasn't aware of this. I thought that they were completely independent.

> Is there a reason those libraries aren't included in the setup.py install_requires section?

I like keeping them separate for a couple of reasons:
- Users do a `import dash_core_components` - if they didn't install it explicitly, they might wonder why or how they could do this. The fact that they can do this just by doing `pip install dash` is implicit. This probably doesn't bother many people besides me though 😄 
- It encourages awareness that these are separate, modular projects. One of the core principles of Dash is its plugin system and modular-based approach: `dash_core_components` and `dash_html_components` use the same plugin system that we make available to everyone. Installing the packages separately provides the user with a little bit of awareness about this. Now, in practice, everyone uses `dash_core_components` and `dash_html_components`, so I might be being too pendantic here as well.
- In the installation guide, I also wanted to teach some awareness about versioning and changelogs. That's why we have `pip install dash==0.28.5` rather than `pip install dash`. These packages are changing a lot and it's good for users to be aware of which version they are on and how they can learn about new features and bug fixes (changelog). This one I feel pretty strongly about and, through discussions in the community forum, I think users have a pretty good awareness about this.

All that being said, `pip install dash` _should just work!_. I actually can't replicate your issue: I just created a fresh virtualenv and did a `pip install dash` and it worked:

```
$ pip install dash
Collecting dash
  Downloading https://files.pythonhosted.org/packages/a2/5a/0d664826ef6c10b55ddb72566e274c96a3d399d3f6ad19f3cace96f7891a/dash-0.28.5.tar.gz
Collecting Flask>=0.12 (from dash)
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting flask-compress (from dash)
Collecting plotly (from dash)
  Using cached https://files.pythonhosted.org/packages/d6/3b/abec247e24e2b8f29793811788fe0607062f40eefe3104823ad57f06ecf1/plotly-3.3.0-py2.py3-none-any.whl
Collecting dash_renderer (from dash)
Collecting Jinja2>=2.10 (from Flask>=0.12->dash)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting click>=5.1 (from Flask>=0.12->dash)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting Werkzeug>=0.14 (from Flask>=0.12->dash)
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from Flask>=0.12->dash)
  Downloading https://files.pythonhosted.org/packages/c9/c3/8dadb353944803796515ce68ad3944e6e7acc934f5036c40829cb96e64a1/ItsDangerous-1.0.0-py2.py3-none-any.whl
Collecting nbformat>=4.2 (from plotly->dash)
  Using cached https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl
Collecting requests (from plotly->dash)
  Downloading https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 1.5MB/s
Collecting six (from plotly->dash)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting retrying>=1.3.3 (from plotly->dash)
Collecting decorator>=4.0.6 (from plotly->dash)
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting pytz (from plotly->dash)
  Downloading https://files.pythonhosted.org/packages/52/8b/876c5745f617630be90cfb8fafe363c6d7204b176dc707d1805d1e9a0a35/pytz-2018.6-py2.py3-none-any.whl (507kB)
    100% |████████████████████████████████| 512kB 3.0MB/s
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->Flask>=0.12->dash)
Collecting traitlets>=4.1 (from nbformat>=4.2->plotly->dash)
  Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
Collecting jupyter-core (from nbformat>=4.2->plotly->dash)
  Using cached https://files.pythonhosted.org/packages/1d/44/065d2d7bae7bebc06f1dd70d23c36da8c50c0f08b4236716743d706762a8/jupyter_core-4.4.0-py2.py3-none-any.whl
Collecting jsonschema!=2.5.0,>=2.4 (from nbformat>=4.2->plotly->dash)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting ipython-genutils (from nbformat>=4.2->plotly->dash)
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->plotly->dash)
  Downloading https://files.pythonhosted.org/packages/8c/4b/5cbc4cb46095f369117dcb751821e1bef9dd86a07c968d8757e9204c324c/urllib3-1.24-py2.py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 2.7MB/s
Collecting certifi>=2017.4.17 (from requests->plotly->dash)
  Using cached https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->plotly->dash)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->plotly->dash)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Building wheels for collected packages: dash
  Running setup.py bdist_wheel for dash ... done
  Stored in directory: /Users/chriddyp/Library/Caches/pip/wheels/0d/96/0c/27a9a7012f9444b46d3795cd11098c88cba43b49e23c8f5303
Successfully built dash
Installing collected packages: MarkupSafe, Jinja2, click, Werkzeug, itsdangerous, Flask, flask-compress, decorator, ipython-genutils, six, traitlets, jupyter-core, jsonschema, nbformat, urllib3, certifi, idna, chardet, requests, retrying, pytz, plotly, dash-renderer, dash
Successfully installed Flask-1.0.2 Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 certifi-2018.10.15 chardet-3.0.4 click-7.0 dash-0.28.5 dash-renderer-0.14.3 decorator-4.3.0 flask-compress-1.4.0 idna-2.7 ipython-genutils-0.2.0 itsdangerous-1.0.0 jsonschema-2.6.0 jupyter-core-4.4.0 nbformat-4.4.0 plotly-3.3.0 pytz-2018.6 requests-2.20.0 retrying-1.3.3 six-1.11.0 traitlets-4.3.2 urllib3-1.24
```

Of course, if I try to do `import dash_core_components`, it won't work since it wasn't installed.
```
>>> import dash_core_components
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dash_core_components'
```
And I suppose if my reflex was "oh, that seems broken" rather than "oh, of course, I need to install the package!", then I'd google the error message:
![image](https://user-images.githubusercontent.com/1280389/47454658-b7e6e580-d79d-11e8-8f7e-c21f038a0942.png)

And then I'd see a bunch of issues, instead of installation instructions! 

So, I understand your pain. Not everyone is going to go through our nice user guide chapter by chapter (https://dash.plot.ly/) (no matter how hard I try 😢 ). Many folks will first just find an example online and then attempt to run it.

So, now I'm conflicted. I really like our installation instructions (https://dash.plot.ly/installation) but not everyone ends up on that page when they get started with Dash. And if they don't end up on that page, then they might end up having a bad time.

To start, I'm going to update those issues that appear on google with installation instructions to prevent the rabbit hole. Maybe I'll add some text to `dash.plot.ly/installation` too with that error message, so that it ranks better on search engines. 

I'll keep thinking about this in the meantime. Thank you very much for raising the issue @hinnefe2 and I'm sorry about the rabbit hole 🐰

**Comment by chriddyp** [comment]
Just to follow up, I've edited the top comment of #82, #29, #347, #14, #18, #25 with a note to refer folks to the installation instructions.

**Comment by hinnefe2** [comment]
Hey, thanks for the quick response! (I'm consistently blown away by how responsive you all are on the `dash` team).

There's a slight miscommunication here (which is my fault): `pip install dash` does run without errors, it's just when I go to run a dash app (eg the [Hello World](https://github.com/plotly/dash-hello-world) example) that I get the`ModuleNotFoundError`. This is on me - the app does import both modules so it's clear why I need them (and I should have been more explicit in the initial report).

I think I just got tripped up by my own laziness here 😄, first trying `pip install dash` without reading the docs, then chasing a `requirements.txt` red herring because I was too lazy to manually install missing dependencies.

I think this last bit speaks to your second bullet point (about these being separate, modular projects). In my mind the component libraries were dependencies because I'd never seen a Dash app without them. So when they were missing I thought other "dependencies" might be missing and went looking for `requirements.txt`. Your arguments make sense though so I'm happy to close this.
