### ISSUE TITLE
The link to app.py gist is not working

### ISSUE THREAD

**Issue by pukkinming** [plotly/dash#456]
[Link to app.py gist](https://gist.github.com/lazyspark/f6e74ebc756c19bc3a06e10117333145)

The main part of the code is creating the Flask Server, creating routes and passing the server to the dash app.

_Originally posted by @ghost in https://github.com/plotly/dash/issues/214#issuecomment-385846571_

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
