### ISSUE TITLE
Don't validate configuration set by environment variables

### ISSUE THREAD

**Issue by scjody** [plotly/dash#530]
While working on https://github.com/plotly/streambed/issues/12111, we noticed that `requests_pathname` and `routes_pathname` are validated very strictly, even when they come from environment variables. While this validation makes sense when the values come from a user-supplied `config.py`, validating values supplied by DDS in the environment is unnecessary and prevents us from doing things we know will work, but weren't anticipated by the authors of a particular `dash` version.

@chriddyp @T4rk1n FYI

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
