### ISSUE TITLE
Callback should raise exception when no inputs or events are given

### ISSUE THREAD

**Issue by shoval** [plotly/dash#538]
Currently a MissingEventsException is raised only if a state is given, but no inputs or events are given. 

I suggest that this exception be raised when no inputs or events are given, regardless of whether states are given. In cases where the decorator is given only and output element, no errors are shown, and the callback never gets called.

**Comment by T4rk1n** [comment]
Now that events are removed, there should a single check that the inputs list is not empty.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
