### ISSUE TITLE
Subplots: Unexpected behaviour compared to plotly.py

### ISSUE THREAD

**Issue by aaronpries** [plotly/dash#543]
When updating a figure with subplots, dash turns the subplots into a single plot. Consider the following example:

```python
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.graph_objs as go
from plotly import tools

def get_initial_figure():
    subplots = tools.make_subplots(rows=1, cols=2, shared_yaxes=True, print_grid=False)
    fig = go.FigureWidget(subplots)
    fig.add_trace(go.Scatter(x=[0, 0], y=[0, 1]), 1, 1)
    fig.add_trace(dict(x=[0, 1], y=[0, 1]), 1, 2)
    return fig

fig = get_initial_figure()
fig
```
The following figure shows up:
![image](https://user-images.githubusercontent.com/9529130/51335270-f11fb080-1a81-11e9-9350-d301cbd77c8a.png)
With plotly, I can update both subplots like this:
```python
new_points_left = dict(x=[0, 10], y=[0, 10])
new_points_right = dict(x=[0, 10], y=[10, 0])
new_traces = dict(data=[new_points_left, new_points_right])
fig.update(new_traces)
```
However, if I use dash, it starts with two subplots but after triggering the update both lines are in one common plot:
```python
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([html.Button('Update', id='button'),
                       dcc.Graph(id='graph', figure=get_initial_figure())])

@app.callback(
    dash.dependencies.Output('graph', 'figure'),
    [dash.dependencies.Input('button', 'n_clicks')]
)
def update(input_value):
    if input_value is None:
        return None # Just to prevent an immediate update
    else:
        return new_traces  # the same list of dictionaries!
```
![image](https://user-images.githubusercontent.com/9529130/51335377-3d6af080-1a82-11e9-911a-3895e1fd3f84.png)

**Comment by alexcjohnson** [comment]
Thanks @aaronpries - the issue here is that dash really doesn't have the concept of *updating* a property - at least not in the sense of `fig.update` from `plotly.py`, where it merges the new attributes into the existing figure. Dash is always going to pass along an entirely new figure to the plot, so you need to construct the complete figure again.

**Comment by maulberto3** [comment]
Hi @alexcjohnson I have an issue, maybe related to this, in my subplots, first subplots callback call is ok, but subsequent callback calls, it just won't update some things as intended, for example, layouts won't update, even with fig.update_layout(), and now, it seems that even passing different ordered values, somehow subplots retains the original sorting state, which is not what I'm passing into to. What's the correct treatment of subplots in order to get fully guarantee of updates, whether in new data or layouts passed? Hopefully you can shed some light. Thanks.

**Comment by alexcjohnson** [comment]
@maulberto3 if returning the same figure from a callback gives different results depending on what figure was in the graph before (if any) that's a bug. In order for us to investigate, we'll need a self-contained dash app we can copy-paste and run locally to see the inconsistencies. See if you can create such an app, then open a new issue here and we'll be eager to look into it. Thanks!

**Comment by MKimiSH** [comment]
I think I am running into a similar problem. And I checked the code of `make_subplots()` a bit and think (not 100% sure though) the problem is that `make_subplots()` [sets `_grid_ref` and `_grid_str` of `go.Figure`](https://github.com/plotly/plotly.py/blob/586aeebaad67e013799be8ad84b2c2362ce91d26/packages/python/plotly/plotly/_subplots.py#L882), but these two attributes are not included in the dictionary form, and subsequently plotly cannot recognize that this is a figure with subplots.
