### ISSUE TITLE
Serving large files locally (JS bundles) on windows machines in flask sometimes doesn't work

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#56]
See https://github.com/plotly/dash/issues/46#issuecomment-311466557 for more context

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
