### ISSUE TITLE
Raise an exception if a callback is registered _after_ app start?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#577]
A tricky part about Dash is how callbacks need to be registered before the app starts (https://community.plot.ly/t/dynamic-controls-and-dynamic-output-components/5519).

Some users register them later:
- Perhaps they are wrapping up callbacks in their own component classes and the callbacks are only registered when the class is instantiated
- Or perhaps they register these callbacks inside _another_ callback, see https://community.plot.ly/t/dynamcially-create-layout-elements-and-callbacks-and-then-add-new-ones/19008

Seems like we should "freeze" callback instantiation after app start and raise a helpful exception pointing them to some documentation about why they can't register callbacks after the server has started.

**Comment by stonedseeker** [comment]
Hello 👋
Hi there! I'm interested in working on this. I believe I can help implement the solution as described. 
Is this issue still relevant, i'd like to work on it.

**Comment by T4rk1n** [comment]
Hi @stonedseeker This issue is not really relevant anymore as we would rather want to allow a way to dynamically add callbacks #787

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
