### ISSUE TITLE
determine which input is triggering in callback

### ISSUE THREAD

**Issue by havok2063** [plotly/dash#59]
Since only a single Output is allowed in a callback, and all Inputs must feed into it, how can we determine which input is being triggered during a callback?  I have three time-series line plots that I want to cross-filter, and update, any time a range is selected in any of the other plots.   For example, the range of Plot A should update when either the range of Plot B or Plot C is updated.  But the callback collects the ranges from all plots simultaneously.  Is there a way to get the id of which input was triggered during a callback?  

Here is my code but it only updates with data from plotB, when it is triggered.  When I update Plot C the datac variable is indeed updated but the data from plotB is also passed in again, so the callback function has no knowledge of which plot is actually triggering new input.     

```
@app.callback(
    Output('plotA', 'figure'),
    [Input('plotB', 'relayoutData'),
     Input('plotC', 'relayoutData')])
def display_selected_data(data, datac):

    print('data', data)
    print('datac', datac)

    startx = 'xaxis.range[0]' in data if data else None
    endx = 'xaxis.range[1]' in data if data else None

   # define the new xrange
    if startx and endx:
        xrange = [data['xaxis.range[0]'], data['xaxis.range[1]']]
    elif startx and not endx:
        xrange = [data['xaxis.range[0]'], thedates.max()]
    elif not startx and endx:
        xrange = [thedates.min(), data['xaxis.range[1]']]
    else:
        xrange = None

    traces = [go.Scatter(
        x=thedates,
        y=mdf['uniqvisits'])]
    return {
        'data': traces,
        'layout': get_layout('Unique Visits', 'Date', 'Unique Visits', xrange=xrange)
    }  
```

**Comment by pyenthu** [comment]
Have I believe you will have to write three different call backs and use the beta feature of EVENT and STATE to provide input to the function to generate output.

**Comment by havok2063** [comment]
Can you provide a bit more detail on what the EVENT and STATE features are and how to use them?  I can't find any information in the documentation about them.

**Comment by pyenthu** [comment]
https://gist.github.com/chriddyp/e546a2a2c05df29c868e4cef57fb2105


On Jul 1, 2017 5:51 PM, "Brian Cherinka" <notifications@github.com> wrote:

Can you provide a bit more detail on what the EVENT and STATE features are
and how to use them? I can't find any information in the documentation
about them.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/plotly/dash/issues/59#issuecomment-312429236>, or mute
the thread

**Comment by havok2063** [comment]
Thanks for the link, but this isn't entirely helpful.  There's no description of what events and states are.  I get what events are, i.e. similar to events in javascript, but what are states?  In this example code, they look exactly like Inputs.  What's the difference between an Input and a State and how do I use States?  Can I use them to distinguish which Input triggers a callback?

**Comment by alishobeiri** [comment]
@havok2063 States are arguments passed to the function of the callback that won't trigger the callback itself. So changing the code you provided:

```
@app.callback(
    Output('plotA', 'figure'),
    [Input('plotB', 'relayoutData')],
    [State('plotC', 'relayoutData')])
def display_selected_data(data, datac):
```
In the above code only changes on the relayoutData of plotB would trigger the callback, changes to the layout of plotC would not trigger the callback itself. plotC's relayoutData will be passed into ```def display_selected_data``` as datac and can be accessed when the callback itself is triggered but layout changes on plotC will not directly trigger the callback. 

In terms of what you're trying to do, it might be bit tough to figure out directly which input triggered the callback, but one thing you could do is to have two hidden ```html.P``` element that you tie to separate callbacks and when either plotB changes or plotC changes you set the value of the ```html.P``` element associated with either one to a known value - for example, you could set the element to hold the value of 1 if the plot has changed and a 0 otherwise. You could then pass the paragraph elements as inputs:

```
@app.callback(
    Output('plotA', 'figure'),
    [Input('pHolderPlotB', 'children')
     Input('pHolderPlotC', 'children'],
    [State('plotB', 'relayoutData'), State('plotC', 'relayoutData')])
def display_selected_data(bTrigger, cTrigger, data, datac):
    if(int(bTrigger) == 1):
       # do this 
   elif(int(cTrigger) == 1):
       # do that
```

And to reset the values of ```pHolderPlotB``` and ```pHolderPlotA``` after you have redrawn plotA you could create a third callback that will reset the values of both ```pHolderPlotB``` and ```pHolderPlotA``` back to 0 when ```plotA``` has changed.

There might be easier ways to do this but this is one that came to mind.

**Comment by glyg** [comment]
Hi,

I have a somewhat related design issue with the single `Output` paradigm:
Part of my app is a simple frame by frame player, so just:
a backward button, a frame number input and a forward button like so: 
```
| < | 00 | > |
``` 
Those inputs should then update a graph, showing the desired frame.
The callback looks like:
```python
@app/callback(
    Output('graph', 'figure')
    [Input('frame-num', 'value'),],
    events=[Event('backward-button', 'click'),
                  Event('forward-button', 'click'),]
    )
```

How can I distinguish between the two events (to decrement or increment my frame number)?

Thanks for the good work!

**Comment by pgalilea** [comment]
@glyg I'm facing the same issue

**Comment by jwhendy** [comment]
@glyg I thinks this is key from @chriddyp 's comment [above]():

>One core concept with Dash is that the app is described entirely by its *current* state and not by the *order of events.*

For your example, the frame to display is simply the `frame_num` - `back_clicks` + `forward_clicks`, right? Basically, where did we start and how many times did we increment/decrement via buttons? At least that's how I'm interpreting it.

```
app.layout = html.Div([
    html.Button('<', id='back_clicks', n_clicks=0),
    dcc.Input(id='frame_num', type='number', placeholder='starting frame'),
    html.Button('>', id='forward_clicks', n_clicks=0),
    html.Div(id='graph')])

@app.callback(
    Output('graph', 'children'),
    [Input('frame_num', 'value'),
    Input('back_clicks', 'n_clicks'),
    Input('forward_clicks', 'n_clicks')])
def cback(frame_num, back, forward):
    return frame_num - back + forward
```

**Comment by glyg** [comment]
Hi @jwhendy, thanks for the suggestion! I thought about it actually but was a bit worried about the behavior at boundaries: if you keep on clicking the back button when you already reached 0, you'd need to click forward as many times without seeing anything happening ....

**Comment by jwhendy** [comment]
@glyg ah, I get it now. I don't know `dash` well enough to solve that, unfortunately.

Indeed, my mind keeps thinking of separate callbacks per button (which would update the same output) or needing to do something inelegant like hide "helper variables" inside of a `div` somewhere.

**Comment by chriddyp** [comment]
This feature is being considered through the `PrevInput` or `PrevState` abstraction in https://github.com/plotly/dash-renderer/pull/25. I'm not sure when this work will be finished. If your organization or company would like to expedite this this work through a sponsorship [please reach out](https://plot.ly/products/consulting-and-oem/).

**Comment by ronscoder** [comment]
This is going to be a problem for me, as my app will have buttons with id dynamically generated, and one output area. There may be work-around, but it would mean extra labour.
