### ISSUE TITLE
Is it possible to execute 2 callbacks parallel?

### ISSUE THREAD

**Issue by Anusha0526** [plotly/dash#613]
Hello,

I have a requirement where I am trying to automate git revert functionality as part of dash callback. There are chances of facing conflicts. In such situations as soon as I realise there is conflict I want a URL to be displayed in the web page by using another callback. User resolves the conflict by clicking on the url which redirects then to a online editor. Once done the callback that is performing the revert must resume its execution.
So in simple words I want one callback to perform one action and sets an environmental variable and another callback which is called in certain intervals should check the status of this environmental variable and display appropriate message accordingly on the web page
Is it possible?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
