### ISSUE TITLE
apache deployment of multi-page app

### ISSUE THREAD

**Issue by nikhartman** [plotly/dash#631]
If I wanted to deploy any of the examples found at [https://dash.plot.ly/urls](https://dash.plot.ly/urls) using Apache, what would my `VirtualHosts` configuration need to look like? 

This works to get me to the `/` layout at `server.com/subdir`:

```
WSGIDaemonProcess app user=www-data group=www-data threads=5
WSGIScriptAlias /subdir /path/to/app/app.wsgi

<Directory  /path/to/app>
    WSGIProcessGroup app
    WSGIApplicationGroup %{GLOBAL}
    Require all granted
</Directory>
```

The trouble comes in with redirecting something like the `/page-2` layout. I have tried a few things along the lines of...

```
WSGIScriptAliasMatch ^/subdir\b([-a-zA-Z0-9@:%_\+.~#?&//=]*) /path/to/app/app.wsgi/$1
```
But that seems to redirect all kinds of nonsense. Any thoughts on this? I think the trouble is in the fact that I'm trying to deploy this in a subdirectory on my domain. Still, it feels like I fight I should be able to win.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
