### ISSUE TITLE
Can not debug dash with pycharm well.

### ISSUE THREAD

**Issue by eromoe** [plotly/dash#632]
Hello,

I have some large datafames using flask-caching (I can see cached file size is 375MB) , but dash usually restarted after loading the data.
I tried to use pycharm to debug it,  struggle too . 
It often:

1. restart server after loading data, same as start directly. (This rarely happen on linux, so I want to debug )
2.  got `sqlite3.ProgrammingError` (Looks like dash start in multiple thread? But flask is single thread by default , werid )
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\history.py", line 780, in writeout_cache
    self._writeout_input_cache(conn)
  File "C:\Anaconda3\lib\site-packages\IPython\core\history.py", line 764, in _writeout_input_cache
    (self.session_number,)+line)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 12332 and this is thread id 35752

```

python: 3.6.5
os: windows 10
dash: 0.37.0 ~ 0.39.0

**Comment by hrampadarath** [comment]
Hi @eromoe did you ever solve this issue? I'm seeing a similar-ish issue.

Thanks

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
