### ISSUE TITLE
Feature Request: Solid Volume Plots

### ISSUE THREAD

**Issue by SterlingButters** [plotly/dash#648]
It was difficult to decide where to create this suggestion (`plotly.py` or `dash`) but since the goal would include more versatile interactvity, I chose here.

I think solid volume plots could be quite useful. They would be different from surfaces in that when they are sliced with a callback, they are not "hollow". Additionally, one could make several volume plots as traces to select/deselect for better viewing. 

Obviously the challenge would be determining how to fill the volume given one or multiple surfaces.

Something like the following:
<img width="253" alt="Screen Shot 2019-03-13 at 4 13 39 PM" src="https://user-images.githubusercontent.com/22737286/54311448-f8a79580-45aa-11e9-9b09-d7e3b709488f.png">

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
