### ISSUE TITLE
V0.39.0 not work on jupyter

### ISSUE THREAD

**Issue by tkang007** [plotly/dash#652]
Hi,

I would like to report v0.39.0 issue when useing  with jpyter-plotly-dash at Jupyter.
The notebook cell output is just "Loading...", not finished forever.

When I download to v0.38.0, everything was fine.

Thanks,

**Comment by tkang007** [comment]
This case looks like related with this one, https://github.com/GibbsConsulting/django-plotly-dash/issues/127
So, I will close at case at here.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
