### ISSUE TITLE
Capability of allowing callbacks to produce unique output first time they run, possibly using dcc.Interval?

### ISSUE THREAD

**Issue by michael-ziedalski** [plotly/dash#663]
I have a somewhat unusual use-case of Dash, but one that I do not believe will never be encountered by others or is trivial for Dash's functionality.  I built an app that relies on a `dcc.Interval()` object to trigger a callback (which is supposed to read in data from a constantly updating database outside of Dash). Now, on the first running of this callback, the entire database's data should be imported in, but afterwards on each subsequent run, only the new data should be appended in (for whatever operation the callback needs it for).

I thought of implementing this by having the callback explicitly also check against the `dcc.Interval()` object's `n_intervals`, and run action **A** if `n_intervals == 1:`, and run action **B** for everything else.

Conceptually,  this makes sense. However, practically in my app, this leads to many complications. In my app, I have to frequently disable the `dcc.Interval()` object (such as when the database stops updating), and when I re-enable it, I find that the latest previous `n_intervals` value is in place, so the callback will not act appropriately on its _*new*_ first run. The obvious solution would be to also set `dcc.Interval()`'s `n_intervals` to `0` whenever I disable it to force it to reset, but manually editing `n_intervals` creates frivolous Dependency Loop errors in Dash, so no-go.

So, what I am proposing is a new functionality in `dcc.Interval()` that allows it to resets its `n_intervals` value to `0` whenever `max_intervals` is also set to `0` (how I disable it). This would allow greater needed flexibility in callbacks relying on interval objects to trigger them, and seems to be the easiest way to implement this.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
