### ISSUE TITLE
naming: should `state` in `callback` be plural (`states`)?

### ISSUE THREAD

**Issue by pingf** [plotly/dash#67]
just check the definitions of the callback

```python
 def callback(self, output, inputs=[], state=[], events=[]):
    ....
```
why is the state not the plural form? however , it accepts a list.

**Comment by chriddyp** [comment]
I think that grammatically `state` can refer to a collection of values. I'm used to seeing it in the singular form (referring to a collection of states). It seems like others have too: https://ell.stackexchange.com/questions/84756/singular-or-plural-for-word-state-in-the-following-sentence

You're right that it's inconsistent with the rest of the arguments in this context. I'm not sure if it is worth changing but I'll leave this open for discussion. If we change it, we should change it sooner rather than later to reduce the number of affected users.
