### ISSUE TITLE
support any xyz tile server as a map option

### ISSUE THREAD

**Issue by glw** [plotly/dash#697]
Hi I thought I would add a feature request for allowing additional mapping tiles besides mapbox, such as; openstreetmap, stamen, nextzen, etc. Something similar to [folium](https://python-visualization.github.io/folium/quickstart.html) which allows any source that leaflet.js accepts.

eg.

```
folium.Map(location=[45.372, -121.6972],
           zoom_start=12,
           tiles='http://{s}.tiles.yourtiles.com/{z}/{x}/{y}.png',
           attr='My Data Attribution')
```

**Comment by alexcjohnson** [comment]
@glw if you're talking about extending what the `Graph` component can do, this is a question for plotly.js rather than dash. I see a closed issue over there about changing which *mapbox* server you're connected to https://github.com/plotly/plotly.js/issues/2383, I have no idea how hard it would be to generalize to completely separate tile servers.

Alternatively, here's one person's solution for using folium directly in dash: https://medium.com/@shachiakyaagba_41915/integrating-folium-with-dash-5338604e7c56
That's a semi-static solution, wouldn't work well for arbitrary user-generated maps.

And here's a user-contributed dash leaflet component: https://community.plot.ly/t/show-and-tell-leaflet-component-for-dash/21198 -> https://github.com/chschoenenberger/dash_leaflet
I haven't used it, so no idea what it can do, but it could be exactly what you want, or at least a good starting point.

**Comment by glw** [comment]
@alexcjohnson thanks for the suggestions and directing me to the proper plotly repo. I took a look at the alternate solutions and the dash_leaflet one looks promising!

**Comment by chriddyp** [comment]
for folks coming here from google, see https://plot.ly/python/mapbox-layers/, which was added this summer (thanks to a customer that sponsored the development of that feature)
