### ISSUE TITLE
preload component suites?

### ISSUE THREAD

**Issue by ned2** [plotly/dash#706]
When running Google's [Pagespeed tool](https://developers.google.com/speed) over a Dash app (with debug mode off and running on a WSGI server) the biggest improvement that is suggested to me is [preloading requests](https://developers.google.com/web/tools/lighthouse/audits/preload) for assets that are fetched subsequently by the dash renderer. It looks like this could be the various component suites' JavaScript that this could apply to. Wondering if this could be a simple performance enhancement?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
