### ISSUE TITLE
[Feature Request] Environment check tool for integration test

### ISSUE THREAD

**Issue by byronz** [plotly/dash#759]
Thanks so much for your interest in Dash!

Before posting an issue here, please check the Dash [community forum](https://community.plot.ly/c/dash) to see if the topic has already been discussed. The community forum is also great for implementation questions. When in doubt, please feel free to just post the issue here :)

**Is your feature request related to a problem? Please describe.**
This happens more than once among dash core developers that the local `venv` integration environment might be slightly different than the Circle CI Docker environment. 

- mismatch of component version
- git commit sha is not the same, i.e. CircleCI docker contains the latest commit head from master, but locally might not always be the case
- mismatch of webdriver & browser version

**Describe the solution you'd like**
A simple script or command line tool to gather all the information mentioned above, so you can easily compare the mismatch from your local `venv` and circleci docker

**Additional context**
Part of the problem can be solved easily by using an adapted Dockerfile image based on CircleCI version, but for debugging purpose, locally venv is more flexible and convenient.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
