### ISSUE TITLE
Page fails to load in Safari when using dcc.Input with `list` option

### ISSUE THREAD

**Issue by mkhorton** [plotly/dash#769]
Apologies if this is the wrong repo, not sure if it's a component bug, a renderer bug, or what...

**Describe your context**

```
dash                            0.43.0      
dash-core-components            0.48.0      
dash-html-components            0.16.0      
dash-renderer                   0.24.0      
```

    - OS: macOs 10.14.5
    - Browser Safari
    - Version  12.1.1

**Describe the bug**

Minimal example:

```
import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash(__name__)
app.scripts.config.serve_locally = True

server = app.server

app.layout = html.Div([
    html.Datalist(children=[html.Option(value=v) for v in ["apple", "aardvark", "avocado"]], id="suggestions"),
    dcc.Input(value="", id="input_test", type="text", autoComplete="on", list="suggestions")
])

if __name__ == "__main__":
    app.run_server(debug=True, port=8050)
```

**Screenshots**

In Chrome 74.0.3729.169 (Official Build) (64-bit) this works:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/2976580/59323962-cb45b300-8c91-11e9-9b44-11345703bdc5.png">

While in Safari Version 12.1.1 the page fails to load entirely:

![image](https://user-images.githubusercontent.com/2976580/59324014-fa5c2480-8c91-11e9-9c39-75b9a8b543cd.png)

**Comment by alexcjohnson** [comment]
Thanks for posting @mkhorton - we're not getting anything in the console, just a crash inside Safari. `<datalist>` is brand new there, looks like it was only made available at all in March this year. Given the symptoms and the fact that it works correctly in Chrome and FF (and the fact that our `html` components are stupid simple passthroughs), my feeling is this is a bug in Safari, not in Dash.

But let's keep this issue open, see if anyone has other debugging insights or at least to come back to after the next Safari release.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
