### ISSUE TITLE
Catching zoom level in time-series data as input in a chained callback?

### ISSUE THREAD

**Issue by mikkokotila** [plotly/dash#775]
I have time-series data, where timestamp is on x-axis. When I zoom in, how can I capture that as the input for the next callback. So when plot-A is zoomed in, plot-B in the same app automatically follows it.

**Comment by alexcjohnson** [comment]
Here's a starting point https://community.plot.ly/t/zoom-or-pan-one-graph-to-zoom-or-pan-in-other-graph/10158
You have to be a bit careful about this because there can be other things than just zoom that create `relayoutData`, and `relayoutData` only contains the latest change. You can use a `dcc.Store` to accumulate changes.

**Comment by mikkokotila** [comment]
@alexcjohnson Really cool, thanks a lot :)
