### ISSUE TITLE
[BUG] Auto-generated docstrings contain JS boolean values instead of Python boolean values

### ISSUE THREAD

**Issue by shammamah** [plotly/dash#795]
Prompted by https://github.com/plotly/dash-bio/pull/379#discussion_r297840872

While `true` and `false` are not capitalized in JavaScript, they are capitalized in Python. The Python components' docstrings should reflect this, since other JS types are "translated" into Python types (e.g., `PropTypes.shape` -> `dict`).

**Comment by alexcjohnson** [comment]
This is one piece of what I think is a much bigger issue that @rpkyle and I were discussing yesterday: translating docstrings from JS to client languages. Right now we do a good job of translating `propTypes` - because these are code. But the docstrings are currently a hodgepodge of JS and Python syntax, and we probably can't simply regex replace eg all `true` to `True` in the Python generator because sometimes it may just be the word "true", not the symbol.

I propose we switch to pure JS syntax in the JS docstrings, but anything that should be translated for client languages we decorate in a not-too-obtrusive way - something like `%true%` or `~true~` - then we can build up dictionaries for each client language to replace them.

**Comment by alexcjohnson** [comment]
Ah I see, the defaults did come from code, not the docstrings. So yes, #796 can close this one for Python (though R is going to need its own translation with more than that - `[]` and `{}` at least) but we should open a new issue for the docstrings.
