### ISSUE TITLE
Translate JS docstrings to client languages

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash#797]
As discussed in #795 

Right now we do a good job of translating `propTypes` - because these are code. And #796 translates default values - which are also code - for Python, though we'll need something more substantial for R to handle things like `[]` -> `c()` or whatever.

But the docstrings are currently a hodgepodge of JS and Python syntax, and we probably can't simply regex replace eg all `true` to `True` in the Python generator because sometimes it may just be the word "true", not the symbol.

I propose we switch to pure JS syntax in the JS docstrings, but anything that should be translated for client languages we decorate in a not-too-obtrusive way - something like `%true%` or `~true~` - then we can build up dictionaries for each client language to replace them with the correct form for that language.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
