### ISSUE TITLE
PropTypes.exact descriptions flow oddly in some R package docs

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#799]
As @shammamah noted in plotly/dash-bio#382, the flow of description strings is somewhat odd. Example: the `dashbioCircos.Rd` file contains the following information for `layout`:

```
\item{layout}{List of lists containing elements 'len', 'color', 'label', 'id'.
those elements have the following types:
  - len (numeric; required): the length of the block.
  - color (character; required): the color of the block.
  - label (character; required): the labels of the block.
  - id (character; required): the id of the block, where it will recieve
data from the specified "track" id.s. The overall layout of the Circos graph, provided
as a list of dictionaries.}
```

Ideally, the line 

> _The overall layout of the Circos graph, provided as a list of dictionaries._

should follow

> _List of lists containing elements 'len', 'color', 'label', 'id'._

The R package generation code should be modified to more elegantly handle these descriptions. This may require slightly rewording/modifying the line _those elements have the following types_.

@alexcjohnson

**Comment by alexcjohnson** [comment]
There's also "id.s" ie an errant plural. That part at least was already fixed on the Python side, I believe... which makes me think we have an opportunity to share code - we should only have one routine constructing these blocks, that just has separate specific type conversions for the different languages.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
