### ISSUE TITLE
[Feature Request] Keep same color within LegendGroup: distinguish by colorscale or dash style instead.

### ISSUE THREAD

**Issue by samtaz44** [plotly/dash#809]
Within a LegendGroup, it would be good to distinguish scatter legends by another attribute than the color. 

Suggestion: option to keep the default plotly color for **all** the lines within that LegendGroup, and differentiate them in another way, like using a color gradient dominated by the default color, or keeping the exact same color rgb code but differentiating by the style (dashed lines with gradual distance between dots for instance). 

Specification: This would need to be kind of ‘automated’ because the number of sublegends (which I call scenarios in the illustrated example below) within a group varies depending on the group selected by the user in the dropdown menu. As a result, the rgb color/style cannot be hardcoded by default.

Example:
The screenshot below shows how my app looks like, with two graphs and their respective legends.
Upper Graph Legend (depends on what Group(s) the user selects in the dropdown menu):
-Group1
-Group4
-Group6
-Etc, selected by the user in the dropdown menu

Lower Graph Legend (depends on what Group(s) the user selects in the dropdown menu):
-Group1
-Group1-Scenario1
-Group4
-Group4-Scenario1
-Group6
-Group6-Scenario1
-Group6-Scenario2
-Etc, selected by the user in the dropdown menu

At the moment if the user picks Group1 which only has one scenario the color will match between the two Graphs.
However when the users selects for instance Group6, then only Group6-Scenario1 in the lower chart will match the color of Group6 (green in my example), whereas Group6-Scenario2 will have another color, which is not what I would like. I’d like these two scenarios to inherit from the Group6 green color, and be differentiated by another style variance.
![image](https://user-images.githubusercontent.com/52541102/60677161-039b7400-9e81-11e9-96d9-b18170a93e19.png)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
