### ISSUE TITLE
PreventUpdate not stopping changes, figure gets blank

### ISSUE THREAD

**Issue by abdulbasitds** [plotly/dash#833]
It was suggested that to avoid changing the output and aborting the callback, we should rait PreventUpdate esception. I tried it like this

`raise dash.exceptions.PreventUpdate("No data changed!")`

and

`raise dash.exceptions.PreventUpdate`

But still my graph gets blank, is there any issue for this regarding figure output callback as below

@app.callback(
    Output('mygraph', 'figure'),
    [Input('submit_button', 'n_clicks')],
    [State('date_range', 'start_date'),
    State('sb_slider', 'value')]
)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
