### ISSUE TITLE
Remove editor configuration from repo

### ISSUE THREAD

**Issue by Batalex** [plotly/dash#834]
Hi,

I previously noticed that there is a `.vscode/` folder in the index.
We should remove it from the index as it conflicts with the `.gitignore` (and mess up my own editor!).

I could make a quick PR, but first I would rather leave it to someone who wants an easy first contribution to a project.

**Comment by Marc-Andre-Rivet** [comment]
@Batalex Thanks for the comment. I would be interested in knowing what IDE you are using and what issues related to .gitignore interacting with the .vscode folder you are experiencing. Many in the team use vscode as their main editor and we’ve found these integrations useful and never had compatibility issues with other editors.

That said the presence of “python.pythonPath” with “/user/byron” as a path is problematic and it should have been saved in the user settings instead of the repo’s settings. 

@byronz, something more comes to mind?

**Comment by Batalex** [comment]
I mainly use Pycharm & VSCode as well, however when working on Dash I tend to avoid VSCode because of this, sorry if I was not clear enough in my first message. I personally prefer to have my virtual environments with the sources so I defined the pythonPath to be the `venv` folder under the working directory in my global settings.
Myproblem with the repo is that the local settings overrides the global's.

I do not mind changing the configuration to fit my specific workflow, but the changes are not ignored as they should. `git check-ignore` does not show any issue with the `.gitignore` file in itself, my guess is that it is because the folder is already in git's index.

**Comment by byronz** [comment]
@Marc-Andre-Rivet  we should probably avoid this in the code, and if a common setting snippet make sense for dash developers, we can share that in contributor guide
