### ISSUE TITLE
[Feature Request] Dashboard templates

### ISSUE THREAD

**Issue by yinshurman** [plotly/dash#839]
** dashboard templates
dash is very great to  plot graphs, but to quickly make a dashboard ,you have to write quite many  boilerplates codes to get started.
is it possible have some templates just like R shinydashbord https://rstudio.github.io/shinydashboard/

**Comment by byronz** [comment]
@yinshurman  this feature is included in [Dash Enterprise](https://plot.ly/dash/design-kit/), not available in open source verion.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
