### ISSUE TITLE
Sankey diagram problem

### ISSUE THREAD

**Issue by crazycodingcat** [plotly/dash#84]
Hi,

I am trying to reproduce this sample Sankey diagram from plotly in Dash: https://plot.ly/python/sankey-diagram/

I just copy-pasted the sample code and in my dash application use 
`dcc.Graph(figure={'data':  [data_trace], 'layout': layout})`

The graph gets rendered but the rectangles are not displaying: 
![sankey](https://user-images.githubusercontent.com/7253103/28205283-f8db6138-68b3-11e7-981e-e7039d2fd659.png)

I checked the properties of the `rect` svg elements and found the height is negative. Any idea why this happens?

Thanks,
Xuan

**Comment by alishobeiri** [comment]
Hey @crazycodingcat,

Thanks for the question. 

Try changing the value of `pad` inside the node dictionary to be equal to 5.

For example:
```
    node = dict(
      pad = 5,
      thickness = 15,
      line = dict(
        color = "black",
        width = 0.5
      ),
      label =  data['data'][0]['node']['label'],
      color =  data['data'][0]['node']['color']
    ),
```

The same effect can be achieved by increasing the height of the graph in the layout. This happens when the padding between nodes is too high for the height of each node to fit inside the graph.

**Comment by crazycodingcat** [comment]
@alishobeiri Thanks! Yes that works like a charm :)
