### ISSUE TITLE
[BUG] How do i use the input of user for authentication using my own logic

### ISSUE THREAD

**Issue by qxlsz** [plotly/dash#840]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                 0.43.0
dash-auth            1.3.2
dash-core-components 0.48.0
dash-daq             0.1.0
dash-html-components 0.16.0
dash-renderer        0.24.0
dash-table           3.7.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Mac
    - Browser Vivaldi
    - Version 

**Describe the bug**

When using dash auth, it checks for a key value pair which we already hardcoded, instead is there a way i can send the input credentials to another end point and validate against it ?
**Expected behavior**

**Screenshots**

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
