### ISSUE TITLE
[Feature Request] prop docstring syntax requirements

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash#853]
Currently it's pretty easy to make docstrings in js-land that become unreadable in Python/R built docs - and in fact this can cause bugs in dash-docs since we use these built docs to generate them - see https://github.com/plotly/dash-docs/pull/479 and https://github.com/plotly/dash-table/pull/534

Two options come to mind:
1) Require certain formatting of the js docs, and fail to build if those requirements are not met. For example, no unindented bullet lists (-), and no newlines within the doc for one prop
2) Fix the formatting during build - removing newlines, adding indentation

(2) would be nice, but I worry that we may cause other problems with readability with our changes. (1) ensures that the source and built docstrings look as similar as possible but may frustrate users with seemingly trivial errors.

cc @shammamah @Marc-Andre-Rivet

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
