### ISSUE TITLE
Displaying local pdf files within app

### ISSUE THREAD

**Issue by 7pihupriya** [plotly/dash#871]
Hi All,

i'm not able to find a way where i can display local pdf's with in the app

**Comment by dhruvrnaik** [comment]
I am looking for a way to do this too.

**Comment by alexcjohnson** [comment]
Have you tried `html.Iframe(src='/assets/mydoc.pdf')`?

Folks on https://community.plot.ly may have ideas as well.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
