### ISSUE TITLE
Plotly or dash to work with vtkjs?

### ISSUE THREAD

**Issue by laserman781** [plotly/dash#886]
I am using Pyvista which is built on top of vtk to create a vtkjs rendering scene, I was wondering if it was possible to have vtkjs as a window in dash. I am using voila, voila-vuetify, and ipywidgets to create a webapp, but I am looking for a good solution for embedded plotting. 

Is something like this possible with plotly dash?

Thank you!

**Comment by quaeritis** [comment]
I would also be very interested in such an integration, [itk.js](https://github.com/InsightSoftwareConsortium/itk-js) and [vtk.js](https://github.com/Kitware/vtk-js) directly in plotly to support the plotting of vtk objects would be great. As a reverence here is a link to [itkwidgets](https://github.com/InsightSoftwareConsortium/itkwidgets).

**Comment by xhlulu** [comment]
[Dash VTK](https://github.com/plotly/dash-vtk) brings vtk.js directly into Dash :)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
