### ISSUE TITLE
Is it possible to add a hyperlink to data points in a scatter plot 

### ISSUE THREAD

**Issue by lx1054331851** [plotly/dash#912]
![c1b91ef7d031c183c6f682712fbca7e4f17df8f1](https://user-images.githubusercontent.com/12423206/64472155-919b2000-d18c-11e9-986e-b9baa1aa70f8.gif)
Through the hyperlink, I can show more infomation of the data to the audience.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
