### ISSUE TITLE
Add autocomplete option to Dropdown (and others)

### ISSUE THREAD

**Issue by sjtrny** [plotly/dash#960]
I would like an option on Dropdown (and probably other inputs) to disable the browser autocomplete.

I ran into this issue when I created a Dropdown with the ID of "postcode". A user reported that on Android Chrome the browser prompted them to enter their postcode.

`dcc.Dropdown(id="postcode", options...)`

The browser seems to infer the autocomplete type from the ID of the Input. I got around this by changing the ID to something other than an autocomplete type.

This feature already exists for dcc.Input, so this is a request for parity with the other input types.

Reported elsewhere:
- https://community.plot.ly/t/disable-autocomplete-for-input-box-in-dash/22463
- https://community.plot.ly/t/disable-autocomplete-for-dcc-dropdown/24559

**Comment by sjtrny** [comment]
I guess a general and more powerful solution, would be to allow attributes to be set on all Components via a dictionary. This could be considered an extension of the currently supported `aria-` and `data-` but allowing any attribute (that doesn't collide with the inbuilt).

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
