### ISSUE TITLE
[BUG] plotly express facet_row / facet_col keeps options in memory

### ISSUE THREAD

**Issue by legendsam** [plotly/dash#988]
Hello all,
Thanks first of all for all the great job you're doing.

@nicolaskruchten 
I face the following issue when I try to update a scatter plot or bar plot with express package in addition with filters from Dash.

Reproducible example :
```
import dash
from dash.dependencies import Input, Output,State
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd
import plotly.express as px

data= px.data.tips()
    
app = dash.Dash(__name__)
app.layout=html.Div([
    dcc.Dropdown(id='select',options=[{"label":i,'value':i} for i in data.day.unique()],placeholder="choose...",multi=True,value=["Sun"]),
    html.Div(id="output")
])

@app.callback(Output("output","children"),[Input("select", "value")])
def update(selection_value):
    test=data[data.day.isin(list(selection_value) or [])]
    graph=px.scatter(test,y="day",x="tip",facet_col="smoker")

    return [dcc.Graph(figure=graph)]

if __name__ == '__main__':
    app.run_server(debug=True, use_reloader=False)
```

If I pick up all options from the dropdown button then remove Saturday, the label still appears on the plot.

Thank you !
![image](https://user-images.githubusercontent.com/37372020/67864440-eb352080-fb25-11e9-96e0-9e4bba9c7890.png)

**Comment by legendsam** [comment]
Some more specifications about my **configuration** :
dash-auth (1.3.2)
dash-bootstrap-components (0.7.1)
dash-core-components (1.3.1)
dash-html-components (1.0.1)
dash-renderer (1.1.2)
dash-table (4.4.1)

**front end**
Browser Google Chrome Version 77.0.3865.120 windows
or Firefox 65.0.1 (32 bits) windows

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
