### ISSUE TITLE
[BUG] dash app crashes when querying mysql in `render_layout()` when `debug=True`

### ISSUE THREAD

**Issue by schmidt-jake** [plotly/dash#991]
making `debug=False` solved the issue, but why does this happen when in debug mode?

**Comment by JakeTheWise** [comment]
I was running the app from a docker container. There were no error messages in the docker container. The app would successfully get to the `Loading...` screen, where inspecting the network traffic revealed many 502 errors in the dash api calls, mainly to get the dash minified js.

**Comment by alexcjohnson** [comment]
Hmm OK - I have no idea why this is only a problem in debug mode and have not managed to reproduce, but a 502 from the js bundle requests, after having already received the index page implies that the server is locked up while executing the query and can't handle the additional requests. How long does the query take? Any chance you could move the query out of the main layout and into a callback?

**Comment by JakeTheWise** [comment]
The query takes a few seconds. Yes, moving it into a callback was an idea I thought about!

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
